### ISSUE TITLE
Arrêt et reprise d'un import en cours : où doit-on le reprendre ?

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/gn_module_import#10]
Un petit choix sur ce point. 

Actuellement, quand on crée un nouvel import, on commence par sélectionner son jeu de donnée. Dès ce moment là, on a créé un import avec son ID. A partir de ce point, on peut stopper un import quand on veut et le reprendre.

Dans un premier temps, j'envisageais que le formulaire se réouvre toujours à la première étape, pré-remplie, puis on peut aller à la seconde, pré-remplie si on avait fait le travail, et ainsi de suite.  A noter qu'on a que 4 étapes en tout, donc c'est assez vite-fait de passer à la suivante. Ca me semblait bien pour revoir rapidement ce qu'on avait fait avant de finir son import.

Une autre possibilité est de stocker l'étape à laquelle on a stoppé l'import, et d'arriver directement à cette étape.... mais sans repasser rapidement ce qu'on avait fait avant de le mettre en standby. 
Malgré tout, on peut toujours cliquer sur le fil d'ariane pour revenir aux étapes précédentes...

Globalement, mieux vaut-il revenir toujours au début avec des formulaires pré-remplis, ou revenir directement à son étape à votre avis?  

Question plus de fond : doit-on considérer qu'un import est en cours quand on a simplement choisi un JDD mais même pas uploadé de fichier? Si on revoit toutes les étapes, il faut clairement voir qu'un fichier a été uploadé, pour que l'utilisateur n'ait pas l'impression qu'il doit recharger son fichier...  

A y réfléchir, je me dis que finalement et contrairement à ce qu j'avais en tête, il est peut être plus efficace de reprendre directement à la dernière étape.... puisqu'on peut revoir les étapes précédentes en cliquant sur le fil d'ariane...

**Comment by camillemonchicourt** [comment]
Autant reprendre à la dernière étape. Revenir en arrière pour vérifier est possible, mais le faire à chaque fois, c'est un peu lourd et pas utile.

**Comment by DonovanMaillard** [comment]
On stockera l'étape à laquelle l'utilisateur a abandonné l'import, et la reprise se fera à cette étape. Un champ 'step' dans la base permettra de sauvegarder l'étape à laquelle l'import a été mis en standby.
