### ISSUE TITLE
[OBS SANS GEOM] - Le module d'import doit intégrer des données rattachées

### ISSUE THREAD

**Issue by TheoLechemia** [PnX-SI/gn_module_import#107]

**Comment by camillemonchicourt** [comment]
Si une donnée est fournie sans géométrie (x et y ou wkt), alors l'import cherche si des données sont présentes dans les champs ``codecommune`` ou ``codemaille`` ou ``codedepartement``. Si c'est le cas alors il cherche leur ``id_area`` et leur géométrie correspondantes dans la table des zonages du schéma ``ref_geo`` pour les importer.

**Comment by camillemonchicourt** [comment]
Fait dans la 1.1.0.
