### ISSUE TITLE
Champs obligatoires conditionnels

### ISSUE THREAD

**Issue by TheoLechemia** [PnX-SI/gn_module_import#108]
J'ai rajouté les colonnes "codemaille", "codecommunes et "codedepartement' au mapping par defaut "synthese GeoNature".
Quand je charge un nouveau fichier qui ne contient pas ces colonnes, cela me renvoie "La colonne codeMaille n'existe pas. Avez-vous selectionner le bon mapping". Alors que j'ai laissé le champ "codemaille" vide dans le mapping des champs.
En fait quand on charge le mapping, le champs "codemaille" est bien rempli pour le reactiveForm Angular, mais la valeur n'apparait pas comme selectionnée sur l'interface, car en effet le fichier n'a pas de colonne "codemaille".

Est-ce que c'est vraiment un bug ? Est-ce qu'on peut fournir un fichier qui ne contient pas TOUTE les colonnes déclarée dans le mapping sans que cela lève une erreur ? En tout cas il y a bien un bug côté front, car le champs "codemaille" ne devrait pas être remplit si il n'est pas affiché à l'utilisateur.

**Comment by jpanijel** [comment]
Les champs "codemaille", "codecommunes" et "codedepartement" sont des **champs obligatoires conditionnels**.
Ils ne sont pas forcément obligatoires dans le standard, ils ne doivent donc pas être obligatoires lors de l'import **SAUF si l'un des champs obligatoires   des concepts sont remplis et importés via le fichier**.

**Comment by DonovanMaillard** [comment]
C'est bien le cas ici, le soucis levé par théo concerne simplement le mapping par défaut GeoNature, mais tout mapping peut se faire sans ces champs s'ils ne sont pas fournis. Reste à corriger, donc, le mécanisme de remplissage du mapping si le champs n'est pas fourni dans le fichier source. 


Pour @TheoLechemia , en théorie on a un mapping = un format de fichier. Donc si je change de format, je change de mapping. Maintenant, si le module peut avoir un peu de souplesse et remplir les champs présents, et ignorer les champs vides (pour peu qu'ils ne soient pas obligatoires), ça simplifierait les choses dans quelques cas oui.

**Comment by jpanijel** [comment]
Oui il me paraît important que les champs non fournis dans le fichier et non obligatoires dans le standard mais présents dans le mapping ne génèrent pas forcément d'erreur. 
Dans GINCO il y a un mécanisme intermédiaire où le paramétrage des modèles d'import (mapping ici) par les administrateurs leur permet néanmoins de définir des champs obligatoires à l'import en plus du standard. 
Est-ce envisageable dans le module ?

**Comment by TheoLechemia** [comment]
> Maintenant, si le module peut avoir un peu de souplesse et remplir les champs présents, et ignorer les champs vides (pour peu qu'ils ne soient pas obligatoires), ça simplifierait les choses dans quelques cas oui

@DonovanMaillard  C'est bon je l'ai corrigé.

> Dans GINCO il y a un mécanisme intermédiaire où le paramétrage des modèles d'import (mapping ici) par les administrateurs leur permet néanmoins de définir des champs obligatoires à l'import en plus du standard.

Actuellement on peut le faire mais pour l'ensemble du module, pas mapping par mapping, via la table ``dict_field`` qui décrit les champs cible de la table synthese (leur nom, s'ils sont obligatoire etc...). Je le verrait bien ici, parce que le fait qu'un champs soit obligatoire dépend de la table de destination (synthese en l'occurrence) et non de chaque mapping. Ce sera le cas aussi si on ajoute un autre standard d'import (habitat par exemple), on définira les champs obligatoires pour le nouveau standard dans cette même table

**Comment by jpanijel** [comment]
Ok. Cette fonction servait surtout à rendre obligatoire certaines informations selon les types de données, donc plus au niveau des données protocolées. As-tu envisagé d'adapter le module d'import pour ces données ?

**Comment by TheoLechemia** [comment]
Pour les données protocolées ?

**Comment by jpanijel** [comment]
oui

**Comment by TheoLechemia** [comment]
Pas dans l'immediat. Cela necessite d'implémenter les champs additionnels dans la synthese.

**Comment by jpanijel** [comment]
ok

**Comment by TheoLechemia** [comment]
Non reproduit

**Comment by DonovanMaillard** [comment]
Les champs additionnels sont désormais dans la synthèse, et on prévoit d'ajouter un mécanisme pour que le module d'import puisse alimenter ce champs prochainement (#165 ) 

En revanche pas prévu dans ce cadre d'avoir des champs obligatoires conditionnels, qui compliqueraient bien les choses par rapport à ce qu'on prévoit.

**Comment by camillemonchicourt** [comment]
Champs conditionnels obligatoires des codes de zonage pris en charge dans la 2.0.0.

**Comment by camillemonchicourt** [comment]
Dans la version 2.0.0, on peut mapper les champs XY, wkt et/ou les codes géographiques.
Ainsi on peut avoir un fichier source qui mixe ces informations pour la géométrie de base. 
Par contre il ne faut pas qu'une ligne du fichier source ait à la fois des XY et un WKT si ces 2 champs sont mappés.

Si on a mappé une géométrie précise (XY ou WKT) et un code géographique et qu'une ligne du fichier source dispose des 2, on va prendre la géométrie précise et ignorer le code géographique.

Si on a mappé plusieurs codes géographiques et qu'une ligne dispose d'infos sur différents codes géographiques, on aura une erreur car on ne sait pas lequel prendre (les codes géographiques n'étant pas hiérarchisés)
