### ISSUE TITLE
Mauvaise récupération des nomenclatures par défaut

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/gn_module_import#111]
Si je ne renseigne rien dans mon mapping des champs pour un type de nomenclatures, alors le module attribuera bien à toutes mes données les valeurs par défaut paramétrées pour mon instance. 

En revanche, si je renseigne un chzmps (stade de vie par exemple), alors il me récupère les valeurs mappées, mais n'attribue pas de valeur par défaut aux données pour lesquelles l'information est vide. 

De mémoire ça avait été testé et c'était fonctionnel un temps, il faudrait voir pour remettre en place ce mécanisme par la suite.

**Comment by camillemonchicourt** [comment]
Corrigé dans la 1.1.0 avec le paramètre ``FILL_MISSING_NOMENCLATURE_WITH_DEFAULT_VALUE`` ?

**Comment by DonovanMaillard** [comment]
je testerai

**Comment by DonovanMaillard** [comment]
Toujours d'actualité. 

Quand j'ai un champs avec certaines lignes renseignées et d'autres pas : 
- On ne peut pas sélectionner le "blanc" pour le faire correspondre manuellement
- La valeur par défaut n'est pas récupérée et génère une erreur serveur. (message : internal error durint content mapping user values to id_types, details: users_col.

**Comment by camillemonchicourt** [comment]
Dans la version 2.0.0, on peut (on doit) associer les valeurs vides à une valeur de la nomenclature. 
Donc plus de soucis.

![image](https://user-images.githubusercontent.com/4418840/203352297-c7579c3d-279f-4002-ab70-85549d314db9.png)

Le paramètre ``FILL_MISSING_NOMENCLATURE_WITH_DEFAULT_VALUE`` (https://github.com/PnX-SI/gn_module_import/blob/2.0.2/backend/gn_module_import/conf_schema_toml.py#L134) est toujours présent et est bien utilisé, ce qui pose soucis car cela va potentiellement écraser les valeurs mappés pour les champs vides de nomenclatures mappées, si ce paramètre est passé à ``TRUE``.

On propose de supprimer le paramètre ``FILL_MISSING_NOMENCLATURE_WITH_DEFAULT_VALUE`` et la fonctionnalité associée, car désormais dangereuse.

**Comment by DonovanMaillard** [comment]
Sur le 2eme point : 

Est-ce que si je n'ai mappé aucun champs avec la nomenclature sexe, on affiche quand meme la correspondance du sexe pour mapper les valeurs vides, ou est-ce que ce bloc est masqué comme avant ? 

Si masqué, le paramètre reste intéressant pour les nomenclatures masquées/absente du fichier importé. Mais dans ce cas, ca doit passer derrière le mapping "valeur vide" réalisée en front et qui doit etre prioritaire. J'ai pas encore eu le temps de tester...

**Comment by camillemonchicourt** [comment]
Il est masqué comme avant.
Non pas utile de garder le paramètre, car comme avant, c'est la BDD et la table Synthèse qui se charge de remplir les valeurs par défaut des champs qu'on ne renseigne pas lors de l'import.
