### ISSUE TITLE
Fluidification des étapes d'imports de fichiers

### ISSUE THREAD

**Issue by jpanijel** [PnX-SI/gn_module_import#113]
En tant qu'utilisateur, je veux pour que l'import soit le plus fluide possible dans le contexte SINP que l'étape de mapping des champs ne remonte principalement que les champs de mon fichier qui ne sont pas conformes au standard/mapping proposé/imposé (quand il y en a un) et que l'étape de mapping des valeurs ne soit pas obligatoire lorsque j'utilise les nomenclatures préconisées. 

Le workflow proposé est le suivant 
![Fluidification_workflow_Import_3etapes_GINCO2](https://user-images.githubusercontent.com/56294090/78061635-ca4f5080-738d-11ea-968c-9cbdd6b8712d.png)

**Pour l'étape 1** d'upload du fichier: il n'y a pas de changement. Les contrôles de conformité du format du fichier uploadé doivent être faits.

**Pour l'étape 2** de mapping des champs : l'idée principale est que l'application fasse un mapping automatique des champs du fichier et ne propose dans le mapping que les champs qui ne matchent pas ou pas de manière certaine. Cela allègera le formulaire et les champs matchés pourront néanmoins être visibles et modifiés en dépliant un volet non visible par défaut.
Dans un premier temps, le mapping automatique pourra être un mapping exact des champs du fichier avec les champs du standard/mapping par défaut. A terme on pourra améliorer l'algorithme de reconnaissance des champs.

**Pour l'étape 3** de mapping des valeurs/nomenclatures : la philosophie est la même; elle ne doit être proposée que si les nomclatures du fichier ne correspondent pas aux nomenclatures de la plateforme. Du coup il faut que l'ensemble des contrôles de valeurs soient réalisés à l'étape 2.  Si il y a des erreurs de nomenclature alors l'étape 3 est proposée à l'utilisateur avant l'import des données dans la synthèse.

**Pour DEPOBIO** 
Dans un soucis de continuité fonctionnelle, je veux dans le contexte régalien de DEPOBIO pouvoir soumettre un fichier conforme au standard sans possibilité de passer à l'étape 3 de mapping des valeurs/nomenclatures. 

Le workflow serait le suivant
![Fluidification_workflow_Import_2etapes_DEPOBIO2](https://user-images.githubusercontent.com/56294090/78064533-32079a80-7392-11ea-9935-0fdbb2abfc97.png)

**Comment by jpanijel** [comment]
Dans le formulaire de mapping, les valeurs dans les listes déroulantes doivent pouvoir être cherchées via la saisie. Les valeurs des différentes listes de champs doivent aussi être triées par ordre alphabétique.

**Comment by DonovanMaillard** [comment]
Bonjour Judith, 

Nous avons testé les valeurs par ordre alphabétique. Je suis d'accord pour le mapping de contenu, ça peut accélérer les choses. Mais pas pour le mapping des champs à l'étape 2, pour lequel on était revenus en arrière. 

Les fichiers sont, en général, structurés d'une manière assez cohérente. On a donc listé par ordre des champs tels qu'ils sont dans le fichier. Les mettre par ordre alphabétique est en général plus gênant à mon sens. 

Ta proposition ne concerne bien que le mapping de nomenclatures ?

**Comment by jpanijel** [comment]
Bonjour Donovan,
Non ma proposition concerne le mapping des champs. Je ne suis pas d'accord avec toi et tel quel ce mapping est inutisable pour nos utilisateurs. C'est très pénible de ne pas avoir les champs dans un ordre logique. Lorsque l'on a plus de 50 champs dans un fichier, on a beau dire on ne se souvient pas de l'ordre. 
Du coup, la solution sera de passer ce critère en paramètre.

**Comment by DonovanMaillard** [comment]
Ajouter des paramètres pour des détails tels que celui-ci n'est pas forcément une bonne solution, je laisserai théo en juger. Mais il faut aussi veiller, je pense, à ne pas alourdir les fichiers de configuration à l'infini et compliquer le code jusque dans ces moindres détails. 

Dans la pratique, les fichiers qu'on connait bien sont ceux sur lesquels on travaille régulièrement donc qui ont un mapping enregistré. Pour les autres, ok pour avoir un ordre alphabétique, même si ca fait "perdre" 3 secondes de temps en temps.

**Comment by jpanijel** [comment]
Les bureaux d'études ne connaissent pas bien le standard.

**Comment by DonovanMaillard** [comment]
C'est noté! 

Je viens de reprendre le ticket de manière plus large.

Automatiser les mappings autant que possible en faisant une reconnaissance des champs à déjà été évoqué et un fonctionnement possible avait été réfléchi (on stockait, pour chaque champs ou chaque nomenclature, une liste de synonymes qui se complétait à chaque fois qu'on faisait de nouveaux mappings). 

De manière plus globale, je me demande s'il ne serait pas intéressant, au moins dans un premier temps, de proposer : 
- Créer un import : avec le fonctionnement actuel
- Créer un import automatique : avec des mappings par défaut, qui fonctionnent avec un fichier type bien formaté. 

Ce fonctionnement ne serait plus nécessaire une fois qu'on aurait automatisé/rendu intelligent les mappings , mais si cette "intelligence" ne peut pas être faite maintenant, ça permettrait à chacun de pouvoir : 
- définir son format par défaut (exactement le format SINP, ou tout autre format selon les besoins et le profil des uns et des autres)
- définir le mapping par défaut qui doit s'y appliquer
- ne pas se priver pour autant de la possibilité d'avoir des mappings pour les fichiers qui ne seraient pas conformes à son propre format standard. 
En terme d'interface, ca ajoute simplement un bouton sur l'accueil du module. Et si on choisit un import automatique, on reprend tel quel l'étape 1 d'upload, et l'étape 4 de prévisualisation, en masquant à l('utilisateur toute la partie mapping. Si une erreur est détectée, on le renvoie vers un import tel qu'il existe aujourd'hui, avec mappings. 

Ca permet à chacun de bénéficier de cette possibilité d'imports automatiques, sans se priver des mappings pour les fichiers non formatés.

**Comment by camillemonchicourt** [comment]
Concernant l'ordre des champs, lors de mes tests, j'ai aussi trouvé ça galère qu'ils ne soient pas ordonnées par ordre alphabétique. Si certains préfèrent qu'ils soient dans l'ordre du fichier source, un paramètre semble pas très complexe et une bonne solution pour pouvoir l'un ou l'autre. 
Pouvoir chercher dans la liste des champs serait en effet un plus.

Dans la proposition, l'import et l'import automatique sont la même chose, en fonction du fichier importé. Soit il matche avec la mapping par défaut et on zappe des étapes, soit il ne matche pas (ou pas complètement) et on propose les étapes de mapping. Je trouve dommage et complexe de proposer 2 types d'import donc je suis peu favorable. 

J'ai un peu des doutes par contre sur la pertinence de sauter des étapes quand le fichier matche à 100%. Ça peut être perturbant pour l'utilisateur d'avoir des comportements et workflow différents d'une fois sur l'autre. Et ça peut avoir un côté rassurant de pouvoir checker son mapping avant de passer à la suite, même si celui-ci matche à 100%. A voir.

A noter aussi que pour certaines instances, on n'aura pas de mapping par défaut car tout le temps des fichiers hétérogènes. A moins, dans ce cas d'utiliser un mapping type GeoNature ou type SINP pour en avoir un dans tous les cas.

**Comment by jpanijel** [comment]
Oui, pour l'étape 2 je ne pensais pas complètement passer le mapping, je proposais simplement que les champs matchés puissent être visibles et modifiés au cas où dans un volet non visible par défaut. 
Le cas spécifique où tous les champs sont matchés il suffirait d'un message pour le dire en gardant la possibilité de déplier le volet et de confirmer quoi qu'il arrive le mapping.

**Comment by jpanijel** [comment]
Je reprends la formulation initiale de la user story qui effectivement n'était pas exacte

**Comment by DonovanMaillard** [comment]
C'est noté, on aurait donc : 

- Un mapping par défaut facultatif, à renseigner dans la conf
- Si pas de mapping par defaut on ne change rien. 
- Si mapping par défaut, on matche et on "plie" les volets de ce qui fonctionne, et on mets en avant ce qui ne matche pas correctement. 

Même fonctionnement pour les champs + les nomenclatures du coup?

**Comment by camillemonchicourt** [comment]
Oui c'est un truc comme ça @DonovanMaillard.

En complément, on propose ces paramètres : 
- Ajouter un paramètre pour définir si les champs mappés sont affichées ou non par défaut ("default_mapping_mode" par exemple)
- Ajouter un paramètre pour définir si la checkbox permettant de changer de mode d'affichage est affichée ou non ("display_mapping_mode", "True" par défaut)

**Comment by camillemonchicourt** [comment]
Schéma global révisé : 

![Import_Workflow_revu](https://user-images.githubusercontent.com/4418840/80371507-4e63fd80-8892-11ea-9082-7866c62edeaf.png)

Pour le moment, on garde le fonctionnement actuel, qui correspondrait à un profil de type "Administrateur". 
On implémente le CRUVED dans le module sur l'objet "Mapping" pour avoir des utilisateurs avec moins de droits et donc une interface plus simple et des possibilités plus réduites. Notamment le fait de ne pas pouvoir créer/modifier un mapping mais de pouvoir s'appuyer sur un mapping par défaut et d'ajuster les champs différents.

A terme, on s'orienterait plutôt vers un mécanisme de correspondances/synonymes de champs comme proposé par @DonovanMaillard. Et on pourrait même imaginer la substituer totalement aux mapping. On ne stockerait plus que des correspondances de champs qui seraient enrichis à chaque fois qu'on ferait une nouvelle correspondance d'un champs du fichier source avec celui de la destination.

**Comment by camillemonchicourt** [comment]
Fait dans la 1.1.0, mais 
- vérifier que les différents modes sont fonctionnels (notamment pouvoir zapper le mapping des valeurs)
- paramètres et fonctionnement à clarifier dans la documentation.

**Comment by camillemonchicourt** [comment]
Seule a possibilité de masquer le mapping des valeurs a été réalisée.
Le mapping des contenus a été mis de côté pour le moment, dans un ticket dédié : https://github.com/PnX-SI/gn_module_import/issues/100
Les paramètres ont été clarifiés dans le fichier d'exemple de configuration.
