### ISSUE TITLE
Amélioration du rapport d'erreur

### ISSUE THREAD

**Issue by jpanijel** [PnX-SI/gn_module_import#114]
En tant qu'utilisateur non initié au standard du SINP, je veux avoir un rapport d'erreurs clair et précis des différentes erreurs de conformité et corrections automatiques effectuées sur le fichier que je soumets pour pouvoir faciliter les corrections que je dois y apporter.

**Améliorations**
- Pour pouvoir le consulter et le partager facilement, le rapport d'erreur doit être accessible à partir d'une URL et d'une page distincte du processus d'import (ouverture d'un nouvel onglet ou d'une nouvelle page web).
- Le tableau des imports doit proposer un lien vers le rapport d'erreur lorsqu'il y a des données invalides, même lorsque les données valides ont été importées.
- Pour être exhaustif, le rapport d'erreur doit remonter en 3 tableaux distincts les résultats issus des contrôles de conformité, des avertissements et des corrections. 
- Pour être facilement identifiables les résultats des contrôles réalisés seront regroupés selon les groupes et types suivants : 

Groupe   d'erreurs | Type d’erreurs
-- | --
Fichier | Nom du fichier
  | Ouverture du fichier
  | Format du fichier
  | Taille du fichier
  | Lecture du fichier
  | En-tête du fichier
  | Erreur de ligne sur le fichier
  | Droit d’accès
Conformité |  
  | Champ obligatoire
  | Champ obligatoire conditionnel
  | Erreur de format
  | Erreur de référentiel
  | Erreur de nomenclature
  | Doublon
  | Géométrie
  | Géoréférencement
  | Incohérence
Avertissement |  
Correction | 

- En partant du principe que l'ensemble des contrôles sont effectués à l'étape 2, la page du rapport d'erreurs reprend les éléments récapitulatifs de l'import, un tableau listant le nombre d'erreur par type (Faut-il se limiter aux 1000 premières erreurs pour les très gros fichiers?) et le détail des lignes concernées pour chaque erreur. La liste détaillée n'est pas montrée par défaut, elle apparaît en cliquant sur détail

**Import**
Date / heure d'intégration  : 
Identifiant de l'import : 
Modèle d'import : mapping utilisé
JDD cible pour l'import  :
Nom du fichier : [nom fichier]  - (nb de ligne) lignes.

Le tableau listant les erreurs doit indiquer les informations suivantes groupées par groupe 

**Groupe**
Type d’erreur | Nom de la colonne | Nombre d'erreurs | [Action] Détail
-- | -- | -- | -- 

La liste des types des lignes par erreur s'affichent 10 par 10 (ce sont souvent les mêmes erreurs qui reviennent) et doit indiquer les informations suivantes

 **Type d’erreur** 
Champ | Ligne | Valeur dans le fichier | Description | Complément (valeurs attendues si possible).
-- | -- | -- | -- |--

Ces infos sont aussi reprises de manière concaténées dans l'export du fichier des données invalides (pour l'instant on a le nom de l'erreur en anglais).

**Comment by jpanijel** [comment]
La description des erreurs n'est pas toujours parlante pour des utilisateurs non avertis. Je les ai donc repris globalement et complétés au regard des règles du standard, même si cela nécessite de les reprendre lors des évolutions du standard.
Voici le fichier qui reprend l'ensemble des checks. Je les ai séparés par groupes (erreurs, corrections, avertissements) dans différentes feuilles xls. 
Mes ajouts et corrections sont en rouge. J'ai inséré une colonne remarques, complément attendu dans le rapport.
[Contrôles_imports.xlsx](https://github.com/PnX-SI/gn_module_import/files/4414739/Controles_imports.xlsx)

**Comment by TheoLechemia** [comment]
Travail en cours:
- intégration de toutes les erreurs en base sur la base du fichier de Judith : 
https://github.com/PnX-SI/gn_module_import/blob/errors-improvement/data/data.sql#L15
- une nouvelle page "rapport d'erreur"
![rapport_erreurs](https://user-images.githubusercontent.com/15265745/78805962-61d22600-79c2-11ea-8fdb-3375b723d957.png)
- accessible depuis la liste des imports:
![liste_import](https://user-images.githubusercontent.com/15265745/78805999-6d255180-79c2-11ea-87d4-ee336d1a580e.png)

TODO:
- Les erreurs de la 1ere étape (encoding, nom de fichier et tous les contrôle de "goodtable") ne sont pas écrit dans la table des erreurs mais simplement signifié à l'utilisateur sous forme d'un message d'erreur (toaster). 
Est-ce qu'on affiche un rapport d'erreur à l'utilisateur déjà à ce niveau là ? Ou l'info du toaster suffit ?
- Vérifier que tous les "checks" fonctionnent correctement
- Implémenter les vérification de nomenclature (actuellement, si une nomenclature n'est pas trouvée, on pousse la valeur par défaut)
- Grouper le rapport d'erreur si l'étape du mapping des valeur est désactivée

**Comment by camillemonchicourt** [comment]
OK super, merci.
Le Toaster c'est vraiment pas top, pas très clair et on ne voit que les erreurs une par une, après les avoir supprimé dans l'ordre, donc vraiment pas utilisable.
Un tableau des erreurs serait bien mieux je pense.

**Comment by TheoLechemia** [comment]
Petit point d'avancement: 
Une route a été créé pour la vérification des nomenclatures. Le code existant a été completement revu. Les erreurs de nomenclatures sont inclus dans le rapport d'erreur :
![err_nomencl](https://user-images.githubusercontent.com/15265745/79244352-1a8ede00-7e77-11ea-8ede-8d3166365e1d.png)
Un paramètre a été ajouter pour contrôler l'action du remplissage des nomenclatures en erreur par la valeur par défaut: `FILL_MISSING_NOMENCLATURE_WITH_DEFAULT_VALUE`
Reste à intégrer ce mécanisme dans le workflow d'import
