### ISSUE TITLE
Vérification des differents SRID

### ISSUE THREAD

**Issue by TheoLechemia** [PnX-SI/gn_module_import#116]
Actuellement le module ne gère que la vérification pour les SRID 2154 et 4326.
La vérification est faite ligne par ligne pour l'ensemble des points (si c'est un polygone), et les bornes sont en dur dans le code.
Plutôt que de demander à l'administrateur toutes les bornes des SRID qu'il veut autoriser dans le module, je propose de mettre en paramètre la "bounding-box" de l'emprise géographique de la plateforme. 
Au niveau performance on y gagnera également largement, puisqu'on pourra utiliser les fonction optimisée de PostGIS de comparaison de point à bounding-box ou bounding-box à bounding-box dans le cas des polygone.

**Comment by camillemonchicourt** [comment]
Fait. Voir https://github.com/PnX-SI/gn_module_import/issues/130
