### ISSUE TITLE
Export Synthese et mapping Synthese GN par défaut - Erreur typdenbr

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/gn_module_import#118]
Version 1.0.0 du module / Serveur de démo.
J'exporte un CSV de la synthèse de GeoNature puis je teste de l'importer. 
Après uploade du fichier puis selection du mapping par défaut "Synthèse GeoNature", je clique directement sur VALIDER LE MAPPING et j'ai une erreur furtive affichée incompréhensible : 
``La colonne 'typdenbr' n'existe pas. Avez-vous sélectionné le bon mapping ?``

En effet il n'y a pas de mapping pour la colonne "Type de dénombrement" : 

![image](https://user-images.githubusercontent.com/4418840/78790598-0d717b00-79af-11ea-8248-00a9863f6a0d.png)

Mais je ne comprends pas pourquoi il m'affiche cette erreur et c'est peu compréhensible.

**Comment by camillemonchicourt** [comment]
OK c'est du au fait que l'export Synthèse fourni par défaut a été revu et que des noms de champs ont changé depuis la définition du mapping par défaut du module Import. Donc à recaler même si il faudrait encore revoir les noms des champs de l'export par défaut de la synthèse.

Et dans tous les cas il ne devrait pas renvoyer une erreur comme ça et bloquante quand un champs du fichier source n'est pas présent par rapport au mapping défini ?

**Comment by jpanijel** [comment]
Ce qui m'étonne c'est que j'ai eu une erreur bloquante sur le champ deeflou qui ne fait pas partie du mapping par défaut.

**Comment by camillemonchicourt** [comment]
Oui our comprendre il faut regarder (puis revoir) le mapping qui est fournit par défaut et qui ne correspond plus vraiment aux exports par défaut de la Synthèse : https://github.com/PnX-SI/gn_module_import/blob/master/data/default_mappings_data.sql

**Comment by DonovanMaillard** [comment]
En effet, le mapping a été fait sur la base d'un export de geonature démo lors de la sortie du module. Sauf erreur la vue v_synthese_for_export a été revue depuis. 

Pour des champs non obligatoires on pourrait en effet se limiter à une "alerte" ou une info, et ne pas bloquer l'import. Le fonctionnement actuel vient du fait qu'on partait du principe, lors des développements et dans la définition du projet, qu'on avait 1 format = 1 mapping.

**Comment by camillemonchicourt** [comment]
> Ce qui m'étonne c'est que j'ai eu une erreur bloquante sur le champ deeflou qui ne fait pas partie du mapping par défaut.

Ça je vois moins car le champs "Floutage" est bien dans la destination et le mapping : 
![image](https://user-images.githubusercontent.com/4418840/78803515-6517e280-79bf-11ea-9ff8-2e0ec0ef1336.png)

**Comment by jpanijel** [comment]
Ah je crois que je comprends j'ai fait un export depuis occtax et non depuis la synthèse. 
Il va falloir faire qqch pour ça : est-ce que l'on peut désactiver l'export dans occtax ? le problème va se présenter fréquemment pour nos chers utilisateurs lambda (comme moi !)

**Comment by TheoLechemia** [comment]
En fait l'export d'occtax est configurable. On peut faire en sorte qu'il corresponde au mapping fourni sur l'instance

**Comment by jpanijel** [comment]
super 👍

**Comment by camillemonchicourt** [comment]
Ah oui c'est pour ça  !
Oui on l'a désactivé sur certaines instances et il y a des discussions pour recentrer Occtax vraiment plus sur un module de saisie et gestion de ses propres données pour réduire la confusion avec Synthèse

**Comment by TheoLechemia** [comment]
Oups je me suis trompé de ticket pour mes commits, mes excuses.

**Comment by camillemonchicourt** [comment]
Le problème du message d'erreur quand un champs défini dans le mapping n'est pas présent dans le fichier source a été corrigé ici : https://github.com/PnX-SI/gn_module_import/issues/108
Reste à revoir le mapping GeoNature par défaut qui ne correspond plus à l'export par défaut de la Synthèse de GeoNature.

**Comment by DonovanMaillard** [comment]
Je regarde ce dernier point dans les 2 prochains jours ;)

**Comment by camillemonchicourt** [comment]
Les modèles d'import (mappings) fournis par défaut ont été entièrement repris dans la 1.1.0.
