### ISSUE TITLE
Détection automatique de séparateur CSV

### ISSUE THREAD

**Issue by TheoLechemia** [PnX-SI/gn_module_import#119]
Actuellement quand on met un séparateur qui ne correspond pas au fichier, une erreur python sans relation est levée (`psycopg2 has no module errors`).
Je propose que le séparateur soit détecté automatiquement. ça fait une chose de moins à remplir à l'utilisateur et évite des erreurs.

**Comment by camillemonchicourt** [comment]
Oui si possible ça serait idéal.

**Comment by DonovanMaillard** [comment]
Si c'est possible oui, autant automatiser au maximum :) Même chose pour l'encodage si c'est possible d'ailleurs...

**Comment by TheoLechemia** [comment]
Ok, j'ai fais le séparateur. Je garde l'encoding en tête
