### ISSUE TITLE
Permettre le paramétrage et le regroupement des champs en interface

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/gn_module_import#12]
@JulienCorny  m'a sollicité aujourd'hui sur l'interfaçage à l'étape des mappings : 

> au niveau de l'interface pour le mapping de correspondance, ça va être un peu galère d'indiquer quel champs correspond à quelle catégorie, de les ordonner dans le même ordre que ta maquette (parce que je récupère les champs du formulaire en faisant une boucle sur le nom des champs de la synthèse et les résultats arrivent par ordre alphabétique), et enfin la traduction des champs de la synthese en français  est fastidieuse. On peut mettre tout ça en conf mais il me semble que ce serait plus élégant de faire une table dans notre module qui comporte en colonnes id, champs synthese, traduction française, catégorie. Tu crois que c'est faisable ou c'est une mauvaise idée?

2 solutions possibles que je lui ai indiquées donc : 
- Tout définir en dur, offrant assez peu de souplesse mais qui pourrait convenir à l'heure actuelle

- Reprendre le principe de TaxHub, en ayant en effet une table qui permette de créer des sections et une seconde qui permette d'y associer les différents champs de la synthèse à inclure dans ladite section, avec un ordre donné (taxhub le fait très bien, une partie du code est donc déjà dispo, et ça offre une grande souplesse). Ca permet également de donner un nom à afficher en interface pour un champs donné, et donc ca peut faciliter les choses pour avoir un module multilingue par la suite. 

@amandine-sahl  remarque également que ça peut faciliter les choses pour avoir des synonymies à terme, permettant par exemple d'automatiser en partie le mapping (en listant par exemple des noms synonymes de ce qu'on attend dans notre champs, et que le mapping se fasse seul si on a un champs qui porte ce nom dans la table source). 

Ce que je vois également, c'est qu'à termes une telle souplesse facilitera sans doute des développements futurs pour permettre au module d'import de faire des intégrations de données dans autre chose que la synthèse. (en intégrant un id_module, et faire une correspondance entre des champs dudit module et des sections/noms à rentrer en interface pour le mapping... même s'il restera plein de soucis à résoudre pour arriver à cette seconde version du module d'imports). 

A priori donc, je serais bien favorable à avoir 2 tables (une pour les sections, une pour les champs cible de la synthèse, le nom à mettre en interface etc) sur le principe de TaxHub. 
Restera en revanche à rediscuter avec @JulienCorny et son collegue, pour voir comment se gère le widget à afficher en interface (on a pas que des menus déroulants, mais des cases à cocher sur les uuids, la possibilité d'avoir un geom OU un x + un y dans les géométries, etc). Pas mal de réflexions à avoir encore sur ces cas particuliers, mais dans le mapping des champs la plupart des cas sont une liste déroulante comprenant les champs du fichier source : pour ces cas, avoir des tables et une interface paramétrable sera intéressant et ouvre pas mal de perspectives!

**Comment by camillemonchicourt** [comment]
Oui gérer ça dans la BDD est idéal car générique, souple et évolutif

**Comment by DonovanMaillard** [comment]
Validé, julien mettra ce mécanisme en place dans les prochaines semaines.
