### ISSUE TITLE
Performances et traitements parallèles

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/gn_module_import#123]
Pour améliorer les performances et ne plus attendre la fin du traitement au niveau du navigateur client, on propose de réaliser les traitements en parallèle. 

Lorsque l'on charge un fichier, le processus de vérification sera lancé de manière asynchrone pour ne pas avoir à garder mon navigateur ouvert. Idem pour les contrôles des mappings et des données et l'import final dans la Synthèse.

L'ensemble du processus des checks doit être réalisé en tâche de fond sur le serveur. Exécuter toutes les requêtes en arrière plan (dans un thread à part) pour éviter les timeout.

Dans le tableau des Imports : Ajouter une étiquette “Vérifications en cours” à la place de la date de fin de l’import.

Quand un traitement est terminé, une notification doit être envoyée au navigateur pour que celui-ci passe automatiquement à l'étape suivante. Notamment utile pour les petits fichiers dont les traitements asynchrones continueront à être très rapide et ne doivent pas casser l’enchaînement fluide des étapes.

En tant qu'utilisateur,  je veux pouvoir être averti(e) de la fin du processus de vérification pour les gros fichiers de données.

Au delà de x lignes dans un fichier, une alerte annonce à l'utilisateur que son fichier est pris en charge et qu'il va recevoir un mail à la fin du processus de vérification du fichier.

Le nombre de ligne du fichier est un paramètre de la configuration de la plateforme.

On peut s’inspirer de ce qui était fait dans le module Export : https://github.com/PnX-SI/gn_module_export/blob/70829653fc159a25155f73f9fb31a77da5c34973/backend/utils_export.py#L36

**Comment by TheoLechemia** [comment]
A noté, que cela implique que toutes les vérifications de cohérence sur le fichier se font de manière groupées, après les mappings des champs et des valeurs. Les étapes de mappings servent simplement à enregistrer les mappings

**Comment by DonovanMaillard** [comment]
pour le coup, ca "oblige" à faire ses imports en plusieurs fois? A venir corriger son mapping si erreur il y a, repartir, et revenir plus tard que le module a fait ses controles?

**Comment by TheoLechemia** [comment]
ça se discute. Mais aucune des deux manières de faire n'est super optimale. 
Attendre 10 minutes à l'étape une, recevoir une notif pour avertir que c'est terminé, puis re attendre 10 minutes après le mapping des valeur, recevoir une notif, pour enfin envoyer ses données dans la synthese.
Ou alors attendre une seule fois 20 minutes et avoir un rapport complet
?

**Comment by camillemonchicourt** [comment]
Par forcément, comme indiqué plus haut, quand un contrôle est terminé, une notification est envoyée au navigateur pour qu'il passe à l'étape suivante. 
Le fait de grouper les contrôles permet lui d'éviter de fractionner les attentes, que ce soit traité en direct ou en parallèle.

**Comment by TheoLechemia** [comment]
Oui ça n'a pas formément de rapport avec la parallélisation. Quoique sur le code ça va avoir des implications.
La remarque avait plus de sens sur le ticket de la fluidification

**Comment by camillemonchicourt** [comment]
Fait dans la version 1.1.0 où les contrôles ont été regroupés à la fin, entre l'es étapes 3 et 4.
Et avec l'ajout d'un paramètre ``MAX_LINE_LIMIT`` permettant d'activer cette fonctionnalité et de définir à partir de combien de lignes dans le fichier source elle se déclenche.
