### ISSUE TITLE
Doute sur les URL

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/gn_module_import#126]
En voyant mes URL, j'ai un doute... à vérifier. 

L'URL renvoie l'étape, et l'id du dataset. A partir de ce constat, il faudrait vérifier comment fait le module quand on a deux ou 3 imports en cours sur un même jeu de données. Mieux vaudrait que les url comprennent l'étape et l'id de l'import à priori...

**Comment by DonovanMaillard** [comment]
Se limite à la 1ère etape, ensuite c'est bien l'id_import et l'etape qui sont renseignés

**Comment by TheoLechemia** [comment]
Oui l'id_import a été passé dans l'url. Avant tout était basé sur les info stockées dans le localstorage, ce qui posait des problèmes
