### ISSUE TITLE
Problème de format des integers ? 

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/gn_module_import#127]
Dans un fichier de quelques 150.000 lignes, suite à mon premier mapping, le module me renvoie 'internal server error'. 

En allant voir les logs, j'ai l'info suivante : 

> *** ERROR IN CORRESPONDANCE MAPPING
> object of type <class 'numpy.float64'> cannot be safely interpreted as an integer.
> Traceback (most recent call last):
>   File "/home/pole-gnadmin/geonature/backend/venv/lib/python3.5/site-packages/numpy/core/function_base.py", line 117, in linspace
>     num = operator.index(num)
> TypeError: 'numpy.float64' object cannot be interpreted as an integer

**Comment by DonovanMaillard** [comment]
Sur mon instance (dernière release GN sur debian9), c'est NumPy 1.18.1 qui est installée. 

Ce n'est peut-être qu'une piste parmi d'autres, mais le problème semble connu sur cette version et plusieurs utilisateurs recommandent de repasser sur NumPy 1.17 pour régler ce soucis.

**Comment by DonovanMaillard** [comment]
Testé aujourd'hui, problème n'apparait effectivement plus lorsqu'on rétrograde la version de numpy. Le soucis est présent sur numpy 1.18.1 et 1.17.0. Mais absent sur 1.17.4.

Il faudrait donc fixer la version de numpy sur 1.17.4, mais cette dépendance est installée par une autre, je ne sais pas encore la quelle. Elle n'est donc pas directement dans le requirement.txt. A tester. 

En attendant, pour les utilisateurs de cette version qui aurait le soucis, ma manip pour régler le soucis a été la suivante : 

```
cd
source geonature/backend/venv/bin/activate
pip3 uninstall numpy
pip3 install numpy==1.17.4
deactivate
sudo supervisorctl restart all
```

**Comment by DonovanMaillard** [comment]
Beaucoup de modifications pour la release 1.1.0, pas revu sur la nouvelle version.

**Comment by JulienCorny** [comment]
Salut Donovan, 

Même problème avec la release 1.1.0 (numpy 1.20.0) sur un GeoNature 2.5.5 : 

*** ERROR IN CORRESPONDANCE MAPPING
Cannot interpret '<attribute 'dtype' of 'numpy.generic' objects>' as a data type
Traceback (most recent call last):
  File "/home/USER/geonature/external_modules/import/backend/transform/transform.py", line 310, in field_mapping_data_checking
    import_id,
  File "/home/USER/geonature/external_modules/import/backend/wrappers.py", line 9, in wrapper
    res = func(*args, **kw)
  File "/home/USER/geonature/external_modules/import/backend/extract/extract.py", line 54, in extract
    npartitions=npartition,
  File "/home/USER/geonature/backend/venv/lib/python3.7/site-packages/dask/dataframe/io/sql.py", line 123, in read_sql_table
    bytes_per_row = (head.memory_usage(deep=True, index=True)).sum() / 5
  File "/home/USER/geonature/backend/venv/lib/python3.7/site-packages/pandas/core/frame.py", line 2599, in memory_usage
    index=['Index']).append(result)
  File "/home/USER/geonature/backend/venv/lib/python3.7/site-packages/pandas/core/series.py", line 262, in __init__
    raise_cast_failure=True)
  File "/home/USER/geonature/backend/venv/lib/python3.7/site-packages/pandas/core/internals/construction.py", line 642, in sanitize_array
    value, len(index), dtype)
  File "/home/USER/geonature/backend/venv/lib/python3.7/site-packages/pandas/core/dtypes/cast.py", line 1187, in construct_1d_arraylike_from_scalar
    subarr = np.empty(length, dtype=dtype)
TypeError: Cannot interpret '<attribute 'dtype' of 'numpy.generic' objects>' as a data type
{'message': "INTERNAL SERVER ERROR : Erreur pendant le mapping de correspondance - contacter l'administrateur", 'details': "Cannot interpret '<attribute 'dtype' of 'numpy.generic' objects>' as a data type", 'raisedError': 'GeonatureImportApiError'}

La réinstall de 1.17.4 a bien réglé le pb, merci !

J'ai pas encore testé la nouvelle release 1.1.1

**Comment by TheoLechemia** [comment]
C'est Panda qui installe Numpy côté module d'import, et d'autres librairies géographiques côté GeoNature.
J'ai fixé la version de numpy dans le module d'import dans la 1.1.1, ça solutionne le problème

**Comment by JulienCorny** [comment]
oui c'est bon pas de pb dans la 1.1.1
