### ISSUE TITLE
Clarification des contrôles de date

### ISSUE THREAD

**Issue by TheoLechemia** [PnX-SI/gn_module_import#128]
Jusqu'a maintenant, l'utilisation de la librairie panda pour transformer les dates fournies dans le fichier en format "timestamp" était trop permissif.
On pouvait passer des dates à n'importe quel format: (YYYY-MM-DD ou MM-DD-YYYY, avec n’importe-quel séparateur). Ce qui pouvait apparaître comme un fonctionnement souple était en réalité trompeur car en cas de doute sur un mois ou un jour, panda choisissait pour nous
Ex -> Un 11 juillet 2012 écrit 11-07-2012 pouvait être interprété comme un 07 novembre 2012.
J'ai donc définit les formats de date acceptés suivant:
YYYY-MM-DD ou YYYY-MM-DD HH:MM ou YYYY-MM-DD HH:MM:SS . Les séparateurs suivants sont acceptés: "-" "/" ":" " "

**Comment by camillemonchicourt** [comment]
OK c'est plus sur en effet.
Si on ajoute la détection du format inverse (DD-MM-YYYY) peut-être en détectant si la chaîne commence par 2 caractères ou 4 avant le premier séparateur, alors on sera au top. 
Car c'est souvent fourni dans cet autre sens dans l'usage français courant.

**Comment by DonovanMaillard** [comment]
oui, je confirme la remarque de Camille, il faut au moins DD-MM-YYYY ou avec plusiuers séparateurs; 

J'ai souvent aussi des fichiers avec 20180225 sans séparation, mais même si c'est un format relativement récurrent, pas sur qu'il faille l'accepter tel quel.

**Comment by TheoLechemia** [comment]
J'ai rajouté ce format "DD-MM-YYYY". 
Par contre le sans séparateur ne fonctionne pas. Ou alors en compliquant beaucoup le code

**Comment by DonovanMaillard** [comment]
merci ! le sans séparateur demande de toutes facons le même controle entre AAAAMMDD ou DDMMAAAA par une personne. On peut donc le mettre de coté puis on avisera si les formats actuellement disponibles deviennent bloquants

**Comment by camillemonchicourt** [comment]
OK, super, merci.

**Comment by camillemonchicourt** [comment]
Dans la version 2.0, Elie a d'abord voulu utiliser l'outil "dateutil", mais celui-ci ne fonctionnait qu'avec des dates au format américain (mois-jour-annee), donc il est revenu à un fonctionnement plus manuel et similaire à celui mis en place dans la V1 du module Import - https://github.com/PnX-SI/gn_module_import/commit/efd236620660b23bcca5e7b3de66a4e76c77afa2, complété par https://github.com/PnX-SI/gn_module_import/commit/7e3a7ecb4d52c7c7764cb72543f2fe61fcdedeba
