### ISSUE TITLE
Mappings récupérant 2 fois un même champs ?

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/gn_module_import#129]
Sur le serveur démo et avec le mapping par défaut geonature, on récupère 2 fois le champs "permid" pour 'identifiant source" et "identifiant sinp". 

Ca doit fonctionner mais en réalité quand on choisit le mapping, le champs n'est affiché qu'une fois pour l'identifiant source. Le champs identifiant sinp est vide, il ne devrait pas.

**Comment by DonovanMaillard** [comment]
Lié à #148

**Comment by TheoLechemia** [comment]
C'est ok pour les nomeclature mais pas pour les autres champs.
Il faut renommer le champs "source->destination" dans la table sinon on ne peut pas retrouver quel colonne correspond à quel destination.

**Comment by DonovanMaillard** [comment]
Ca marche, merci pour ton retour. C'est pas forcément souhaitable d'avoir un fonctionnement différent selon les champs, ca rend le module très "obscur" dans ce qu'il fait ou peut faire. 

Sans doute un point à améliorer par la suite.

**Comment by TheoLechemia** [comment]
En fait ça fonctionne actuellement. C'est juste dans la preview qu'on ne voit pas apparaître les champs, mais l'insertion en synthese est OK. Je parlais de renommé les champs dynamiquement dans le code (et donc dans la table de transformation), mais pas d'impact sur le modèle. Après, oui, pour celui qui va modifier directement dans la table de transformation, ça peut être perturbant.
Au passage je l'ai fait pour les nomenclature. On a par exemple "occ_naturalite" qui est transformé en "_tranformed_occ_naturalité" pour la transformation des nomenclatures?

**Comment by TheoLechemia** [comment]
J'ai réussi à le faire sans changer le nom des colonnes en base finalement
