### ISSUE TITLE
Vérification des géométries

### ISSUE THREAD

**Issue by TheoLechemia** [PnX-SI/gn_module_import#130]
Conformément au standard, un nouvelle vérification sur les géometrie a été implémentée.
On vérifie que les géométrie fournies sont "valide" d'après les règles de l'OGC. Voir ici pour plus de détail: https://postgis.net/docs/using_postgis_dbmanagement.html#OGC_Validity. Cela concerne principalement les géométries auto intersectées. 
On utilise la fonction postgis https://postgis.net/docs/ST_IsValid.html

**Comment by TheoLechemia** [comment]
La vérification des géométries ne supportait jusqu’à maintenant que le SRID 4326 et 2154. Les limites (xmin, xmax, ymin, ymax) de chacuns de ces SRID étaient écrits en dur dans le code. 
Le mécanisme a été changé pour un mode plus générique. Un paramètre  ``INSTANCE_BOUNDING_BOX`` a été ajouté à la config du module (avec comme valeur par défaut la bounding box de la France métropolitaine - Corse inclu ). On vérifie simplement que les données fournies intersectent bien cette bounding-box. Sinon une erreur est levée
Une vérification visuelle sera ajoutée à l'étape de prévisualisation ou l'utilisateur pourra voir la boundibg box du fichier qu'il vient d'importer.

**Comment by camillemonchicourt** [comment]
En 2022, un paramètre complémentaire `ID_AREA_RESTRICTION` a été intégré : https://github.com/PnX-SI/gn_module_import/issues/217.

Il permet d'exclure les données en dehors d'un zonage du ref_geo.
Pas forcément à vérifier que les coordonnées géographiques sont valides comme prévoyait ce paramètre `INSTANCE_BOUNDING_BOX` ajouté dans ce ticket.

Par la suite ce paramètre `INSTANCE_BOUNDING_BOX` a été retiré (je ne sais plus quand), comme on voit ici : https://github.com/PnX-SI/GeoNature/pull/3344/files.
