### ISSUE TITLE
Visualisation/Création/Modification de mapping: intégration du CRUVED

### ISSUE THREAD

**Issue by TheoLechemia** [PnX-SI/gn_module_import#136]
Actuellement, on ne peut voir que les mappings que l'on a créé soit même. 
L'idée est de pouvoir proposer des mappings pour l'ensemble d'une plateforme ou un groupe d'utilisateur, sans pour autant que tout le monde puisse modifier les mappings des autres.
Il est proposé d'implémenter le CRUVED sur le module et notamment de créer un sous objet du module pour gérer les mapping. 
Pour les personnes n'ayant pas le droit de modifier des mappings, on propose tout de même la possibilité d'adapter "temporairement" un mapping à son fichier. Ce mécanisme n'écrasera pas le mapping source utilisé, en créant un "mapping temporaire" qui sera supprimé à la fin de l'import.
Pour les personnes ayant le droit de modifier un mapping, un message d'alerte sera affiché lorsqu'on modifier un mapping.

**Comment by DonovanMaillard** [comment]
top ! ça viendrait se gérer dans l'admin, comme pour le module export du coup?

**Comment by TheoLechemia** [comment]
Si c'est juste des permissions ce sera depuis l'admin des permissions.

**Comment by DonovanMaillard** [comment]
ok ça marche ! merci

**Comment by camillemonchicourt** [comment]
Pour le fait que des mappings soient partagés, voir https://github.com/PnX-SI/gn_module_import/issues/98
A réfléchir qu'elle est la meilleure solution pour partager des mappings.

**Comment by camillemonchicourt** [comment]
Intégré dans la 1.1.0. Voir la documentation https://github.com/PnX-SI/gn_module_import#droits-du-module
Cependant, tant qu'on n'a pas un R=3, l'étape 2 de mapping des champs n'est pas accessible. 
Elle renvoie un message d'erreur ``[object Object]``, alors que je ne devrais pas voir les mappings de base, mais devrait pouvoir accéder à l'interface et créer un mapping.

**Comment by DonovanMaillard** [comment]
Le R c'est de la simple lecture, en théorie on ne devrait pas dépasser la consultation de l'historique :/
