### ISSUE TITLE
erreur à l'installation de la version 1.0.0 du module d'import

### ISSUE THREAD

**Issue by olivier8064** [PnX-SI/gn_module_import#137]
Bonjour, 

Je viens de faire une installation de zéro de géonature version 2.3.2 tout s'est bien déroulé. 
Tout de suite après, en me loguant avec l'utilisateur geonatureadmin, j'ai suivi la procédure pour installer le module d'import 1.0.0 (https://github.com/PnX-SI/gn_module_import)
Mais j'ai un message d'erreur à la fin avec ce fichier de log ci joint. 
Une idée du problème ? 
Merci 
Olivier
[2020-05-18T20_06_51_757Z-debug.log](https://github.com/PnX-SI/gn_module_import/files/4646442/2020-05-18T20_06_51_757Z-debug.log)

![Screenshot - 18_05_2020 , 22_07_17](https://user-images.githubusercontent.com/7148321/82255509-0eee7580-9955-11ea-81fb-62454c425b2a.png)

**Comment by TheoLechemia** [comment]
Bonjour,
Le module a bien été installé, il s'agit vraisemblablement d'un problème de RAM insuffisante du serveur au moment du rebuild du frontend.
Combien le serveur a-t-il de RAM ?
Petite astuce pour que ça refonctionne (libérer de la RAM pour lancer le build du frontend)

se placer dans le répertoire "frontend" de GeoNature et lancer:

```
sudo supervisorctl stop all 
sudo service postgresql stop
npm run build
```

puis 

```
sudo service postgresql start
sudo supervisorctl restart all

```

**Comment by camillemonchicourt** [comment]
A noter qu'on est en train de faire une grosse révision du module pour sortir une version 1.1.0 : https://github.com/PnX-SI/gn_module_import/blob/develop/docs/CHANGELOG.rst

La version 1.0.0 est une première version fonctionnelle mais à garder pour des tests pour le moment, car on revoit beaucoup de choses dans la 1.1.0.

**Comment by olivier8064** [comment]
Merci Théo et Camille pour ces infos ! 
En effet j'en suis resté au serveur de base de 2 Mo. 
Mais grâce à ta manip Théo, c'est bon , ça fonctionne ! 
Et c'est vraiment génial, j'ai réussi à importer un lot de mes données en quelques clics, comme elles étaient déjà au format SINP, ça aide ;) 
Par contre un fichier csv d'exemple aiderait bien car pour une raison inconnue, la phase de test n'a pas voulu de mon champ UUID, pourtant bien au format UUID..

Petit regret aussi : que l'import ajoute les données dans la synthèse uniquement et pas dans le module occtax. Ce qui ne permet de pas de gérer la donnée il me semble ? (modifier, supprimer). Ou alors je n'ai pas tout compris ce qui est bien possible ;) 
Merci encore :) 

![Screenshot - 19_05_2020 , 21_06_35](https://user-images.githubusercontent.com/7148321/82367988-ee85f000-9a14-11ea-903d-3f1a16d55648.png)

**Comment by camillemonchicourt** [comment]
Bonsoir @olivier8064,
oui le problème que tu as rencontré était lié à GeoNature et pas au module d'Import.
En effet GeoNature arrive à tourner avec 2 Go de RAM, mais en dessous de 4 Go de RAM, il peut rencontrer des soucis au moment de sa recompilation quand on met à jour sa configuration ou qu'on installe un module. 

Concernant le module d'import, on avait fait pas mal de documentation, mais elle n'était encore que dans la branche en développement. Je viens de la pousser dans la branche principale et elle est maintenant affichée directement sur la page d'accueil du module : https://github.com/PnX-SI/gn_module_import#utilisation-du-module-dimports

Super que tu aies pu faire un premier import, surtout qu'on a identifié différents problèmes sur la version 1.0.0 en cours de corrections et d'améliorations.

Concernant l'exemple, justement par défaut il y a un modèle d'import (mapping) correspondant exactement à des données exportées de la synthèse de GeoNature. Cela permet de tester un import facilement avec des données exportées d'une synthèse de GeoNature, sans avoir à refaire les correspondances de tous les champs et de toutes les nomenclatures. Mais ce modèle d'import par défaut a quelques soucis et décalage par rapport aux données exportées de la Synthèse de GeoNature. Cela fait partie des petits soucis identifiés de la 1.0.0.

Concernant la fonctionnement, le module d'Import a clairement vocation a importer des données de partenaires ou des données venant d'autres outils, de les stocker dans leur format brut pour les archiver dans GeoNature et de faire les correspondances pour les copier dans la Synthèse, qui est la partie centrale de GeoNature. Occtax lui, est avant tout un module de saisie de données d'observations occasionnelles (contacts aléatoires et inventaires) qui n'a pas vocation à intégrer toutes les données des partenaires, des autres outils etc...
D'ailleurs quand on importe des données externes dans la Synthèse de GeoNature avec le module d'Import, il est fortement conseillé de créer des jeux de données au préalable pour bien identifier l'origine de ses données dans leurs métadonnées. 

Pour en savoir plus, voir la doc du module : https://github.com/PnX-SI/gn_module_import#utilisation-du-module-dimports

Et à suivre avec la version 1.1.0 du module d'Import.

**Comment by olivier8064** [comment]
Merci Camille pour toutes ces précisions. En effet, c'est mieux avec le tuto ;) Il ne manque plus qu'un fichier csv exemple et ce sera parfait ;) 
Je comprends la logique pour "l'archivage" des données des producteurs mais ce qui est dommage c'est qu'on est plus qu'à un doigt pour les assos ou autres producteurs de données de pouvoir se passer de leurs propres bases de données. 
Même des données anciennes sont "vivantes" comme tu le sais : un contributeur peut s'apercevoir qu'il s'est régulièrement trompé sur une espèce, ou alors le recul de la taxonomie nous fait comprendre qu'il y a des "citations par erreur" etc... D'ailleurs si un producteur modifie tout cela dans sa base et réimporte ensuite le tout dans GeoNature, est ce que la donnée, qui porterait le même UUID est bien "mise à jour" dans la synthèse ? (je dévie un peu par rapport au sujet initial, me dire si je dois reposer cette question ailleurs sur Github... 

Bonne soirée.

**Comment by camillemonchicourt** [comment]
Comme le modèle d'import (mapping) proposé par défaut est celui d'un export Synthèse de GeoNature, le CSV d'exemple est tout simplement un export depuis une Synthèse de GeoNature. 
Les données dans la Synthèse ne sont pas figées, il est possible de faire des ajustements et corrections directement dans la base de données si besoin.

Par contre on peut valider les données présentes dans la Synthèse avec le module Validation.

Si on importe une donnée déjà présente alors il indiquera un doublon.
Si on veut réimporter des données qui ont été modifiées par ailleurs on fait un "Annule et remplace". On les supprime et les réimporte complètement. Ce serait bien plus compliqué de les comparer, vérifier les différences etc...

**Comment by olivier8064** [comment]
Merci Camille pour toutes ces précisions, oui c'est vrai qu'il est toujours possible d'intervenir dans la base. Je vais faire des tests d'export pour essayer de comprendre pourquoi l'import de mon UUID n'a pas fonctionné.
Olivier
