### ISSUE TITLE
Import de fichier d'une seule ligne

### ISSUE THREAD

**Issue by TheoLechemia** [PnX-SI/gn_module_import#143]
Erreur lors de la conversion de de dataframe daks vers dataframe pandas lorsque le fichier ne fais qu'une ligne. 
Pas tout le temps reproduit. A tester

**Comment by TheoLechemia** [comment]
Reproduit avec ce fichier:
[invalid_data (4).zip](https://github.com/PnX-SI/gn_module_import/files/4903004/invalid_data.4.zip)

**Comment by DonovanMaillard** [comment]
Testé avec ton fichier (point hors de métropole) et avec un de mes fichiers, je n'ai pas reproduit, les 2 sont bien importés.

**Comment by camillemonchicourt** [comment]
OK cool car à priori cela n'avait pas été corrigé. 😀

**Comment by DonovanMaillard** [comment]
Peut-être qu'on retmombera dessus mais pour le moment, c'est passé :)
