### ISSUE TITLE
Problème quand un champs source pointe vers plusieurs champs destination

### ISSUE THREAD

**Issue by TheoLechemia** [PnX-SI/gn_module_import#148]
Le code du module ne permet pas actuellement de faire matcher une nomenclature source vers plusieurs nomenclatures de destination.

Cas d'utilisation:

On a un champs "critère" qui contient la valeur suivantes "Mâle chanteur ". Ce critère peut être associés aux nomenclatures suivantes:
**Etat biologique:** Observé vivant
**Sexe**: male
**Comportement**: chamt
etc...
Dans le mapping des champs on met donc le champs "critère" pour l'ensemble des nomenclatures de destination.

**Comment by camillemonchicourt** [comment]
Solution envisagée : Ne pas remplacer le contenu de la colonne source par les valeurs du mapping cible car ça pose des soucis.
Mais la garder telle quelle et ajouter autant de colonne à la table qu'il y a de nomenclatures mappees.

**Comment by camillemonchicourt** [comment]
En cours : https://github.com/PnX-SI/gn_module_import/commit/3a64aa48ab7d6d5217696647442a48d9761a353b

**Comment by camillemonchicourt** [comment]
Fait dans la 1.1.0
