### ISSUE TITLE
Réinstaller ou mettre à jour le module / 1.1.0.rc.2

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/gn_module_import#149]
De grosses évolutions ont été apportées entre la version 1.0.0 et la 1.1.0 en cours de finition.

Pour migrer notre module entre ces 2 versions, j'ai testé 2 méthodes. Désinstaller puis réinstaller la nouvelle version du module. Ou le mettre à jour : 

### DESINSTALLER v1.0.0 / REINSTALLER v1.1.0.rc.2

**1.** Supprimer les 2 schémas de la BDD du module (``gn_imports`` et ``gn_import_archives``)

Attention si vous aviez déjà réalisé des imports avec le module, les données resteront dans la Synthèse, 
mais les données sources qui sont stockées dans des tables spécifiques dans les schémas du module seront donc supprimées.
Cependant il en restera une référence dans la table ``gn_synthese.t_sources`` (à supprimer en cohérence).
Sinon il est possible de sauvegarder les tables des données sources pour les réintégrer ensuite.

```SQL
DROP SCHEMA gn_import_archives CASCADE;
DROP SCHEMA gn_imports CASCADE;
```

**2.** Renommer le dossier ``gn_module_import`` dans ``/home/myuser/`` pour le mettre de côté (``gn_module_import_OLD`` par exemple)

**3.** Supprimer le lien symbolique vers le module import dans ``/home/myuser/geonature/external_modules``

**4.** Si vous avez déjà importé des données dans la Synthèse, vous pouvez éventuellement les supprimer :

```SQL
DELETE FROM gn_synthese.synthese
WHERE id_module = 15; -- Le module IMPORT à l'id 15 dans notre cas. A adapter
```

**5.** Supprimer la ligne du module IMPORTS dans la table ``gn_commons.t_modules``

**6.** Réinstaller le module

Voir https://github.com/PnX-SI/gn_module_import#installation-du-module-dimports

```
wget https://github.com/PnX-SI/gn_module_import/archive/1.1.0.rc.2.zip
[...]
```

**7.** Donner les droits aux groupes souhaités sur l'objet MAPPING.

Admin / Permissions / IMPORT / Objets du module / MAPPING

### METTRE A JOUR EN VERSION 1.1.0.rc2

Exécutez la mise à jour du schéma de BDD du module IMPORT pour appliquer les évolutions de celui-ci entre la version 1.0.0 et la 1.1.0.rc.2 : https://github.com/PnX-SI/gn_module_import/blob/fd258630f6df365ecf3dc7bf4c54c976fb505372/data/migration/1.0.0to1.1.0.sql

```
cd /home/geonatadmin
wget https://github.com/PnX-SI/gn_module_import/archive/1.1.0.rc.2.zip
unzip 1.1.0.rc.2.zip
rm 1.1.0.rc.2.zip
mv gn_module_import gn_module_import_old2
mv gn_module_import-1.1.0.rc.2/ gn_module_import
cp /home/`whoami`/gn_module_import_old2/config/conf_gn_module.toml  /home/`whoami`/gn_module_import/config/conf_gn_module.toml
cd /home/`whoami`/geonature/backend 
source venv/bin/activate
geonature update_module_configuration IMPORT
```

**Comment by DonovanMaillard** [comment]
Petite précision sur ta première méthode : 

L'installation du module ne supprime pas les tables "historiques" de Gil (match geom, match field etc). Ta méthode les supprime donc. S'assurer si, en conséquence, l'installation du module crée bien le schéma gn_imports, puisqu'il pré-existe dans les installations de geonature indépendamment du module.

**Comment by camillemonchicourt** [comment]
Oui l'installation du module crée bien le schéma si il n'existe pas, mais cette méthode n'est pas conseillée notamment car elle supprime tout le schéma qui était préalablement créé par GeoNature et incluait d'autres tables et des fonctions pour l'import niveau 2. Pour l'instant on n'utilise pas ces tables et fonctions, mais pour être cohérent avec les autres GeoNature, si on utilise cette méthode, il faut ensuite re-executer le script SQL de GeoNature complétant le schéma d'import (https://github.com/PnX-SI/GeoNature/blob/master/data/core/imports.sql).

**Comment by DonovanMaillard** [comment]
Méthode 2 intégrée à la doc.
