### ISSUE TITLE
L'installation de 1.1.0.rc.2

### ISSUE THREAD

**Issue by georgemoon** [PnX-SI/gn_module_import#150]
Bonjour,

Je dois installer ce module dans les prochains jours parce que je termine mon stage cette semaine.

Est-ce que c'est une bonne idée d'installer la version 1.1.0.rc.2 plutôt que la version 1.0.0, même si cette version n'est pas encore finalisée ? J'ai vu dans #149 que ce n'est pas nécessairement facile de mettre à jour la version 1.0.0.

Merci d'avance pour votre assistance.

**Comment by DonovanMaillard** [comment]
Bonjour, 

Je dois faire des tests cet après-midi sur la rc2 justement, mais dans tous les cas je pense que je passerais directement sur la RC2. Elle corrige pas mal de bugs et apporte de nouvelles fonctionnalités, même s'"il y a des correctives par la suite ca sera moins compliqué je pense que de partir de la 1.0.0 .

**Comment by georgemoon** [comment]
Ok merci, dans ce cas j'installerai la version 1.1.0.rc.2 demain. Merci !

**Comment by camillemonchicourt** [comment]
De manière générale il faut éviter d'installer une RC en production, ou du moins en prenant en compte les risques.
Cependant dans ce cas, la 1.0.0 avait plusieurs soucis et il y a de grosses évolutions avec la 1.1.0 en préparation.
Et pas mal de tests sur la 1.1.0.rc2.
De notre côté on l'a déployée.

**Comment by georgemoon** [comment]
Oui bien sûr. Normalement j'évite l'utilisation de code que n'est pas en version finale, mais avec l'imminente fin de mon stage je n'ai pas le temps pour attendre la version 1.1.0 officielle. Quand même il est rassurant que vous l'ayez déjà déployée.
