### ISSUE TITLE
Vérification des coordonnées X/Y et bounding box

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/gn_module_import#151]
Sur la version 1.1.0.rc2, j'ai tenté un import avec des données X -Y en lambert 93 (2154). Ces données proviennent d'un autre geonature donc les coordonnées devraient etre bonnes. J'ai vérifié la vue d'expoert, pas d'inversion de X et Y ou autre boulette du genre a priori. 

Lors de l'import, toutes mes lignes sont invalides, aucune bbox n'est calculée. Les logs sont les suivants : 
```
update t_imports from step 3 to step 4
-> t_imports updated from step 3 to step 4
Get valid data for preview
the JSON object must be str, bytes or bytearray, not NoneType
Error while calculate bbox
-> got valid data for preview
```

Coté base, la géomtry semble bien valide mais toutes mes lignes ont le champs "in_bounds" à false.

**Comment by DonovanMaillard** [comment]
Ok soucis trouvé je pense, la bbox fournie par défaut dans la conf n'est pas valide (erreur "Not a homogeneous array"). 

Quand je passe le paramètre "ckeck bounding box" à false, le module continue d'indiquer false dans le champs in_bounds coté base, même sur un nouveau import. Du coup tout est invalide, rien ne rentre. 

Par ailleurs, plutôt qu'une bbox, il me semblerait plus intéressant à termes de stocker dans les paramètres de GeoNature (gn_commons) la geom de l'emprise de l'instance, et intersecter là dessus. 

Ca pourra aussi servir pour d'autres points (textes de statuts à récupérer etc).

**Comment by DonovanMaillard** [comment]
Précision quand même, c'est fonctionnel avec un champs wkt en 4326...

**Comment by DonovanMaillard** [comment]
Après quelques tests, l'intersection des données avec la bbox est fonctionnelle en 4326 (que ca soit un wkt ou un x/y). Ca semble donc n'etre qu'un soucis de projection :)

**Comment by TheoLechemia** [comment]
Ok merci pour les tests

**Comment by TheoLechemia** [comment]
C'est corrigé ici :
https://github.com/PnX-SI/gn_module_import/commit/3b2f0617f8eece5f41a37a0f132f35cf561a064d

C'était un problème d'inconstance du l'ordre des coordonnées X/Y lors du choix des systèmes de projection pour la reprojection des bounding-box fournies par la librairie PyProj: https://proj.org/faq.html#why-is-the-axis-ordering-in-proj-not-consistent
