### ISSUE TITLE
Chargement des modèles de données lors des retours en arrière

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/gn_module_import#152]
Lorsque je prévisualise et que j'ai un soucis (tout est invalide), et ue je reviens à l'étape 2, aucun modèle de données n'est chargé. 

Il faut aller créer un nouveau modèle, manip au cours de laquelle le module récupère bien les modèles existants. 

Toujours sur la 1.1.0.rc2

**Comment by TheoLechemia** [comment]
Je ne reproduit pas ni sur la démo, ni en local. 
Tu peux restester/préciser ?

**Comment by DonovanMaillard** [comment]
Pour les précisions : 

Etape 2 : je choisis un mapping existant
Etape 3 : idem
Etape 4 : je vois une erreur sur toutes mes lignes (testé avec le fameux id digitiser de mémoire). Donc je décide de retourner sur mon étape 2 pour changer le mapping

Quand je reviens à l'étape 2, aucun mapping n'est sélectionné. Et le widget "select" du mapping est vide. 

Je vais tâcher de reproduire et faire une capture vidéo si besoin. En soit rien de très bloquant non plus...

**Comment by TheoLechemia** [comment]
Je n'arrive tjr pas à la reproduire, mais le commit précedent peut résoudre le bug. Il y avait en effet un problème au niveau de la récupération des mappings quand le localstorage était vide (ou on stocke les informations sur l'import entre les étapes de mapping)
