### ISSUE TITLE
Autocomplétion date max si non renseignée  ?

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/gn_module_import#154]
Sur la V1 en principe, quand date max n'était pas rempli, on y intégrait date_min. 

Là sur la 1.1rc2 en tentant un import, je rentre une date max et à la fin, (pas de données invalides), j'ai une erreur serveur "viole la contrainte not null pour le champs date max". 

A ce stade, on a un "import en erreur", qui ne peut plus être corrigé ni terminé, on n'a plus qu'à le supprimer et le recommencer...

**Comment by DonovanMaillard** [comment]
Solution rapide pour le moment si besoin, passer le champs date fin en obligatoire (dans la bib fields, mandatory=true)

**Comment by TheoLechemia** [comment]
Fait sans rendre le champs date_max obligatoire
