### ISSUE TITLE
Ajouter les champs occtax v2 et leur contrôles

### ISSUE THREAD

**Issue by TheoLechemia** [PnX-SI/gn_module_import#163]
TODO:

- [x] Ajout des champs en base
- [x] Contrôles les profondeurs (min_max): https://github.com/PnX-SI/gn_module_import/commit/d7bd07100e42acda7e25c8abe72172c0532c865f
- [x] Ajout du mapping pour le champ "comportement"
- [x] Contrôle du champs cd_hab (présence dans habref): https://github.com/PnX-SI/gn_module_import/commit/5d4fd318059ee1c53e74723126a76e8ddbaebc7d

**Comment by jpanijel** [comment]
Théo, comment comptes-tu gérer les champs V2 suivants ?

1.  deeFloutage (indique si un floutage a été effectué pour l'import dans la plateforme. Cela ne concerne que les données d'origine privées qui seraient plus précises chez le producteur)
2. diffusionNiveauPrecision (niveau maximal de précision à la diffusion souhaité par le producteur pour les données d'origine privées fournies plus précises)

**Comment by TheoLechemia** [comment]
Donovan a fait une 1ere passe des champs ajouté dans occtaxv2.
Je vais compléter avec ces champs. Ce sont les seuls que tu avais identifier comme manquant ?
C'est assez simple, il suffit de remplir la table "dict_fields" en base et la requête d'insertion dans la synthèse ainsi que l'interface de mapping sont auto-générés.

**Comment by jpanijel** [comment]
Pour que l'UMS puisse s'assurer et juger si l'implémentation du standard V2 convient dans le cadre du projet GINCO-DEPOBIO, pourrais-tu me transmettre une vue de la table dic_fields ? Il faudrait par ailleurs que l'on sache précisément quels champs du standard sont remontés dans les MTD et ceux qui sont stockés peut-être ailleurs comme le  champs orgTransformation (le nom de la plateforme) ?

**Comment by TheoLechemia** [comment]
Dans un 1er temps voilà le contenu de la table dict_field:
[contenu_dict_fields.zip](https://github.com/PnX-SI/gn_module_import/files/5341203/contenu_dict_fields.zip)
Je prépare une correspondance avec tous les champs, y compris hors synthese

**Comment by camillemonchicourt** [comment]
Le contenu de la table est détaillé dans le SQL de création du module : https://github.com/PnX-SI/gn_module_import/blob/develop/data/data.sql#L75

**Comment by jpanijel** [comment]
Voici la compilation de la conformité du module d'import avec les champs du Standard DEE V2 ainsi que la liste des champs à afficher dans le module d'imports GINCO
[Conformite_DEE_V2.xlsx](https://github.com/PnX-SI/gn_module_import/files/5346255/Conformite_DEE_V2.xlsx)

**Comment by camillemonchicourt** [comment]
Fait dans la 1.1.0
