### ISSUE TITLE
Ajouter un champs id_field sur t_mappings_value

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/gn_module_import#164]
Actuellement la table qui stocke les correspondances de valeur stocke uniquement : 
- un id de la ligne (id_match_values)
- un id_mapping
- une valeur source
- l'id de la valeur cible

Du coup si j'ai un mapping avec Sexe : inconnu et Stade : inconnu, ma table t_mappings value va stocker : 
1 - 1 - Inconnu - id1
2 - 1 - Inconnu - id2

Coté BDD on ne sait pas quelle ligne correspond à quel champs ni quelle nomenclature. Ca fonctionne pour le module mais n'est pas très simple à mettre à jour par exemple !

Il serait bien de pouvoir stocker un id_field en plus, de manière à savoir que "tel mapping, pour tel champs, a l'ensemble des correspondances source->cible". 

Par exemple dans notre cas, ca permettrait de facilement supprimer les mappings de valeur qui correspondent aux anciennes techniques d'observation, qui ont disparu. (Pour cette fois il va falloir chercher les ID qui ne correspondent à rien et virer les lignes je pense)

**Comment by DonovanMaillard** [comment]
Merci pour ton retour. J'ai du mal à voir coté base où est la redondance et de quelle manière on peut retrouver une quelconque jointure ?  J'ai même du mal à comprendre comment le module retrouve ses petits quand il a 2 lignes : 

- Mapping 1, valeur "inconnue" doit prendre l'id_nomenclature '50' 
- Mapping 1, valeur "inconnue" doit prendre l'id_nomenclature '64'

C'est pas un besoin hyper prioritaire et là aussi c'est une proposition qui date un peu. mais du coup coté BDD je trouve le stockage assez peu clair, il faut aller chercher l'id_nomenclature pour voir à quel type ca correspond et donc à quel champs on doit le rattacher

**Comment by camillemonchicourt** [comment]
J'ai pas tout compris, mais fait dans la 2.0.0 avec la possibilité d'avoir plusieurs valeurs sources correspondant à une même nomenclature, comme ici où les valeurs vides et "Ne sait pas" sont tous 2 associées à NSP :

![image](https://user-images.githubusercontent.com/4418840/200688405-9be7d1d0-62e9-43cb-89a4-93e3f398967c.png)

Voir aussi le nouveau modèle de données : 

![geonature2db_demo - gn_imports](https://user-images.githubusercontent.com/4418840/200685214-b0bcf9f5-09f6-43c0-8e92-c5f7c46ecf95.png)
