### ISSUE TITLE
Alimenter le champ additionnel jsonb de la synthèse avec plusieurs champs

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/gn_module_import#165]
A réfléchir à terme, 

Il serait bien qu'on puisse, dans l'étape 2, avoir un widget multiselect pour récupérer plusieurs champs source, qui seront poussés au format jsonb dans le champs dédié de la synthèse. Ca permettrait de faciliter l'accès à ces données facultatives.

**Comment by camillemonchicourt** [comment]
Régression non implémentée dans la 2.0.0.
Voir la PR d'intégration dans la 1.2.0 - https://github.com/PnX-SI/gn_module_import/pull/241

**Comment by bouttier** [comment]
Par rapport à ce qui avait été fait dans la 1.2.0, on aimerait :
- Supporter l’import d’une colonne qui contient déjà du JSON (par exemple pour importer un fichier exporté d’une autre instance GeoNature contenant déjà des champs additionnels) (les colonnes sélectionnées seraient alors mergé avec le JSON pré-existant)
- Peut-être pouvoir renommer les colonnes dans le JSON additionnel plutôt que d’utiliser le nom des colonnes CSV. Cela est potentiellement utile pour des données semi-normées.

**Comment by camillemonchicourt** [comment]
Selon moi, les données additionnelles dans la Synthèse ne sont pas vraiment normées, standardisées ou protocolées. 
Ça serait le cas si on importait dans Occtax sur des JDD avec des champs additionnels prédéfinis, ou sur Monitoring avec un protocole et des champs bien identifiés.

Mais pour les imports dans la Synthèse, à ma connaissance, les champs additionnels permettent uniquement de ne pas perdre des infos additionnels présentes dans le fichier source importé, mais ne correspondant à aucun champs du standard Occurrences de taxons.
Donc, pour moi, le fait de pouvoir renommer les colonnes sources que l'on agrège dans les champs additionnels de la Synthèse est un petit plus, mais n'est pas essentiel et peu utile, surtout si cela complique les choses techniquement et fonctionnellement.

**Comment by DonovanMaillard** [comment]
Oui comme Camille, l'idée dans la 1.2 et l'idée que je souhaiterais conserver, c'est de pouvoir rendre disponible en synthèse des champs divers et variés, propre à chaque imports, qui ne sont pas présents dans le standard. Renommer le champs me semble compliqué, au pire il suffit de renommer la ou les colonnes en question dans le fichier csv. 

De même, le but du module est qund meme de permettre des imports à des gens qui ne maitrisent pas la manipulation des données, donc sélectionner plusieurs champs est bien plus simple et pertinent à mon sens que de devoir construire un json en amont

**Comment by gildeluermoz** [comment]
Je confirme.
L'import de plusieurs champs de la source vers le champ additionnal data tel qu'implémenté dans la version 1.2.0 est très utile et utilisé. La fonctionnalité était simple et intuitive. L'utilisateur comprend vite le lien entre le nom de la colonne et le nom de la clé dans le json. Et ceux qui importent finissent par bien comprendre comment et pourquoi il faut bien préparer son fichier source en amont.
Cette fonctionnalité permet notamment, comme le dit Donovan, à des personnes peu familières avec les langages et les formats, d'importer facilement des données comportant des champs qu'ils souhaitent conserver et qui ne sont pas présents dans le standard SINP. 
L'import dans monitoring n'étant pas à la portée d'un utilisateur non développeur, des données historiques conservées ou archivées à plat dans des tableurs peuvent ainsi être bancarisées dans la synthèse. Avec, pourquoi pas, à terme , l'idée de rejoindre monitoring.

**Comment by bouttier** [comment]
Je me suis mal exprimé, ce dont j’ai parlé sont bien des fonctionnalités **en plus** de la création du JSON à partir de colonnes du CSV comme présent en 1.2.0.

**Comment by camillemonchicourt** [comment]
Oui oui, c'est bien clair pour moi que c'est en plus.

**Comment by DonovanMaillard** [comment]
Désolé j'ai mal compris :) Pouvoir intégrer un champs déjà en json alors, pourquoi pas. Changer les noms des clés, si tu as une manière de faire simple pourquoi pas mais j'avoue que ca me semble complexifier un peu la création du mapping. A voir :)

**Comment by gildeluermoz** [comment]
> Je me suis mal exprimé, ce dont j’ai parlé sont bien des fonctionnalités **en plus** de la création du JSON à partir de colonnes du CSV comme présent en 1.2.0.

Oui j'avais bien compris ça

> Supporter l’import d’une colonne qui contient déjà du JSON (par exemple pour importer un fichier exporté d’une autre instance GeoNature contenant déjà des champs additionnels) (les colonnes sélectionnées seraient alors mergé avec le JSON pré-existant)`

Oui intéressant dans le cas que tu cites. Ce serait luxe.

> Peut-être pouvoir renommer les colonnes dans le JSON additionnel plutôt que d’utiliser le nom des colonnes CSV. Cela est potentiellement utile pour des données semi-normées.

Sur ce point, de mon point de vue et si j'ai aussi compris celui de Camille, c'est de dire que oui pourquoi pas si ce n'est pas trop chronophage, ou comme le dit Donovan, pas trop complexe à comprendre dans l'interface. L'idée est de dire que le fonctionnemnent en 1.2.0 est tout à fait satisfaisant et qu'il ne faudrait pas que cette amélioration soit trop "couteuse" à faire.

**Comment by Pierre-Narcisi** [comment]
J'ai fait une implémentation des champs additionnel dans l'Import sur cette PR: https://github.com/PnX-SI/gn_module_import/pull/462

Pour gérer le fait d'importer plusieurs champs ou un seul champ json, je créé un objet json, et je détecte si un des champs renseigné est du Json, si c'est du json je le merge a l'objet, sinon j'ajoute l'objet, clé à l'objet.
