### ISSUE TITLE
Permettre l'édition des imports en erreur

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/gn_module_import#167]
Actuellement les imports 'en erreur' sont totalement bloqués et on ne peut que les supprimer. 

A terme, il serait bien de pouvoir aller corriger les erreurs en question plutôt que de les reprendre à zéro.

**Comment by bouttier** [comment]
En v2, les imports ne passent jamais « en erreur ». Au pire on a un message d’erreur lorsqu’on fait suivant, mais on peut réessayer. Un import peut être repris à n’importe quelle étape, y compris après la fin de l’import (mais ne peut plus être modifié après la clôture du JDD associé).

**Comment by DonovanMaillard** [comment]
Parfait ! Merci à toi

**Comment by camillemonchicourt** [comment]
Fait dans la 2.0.0
