### ISSUE TITLE
Pouvoir télécharger les données invalides une fois l'import terminé

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/gn_module_import#169]
Le téléchargement des données invalides d'un import sont proposées lors de l'étape de prévisualisation. Avant l'export de ces données restait possible après l'import, aujourdhui le bouton n'est plus affiché (au moins pas par défaut?)

L'idéal serait de pouvoir exporter les données invalides soit depuis le rapport d'erreur, soit via un picto directement dans le tableau de la page d'accueil du module

**Comment by camillemonchicourt** [comment]
C'était pas volontaire mais une erreur dans le code qui masquait ce bouton dans la liste des imports.
Corrigé ici : https://github.com/PnX-SI/gn_module_import/commit/318155946de1cc43125093e1b11f9face7b9168f

**Comment by DonovanMaillard** [comment]
Super, merci !
