### ISSUE TITLE
Pouvoir désactiver le controle DEE Flou sur les jdd privés

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/gn_module_import#171]
Le module exige que la nomenclature DEE FLOU soit renseignée si on est sur des données privées. 

Ce controle doit pouvoir se désactiver. On peut ne pas avoir l'info dans le fichier source et vouloir appliquer la valeur par défaut, au niveau régional on a souvent l'info oralement ou par mail sans avoir de champs dédiés.

**Comment by jpanijel** [comment]
Oui dans DEPOBIO, il est aussi très probable que l'information ne soit pas remontée par les plateformes SINP ou les producteurs et qu'elle ne soit donc pas non plus connue des Bureaux d'études au moment du dépôt.

**Comment by camillemonchicourt** [comment]
OK dans ce cas je propose de complètement supprimer ce contrôle qui alourdit et complique les choses.

**Comment by camillemonchicourt** [comment]
Vu avec @TheoLechemia, il va ajouter un paramètre par contrôle pour pouvoir les désactiver si besoin.

**Comment by DonovanMaillard** [comment]
Super, merci à vous ! 

Mais du coup, est-ce que ce contrôle va servir à quelqu'un? S'il ne peut pas être utilisé sur les outils SINP et le dépobio... sera-t-il utilisé par d'autres ?

**Comment by camillemonchicourt** [comment]
Oui pour ce contrôle en particulier, peut se poser la question de le virer complètement si personne ne l'utilise.
