### ISSUE TITLE
Import dans un JDD - Vérifier CRUVED

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/gn_module_import#175]
Actuellement la liste des JDD dans lequel je peux importer est basée sur le CRUVED.
Mais si je vais importer directement dans un JDD (depuis le module Métadonnées par exemple) alors je peux importer dans un JDD dont je n'ai pas forcément les droits.
Vérifier le CRUVED en plus de filtrer la liste des JDD.

**Comment by camillemonchicourt** [comment]
Pour le moment, je supprimerai la possibilité de pouvoir importer dans un JDD directement depuis le module MTD. 
Il n'est pas fait correctement en terme de vérification edes droits, et un utilisateur peut ainsi importer dans un JDD dont il n'a pas les droits, simplement car il le voir dans la liste des JDD du MTD.
Et car cela entraine des moyens d'accès au module différent, en arrivant sur des étapes différentes, donc brouille plus les pistes qu'autre chose selon moi.

**Comment by DonovanMaillard** [comment]
C'est annexe mais se pose la question, quand même, de voir les JDD sur lesquels on a pas les droits dans le module MTD.

**Comment by camillemonchicourt** [comment]
En effet c'est un autre sujet lié au module Métadonnées et c'est déjà géré par le CRUVED.

**Comment by jpanijel** [comment]
Pour information, Alain va prendre en charge ce ticket pour régler la prise en compte du CRUVED.

**Comment by camillemonchicourt** [comment]
Corrigé dans la v2 du module.
