### ISSUE TITLE
Ajout de contrôles

### ISSUE THREAD

**Issue by TheoLechemia** [PnX-SI/gn_module_import#176]
- Vérification sur le champs "type_info_geo": Lever une erreur si une entité de rattachement est fournie est que le champs est à "Georeférencement". Inversement si un WKT est fourni et que le champs est à "rattachement"
- Si une ligne a un UUID regroupement, les champs "methodeRegroupement" et "TypeRegroupement" sont obligatoires et si "methodeRegroupement" ou "TypeRegroupement" sont rempli alors idSINPRegroupement doit être fourni.

**Comment by camillemonchicourt** [comment]
Oui pour le premier, mais pas le deuxième qui est trop contraignant. On peut avoir l'un sans l'autre.

**Comment by jpanijel** [comment]
Ajout des contrôles TypeInfoGeo 
Si sur une même ligne de fichier d'import le champ Géométrie est associé à une entité de rattachement, Et TypeInfoGeo=1 > la ligne est invalide, Les rattachements ne doivent pas être fournis ; ils sont calculés par la plateforme.

Si sur une même ligne de fichier d'import le champ Géométrie est associé à une entité de rattachement, Et TypeInfoGeo='' > la ligne est invalide il faut que le producteur remplisse le champ; Lorsqu'une entité géo-administrative est fournie avec une géométrie (localisation approximative), le champ TypeInfoGeo est obligatoire.

**Comment by TheoLechemia** [comment]
Les 3 contrôles suivants on été ajoutés:
- si type_info_geo = georeferenceent alors aucun rattachement ne doit être fourni
-  Si une entitié de rattachement est fourni alors le type_info_geo ne doit pas être null
-  Erreur si type_info_geo = Rattachement et que WKT ou x/y not null

Les trois contrôles sont désactivables via le paramètre: `CHECK_TYPE_INFO_GEO`

**Comment by camillemonchicourt** [comment]
OK à ajouter dans la documentation listant les contrôles du coup. Merci.

**Comment by jpanijel** [comment]
Problème avec la règle > Erreur si type_info_geo = Rattachement et que WKT ou x/y not null 
>  si type_info_geo = 2 et qu'il y a un objet géométrique, cela ne doit pas nécessairement provoquer une erreur. L’annexe 5.6 sur les principes et cas d’usages pour le géoréférencement des données accepte les cas suivants.

**Illustration de la règle**
- Si une observation a été réalisée sur une commune, sans plus de précision, mais est localisée au centroïde de la commune, alors l’objet géographique du centroïde peut être fourni avec la mention TypeInfoGeo=2 ; la localisation de l’observation est alors géo-référencée à la commune.
- [J'ai aussi ajouté] Si une observation doit se référer à plusieurs objets d’une même entité géo-administratives, un objet géographique peut être utilisé ; celui-ci doit alors être associé à l’information typeInfogeo=2.

**Comment by TheoLechemia** [comment]
Il y a aussi cette contrainte:
Si type_info_geo = rattachement, alors au moins une entité de rattachement doit être fourni ? 
Il y a une contrainte là dessus dans la synthese, du coup l'insertion de marche pas dans ce cas là, car la ligne n'est pas en erreur, mais ne rentre pas dans la synthese

**Comment by jpanijel** [comment]
C'est le bazar, en fait, la note sur les principes et cas d’usages pour le géoréférencement est obsolètes. 
La règle serait donc : 
Erreur si type_info_geo = Rattachement (2) et que WKT ou x/y not null **ou entite de rattachement non fourni**

**Comment by camillemonchicourt** [comment]
OK dans la 1.1.1 ? Et doc listant les contrôles mise à jour ?

**Comment by TheoLechemia** [comment]
Du coup actuelement il y a ces deux contrôles (désactivables):
- Si une entitié de rattachement est fourni alors le type_info_geo ne doit pas être null
- Si  type_info_geo = 1 (Géoréférencement) alors aucun rattachement ne doit être fourni

@jpanijel tu confirmes que tu DEPOBIO on ne met pas le 2eme ?

**Comment by jpanijel** [comment]
Non les règles devraient être identiques partout.  
- Si type_info_geo = 1 (Géoréférencement) alors NatureObjetGeo ne doit pas être null ou NSP.
- Si type_info_geo = 1 (Géoréférencement) + rattachement > ERROR car un rattachement ne peut correspondre à une localisation précise. J'ai cru comprendre qu'il s'agit d'une contrainte forte dans GeoN mais qui est incohérente avec la notion SINP de Géoréférencement; une commune devrait pouvoir être saisie comme un géoréférencement lorsque c'est l'unique information de localisation dont on dispose.
-> A l'heure actuelle je préconise donc pour ce dernier cas de mettre GEOM + type_info_geo = 1  + NatureObjetGeo = Stationnel, mais en réalité il faudrait mettre GEOM + type_info_geo = 2  + NatureObjetGeo = Stationnel

Je suis consciente que cela n'incite pas à remplir type_info_geo puisque c'est plus contraignant et que toutes ces règles sont très compliquées à comprendre.

**Comment by TheoLechemia** [comment]
Ok. 
Actuellement il n'y a pas de vérification avec le champs "NatureObjetGeo", donc à reprendre, améliorer.
Mais en l'état actuel, mais question était de savoir si ou active ou non le contrôle  (sur l'ensemble des instances):
- Si type_info_geo = 1 (Géoréférencement) alors aucun rattachement ne doit être fourni

**Comment by jpanijel** [comment]
oui on peut activer ce contrôle sur l'ensemble des instances

**Comment by bouttier** [comment]
À suivre dans #271
