### ISSUE TITLE
Pouvoir définir les nomenclatures par défaut d'un import si non présent dans la source

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/gn_module_import#178]
En lien avec #176 notamment, 

Il peut arriver que les nomenclatures d'un fichier soient des constantes et par conséquent pas renseignées dans la source (par exemple si toute les lignes sont rattachées à la commune, ou si tous les regroupements sont des relevés). 

Une amélioration à terme serait de pouvoir dire "je n'ai pas de champs source lié à telle nomenclature, mais je peux quand même à l'étape 2 définir la nomenclature par défaut qui convient".

**Comment by camillemonchicourt** [comment]
Oui je pensai qu'il y avait déjà un ticket sur le sujet mais peut-être pas.

Se pose aussi la question si on a une colonne de nomenclature des renseignée mais avec des valeurs vides pour certaines lignes.
On leur affecte alors la valeur par défaut définie dans la BDD. 
Mais on peut vouloir forcer une valeur précise pour les lignes où la nomenclature est nulle.

**Comment by DonovanMaillard** [comment]
En effet, doublon avec #68 ... au temps pour moi
