### ISSUE TITLE
Ajout du nombre de données importées dans la liste des imports

### ISSUE THREAD

**Issue by Adrien-Pajot** [PnX-SI/gn_module_import#183]
En testant le module d'import, certains fichiers comportaient des erreurs et cela pourrait être intéressant de voir ce que cela implique. 

Par exemple quand on regarde la liste, voir le nombre de données qui ont été importées sur le nombre total de données avec la possibilité de supprimer le message d'erreur si ça nous convient. 
(Par exemple j'avais qu'une ligne en erreur, ligne qui finalement ne m'intéresserait pas donc le fichier importé est finalement bon). 

Ceci permettrait notamment de distinguer les erreurs en bout d'import sur une partie ou la totalité des lignes par rapport à celles au début de l'import (encodage) et de prioriser les corrections d'imports.

**Comment by DonovanMaillard** [comment]
Après échanges avec Maxime, on propose l'affichage d'une colonne valide/total dans le tableau des imports : 1200/1235 par exemple. 

Et à coté de ça, on se demande pour le cas où on souhaite ignorer les erreurs restantes, si on ne mettrait pas en place un système pour "archiver" l'import, c'est à dire qu'on ne change rien sauf qu'on n'affiche plus le triangle rouge devant les erreurs pour ne plus attirer l'attention sur ces lignes là.

**Comment by Adrien-Pajot** [comment]
> Après échanges avec Maxime, on propose l'affichage d'une colonne valide/total dans le tableau des imports : 1200/1235 par exemple.

Oui c'était exactement l'objet du ticket : 
> voir le nombre de données qui ont été importées sur le nombre total de données avec la possibilité de supprimer le message d'erreur si ça nous convient.

**Comment by DonovanMaillard** [comment]
c'est sur ça qu'il faut qu'on réfléchisse encore un peu... "fermer" un import, le rendre "inactif", c'est un fonctionnement connu au niveau du JDD et qu'on peut calquer.

Malgré tout il faut veiller à la remarque de jpanijel sur le fait de ne pas accentuer une confusion entre import et dataset en termes d'expérience utilisateur, et dans le cas des imports ça a moins de sens pour le moment car un import est figé/inactif dès lors qu'il est terminé.

Si cette fonctionnalité sert uniquement à retirer ce triangle rouge, on peut imaginer un booléen "ignorer les erreurs". Une proposition de ton coté ?

**Comment by mvergez** [comment]
Bonjour,

Pour ce qui est de l'affichage des données importées et des données totales dans le tableau, j'ai ajouté une colonne "Données totales" et changé la colonne existante par "Données importées". Comme le montre la capture suivante : 
![exemple_import_list](https://user-images.githubusercontent.com/85738261/130101689-8d192bd2-6bb1-4d41-b4fc-1e9576a3e91e.png)

Il est plus simple d'ajouter une colonne plutôt que de personnaliser une colonne existante avec 2 sources de données. Cela rendra cette fonctionnalité plus facilement intégrable dans la branche [refactor](https://github.com/PnX-SI/gn_module_import/tree/refactor).

**Comment by DonovanMaillard** [comment]
Fait dans la version 1.2.0
