### ISSUE TITLE
Support de l'encodage "Latin3" (et autre)

### ISSUE THREAD

**Issue by TheoLechemia** [PnX-SI/gn_module_import#188]
La plupart des fichiers fournis sur DEPOBIO sont enregistrés depuis Excel sous Windows... qui encode en Latin3.
Ajouter le support de plusieurs autres encodages courants.

**Comment by camillemonchicourt** [comment]
Il faudrait que l'utilisateur renseigne l'encodage de son fichier où il pourrait être détecté automatiquement ?

**Comment by TheoLechemia** [comment]
Oui comme c'est le cas actuellement, mais on ne propose que UTF8.
mais goodtable propose l'encodage détecté du fichier, avec un estimation de certitude en %. Il faudrait tester à quel point c'est fiable

**Comment by camillemonchicourt** [comment]
Oui idéalement calculer automatiquement l'encodage (le plus probable), le selectionner mais laisser à l'utilisateur la possibilité de le modifier.

**Comment by DonovanMaillard** [comment]
@camillemonchicourt cette fonctionnalité est toujours prévue pour Ginco ?

Fonctionne avec tous les encodages courants, pas uniquement UTF et Latin ?

**Comment by camillemonchicourt** [comment]
Oui c'est ce sur quoi a travaillé @bouttier.
C'est fonctionnel, et détecte automatiquement l'encodage du fichier.
Mais il en a profité pour faire une reprise bien plus globale du module, notamment pour y mettre en place des tests automatisés.
Travail de reprise assez profond en cours donc, incluant cette évolution fonctionnelle.

**Comment by DonovanMaillard** [comment]
Super merci, 

A voir pour faire un point plus global avec Elie alors et ne pas se téléscoper dans les évolutions et corrections qu'on demande actuellement à Natural via le projet https://github.com/PnX-SI/gn_module_import/projects/1

**Comment by TheoLechemia** [comment]
Oui et même coordonner le calendrier avec le travail d'Elie je pense

**Comment by camillemonchicourt** [comment]
Détection automatique de l'encodage du fichier source développée dans la 2.0.0
