### ISSUE TITLE
Revenir sur des fichiers en erreur - Pouvoir de nouveau exporter les lignes d'erreur

### ISSUE THREAD

**Issue by Adrien-Pajot** [PnX-SI/gn_module_import#190]
En revenant sur les fichiers importés en erreur, je pense qu'il pourrait être intéressant de réexporter les lignes en erreur, surtout quand il y en a beaucoup.

**Comment by Adrien-Pajot** [comment]
A lier avec la #191

**Comment by camillemonchicourt** [comment]
A priori même chose que https://github.com/PnX-SI/gn_module_import/issues/169 ? Corrigé dans la Develop.

**Comment by Adrien-Pajot** [comment]
Au temps pour moi, j'avais cherché mais pas vu dans le titre pourtant explicite.
