### ISSUE TITLE
Erreur WKT

### ISSUE THREAD

**Issue by TheoLechemia** [PnX-SI/gn_module_import#192]
File "/home/geonatadmin/geonature/external_modules/import/backend/transform/check_geography.py", line 40, in check_bounds_x_y
    cur_wkt = Point(float(x), float(y))
ValueError: ("could not convert string to float: '6.486.51'", 'occurred at index 4')
{'message': "INTERNAL SERVER ERROR : Erreur pendant le mapping de correspondance - contacter l'administrateur", 'details': '("could not convert string to float: \'6.486.51\'", \'occurred at index 4\')', 'raisedError': 'GeonatureImportApiError'}

Lève une erreur 500, devrait simplement renvoyer l'erreur dans le rapport

**Comment by DonovanMaillard** [comment]
Ce ticket est assigné à Théo, est-ce que je le fais faire par NS ou est-ce que c'est déjà fait/en cours?

**Comment by bouttier** [comment]
Je me l’assigne !

**Comment by DonovanMaillard** [comment]
Ok, je le retire du projet NS
