### ISSUE TITLE
Changer le type et le controle sur "ref biblio"

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/gn_module_import#196]
Actuellement avec un type varchar255 dans la synthèse, les références biblio devraient plutôt être en textes.J'ai quelques milliers de données qui ne passent pas actuellement à cause de ce type ;)

Il y a une PR en cours sur GeoNature sur ce point pour mettre à jour la synthèse.

**Comment by camillemonchicourt** [comment]
OK dans la 2.6.0 de GeoNature, on a finalement basculé ce champs de 255 à 5000 caractères, plutôt que le passer en type "text" pour limiter les conséquences.
Du coup je pense que c'est OK avec la 1.1.1 du module Import ?

**Comment by DonovanMaillard** [comment]
Je vais tester rapidement, je ne sais pas s'il y avait quelque chose de plus à faire au niveau du backend pour les contrôles. Je te fais un retour rapide :)

**Comment by DonovanMaillard** [comment]
Il y a au moins le dict_field à corriger, le champs ref_biblio est resté de type varchar 255 ;)
