### ISSUE TITLE
Vérification des URL dans le champ digital_proof

### ISSUE THREAD

**Issue by xavyeah39** [PnX-SI/gn_module_import#197]
Salut !
Lors d'un import j'ai une erreur de levée dans le rapport sur le champ `digtal_proof` indiquant que le format des URL n'est pas correct. Portant les lignes qui sont en causes ont bien des URL conforme (commençant par (http:// ou https://).
Un soucis sur le contrôle de la chaîne de caractères ?
Merci,

![image](https://user-images.githubusercontent.com/16793813/105019829-d7394f80-5a46-11eb-80de-4b931dad8127.png)

**Comment by TheoLechemia** [comment]
L'erreur est provoquée par des lignes contenant des URL séparés par des virgules.
L'expression régulière ne supporte qu'une seule URL.
