### ISSUE TITLE
Goodtables 

### ISSUE THREAD

**Issue by orovellotti** [PnX-SI/gn_module_import#2]
Est ce que vous avez regarder ca ?

"Goodtables is a framework to validate tabular data. It can check the structure of your data (e.g. all rows have the same number of columns), and its contents (e.g. all dates are valid)."

https://github.com/frictionlessdata/goodtables-py

**Comment by camillemonchicourt** [comment]
Est-ce qu'il faut que @JulienCorny analyse son utilisation potentielle dans le projet ?

**Comment by JulienCorny** [comment]
Bonjour,
Effectivement goodtables pourrait être pas mal je pense pour des vérifications de base des csv et json, il y a pas mal de choses toutes faites, ça a l'air vraiment bien. On éviterait de recoder quelques vérif de base : format, absence de noms de colonnes, doublons de noms de colonnes, ...

**Comment by camillemonchicourt** [comment]
OK donc goodtables sera bien utilisé dans le module pour faire diverses vérifications des fichiers importés : https://github.com/PnX-SI/gn_module_import/compare/ec89770ce6...22bc23adff
