### ISSUE TITLE
Correspondance import source

### ISSUE THREAD

**Issue by vprunet** [PnX-SI/gn_module_import#201]
je n’ai pas vu de référence vers la table gn_synthese.t_sources dans les tables du schema gn_imports.

Faut-il parser le champ name_source de t_sources pour retrouver l’import correspondant?
Quid d’ajouter une colonne id_source dans la table t_imports?

**Comment by camillemonchicourt** [comment]
En effet voir le MCD dans la doc : https://github.com/PnX-SI/gn_module_import#utilisation-du-module-dimports
Je n'ai plus tout en tête mais ajouter un champs ``id_source`` dans la table ``gn_imports.t_imports`` pourrait être utile.
@DonovanMaillard ?

**Comment by DonovanMaillard** [comment]
Bonjour, 

En effet, pas de référence direcgtement, il n'y a que l'id_import dans le nom de la source. 

En effet, ajouter un id_source_synthese dans la table t_imports pourrait être intéressant pour faire le lien plus efficacement :)

**Comment by DonovanMaillard** [comment]
Je l'intègre aux évolutions qu'on demande à Natural Solutions ces prochaines semaines

**Comment by DonovanMaillard** [comment]
Sera mis en place dans la release 1.2 à venir

**Comment by DonovanMaillard** [comment]
Fait dans la version 1.2.0
