### ISSUE TITLE
Les champs _tr_nomenclature sont affichés dans le mapping de champs

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/gn_module_import#202]
Si on fait un mapping, on se rend compte d'une erreur et on revient en arrière, les champs _tr_nomenclature créés deviennent visibles pour l'utilisateur. S'il les sélectionne ça risque pas de poser soucis ? 

Dans tous les cas ça vaudrait le coup de les masquer sur l'étape 1 pour ne pas perdre l'utilisateur et qu'il n'ait pas à considérer ces champs.

**Comment by DonovanMaillard** [comment]
en cous par Elie

**Comment by camillemonchicourt** [comment]
Dans la version 2.0.0, on n'a plus l'ajout de ces champs dans la BDD pendant le processus d'import, notamment pour éviter ce soucis.
