### ISSUE TITLE
erreur affichage de l'historique de 1.0.0 à 1.1.0

### ISSUE THREAD

**Issue by JulienCorny** [PnX-SI/gn_module_import#203]
Salut !

Dans le cadre d'une MAJ de GeoNature de 2.4.1 vers 2.5.5, j'ai mis à jour le module d'import de 1.0.0 vers 1.1.0. 

Ce qui m'a retourné une petite erreur à l'accueil du module pour l'affichage de l'historique :
{'message': "INTERNAL SERVER ERROR - affichage de l'historique : contactez l'administrateur du site", 'details': "'dataset'", 'raisedError': 'GeonatureImportApiError'}

liée à import_as_dict qui n'a pas de clé 'dataset'. 

J'ai ajouté (dans models.py) : 
if "dataset" in import_as_dict:
    import_as_dict["dataset_name"] = import_as_dict["dataset"]["dataset_name"]
    import_as_dict.pop("dataset")

pour résoudre l'erreur temporairement et pouvoir afficher l'historique. 

J'ai peut-être loupé un truc lors de toutes les mises à jour, mais en tout cas j'avais exécuté les 2 scripts sql de maj du module de 1.0.0 vers 1.1.0

**Comment by camillemonchicourt** [comment]
A priori corrigé avec la 1.1.1 ?

**Comment by DonovanMaillard** [comment]
Je me demande si je n'avais pas eu (et oublié) ce soucis... et de mémoire, je me demande si modifier simplement la config du tableau d'historique pour m'alligner sur le nouveau nom n'avais pas suffit. A creuser ...
