### ISSUE TITLE
Erreur (dépendances?) lors de la MAJ - geonature commande introuvable

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/gn_module_import#205]
Pas lié à la version du module (je l'ai déjà vu ailleurs... :/ ) mais lors de la MAJ, je me retrouve avec un geonature commande introuvable, quand je suis dans le venv. 

Je suis sur debian10 avec GN 2.6.

**Comment by DonovanMaillard** [comment]
Je me dépanne moi-même (pratique). Pas lié à l'import en effet... lié a GeoNature et à un fichier de log introuvable, qui fait que la migration n'était pas terminée correctement. 

Déjà eu en effet ce soucis de fichier log manquant/droits d'écriture manquants, qui bloque certaines étapes de migration.sh.

**Comment by TheoLechemia** [comment]
Tu as solutionner le problème comment ?

**Comment by DonovanMaillard** [comment]
C'était lié à GeoNature en lui-même (migrate.sh), rien à voir avec l'import. 

J'ai le module export sur mon instance mais il n'était pas du tout à jour. Du coup le fichier gn_export/cron.log était manquant, ca bloquait le script. J'ai solutionné le soucis en créant manuellement mon fichier manquant et relancé le migrate.sh. 

Comme cet étape n'était pas bien passée lors de ma MAJ de GeoNature (mais je n'avais pas vu), la MAJ de l'import ne pouvait pas se faire correctement. Donc ça a atterri ici par erreur ;)
