### ISSUE TITLE
Suppression des imports

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/gn_module_import#207]
Lorsqu'on supprime un import, il semble que les données ne sont pas supprimées de la synthèse. C'est en tous cas le cas sur mon instance... @TheoLechemia ça fonctionne chez toi? Les données sont bien censées être retirées de la synthèse lorsqu'on supprime l'import ?

**Comment by DonovanMaillard** [comment]
A moins que mes doublons ne viennent de la version précédente du module et que ce point a été corrigé depuis?

**Comment by camillemonchicourt** [comment]
On avait testé et ça fonctionnait bien.
Mais en effet quand on supprime un Import, ça supprime les tables sources, les données dans la Synthèse, la source, l'import...

Si c'est plus le cas, c'est que quelque chose à casser ?

**Comment by DonovanMaillard** [comment]
Je viens de refaire le test. Ca fonctionne, avec un mais. 

Du coup, si j'importe avec la 1.1.1 et que je supprime, c'est ok. 

Dans mon cas j'avais importé avec une version antérieure. J'ai réimporté les mêmes données (avec la ref biblio) avec la 1.1.1. J'ai voulu supprimer l'import initial sans la ref biblio, et c'est là que ca n'etait pas passé, j'ai du supprimer manuellement deux sources de la synthèse. 

Je pense qu'il y a peu d'utilisateurs concernés par ce cas de figure, la version actuelle est bien fonctionnelle. Reste à voir si d'autres ont le soucis s'ils essaient de supprimer des imports antérieurs.

**Comment by xavyeah39** [comment]
Étant aussi dans ce cas de figure, je confirme le comportement décrit par Donovan ;)
Après mise à jour du module en v1.1.1, la suppression d'un import réalisé précédemment avec la v1.1.0 ne supprime pas les données dans la synthèse.
En revanche, aucun soucis pour un nouvel import réalisé puis supprimer avec la v1.1.1.

**Comment by TheoLechemia** [comment]
Que disent vos logs lors de la suppression d'import d'une version précedente ?

**Comment by camillemonchicourt** [comment]
Corrigé avec la v2 du module, plus stable et robuste.
