### ISSUE TITLE
Enhancement - Vérification emprise géographique lors de l'import 

### ISSUE THREAD

**Issue by Adrien-Pajot** [PnX-SI/gn_module_import#212]
Lors d'imports de gros volume de données, les erreurs sont forcément plus nombreuses. 

Un petit check (ralentissant forcément les performances) de la présence des données dans une emprise géographique définie pourrait permettre d'éviter les problèmes lon/lat qui sont (très) nombreux.
Ceci pourrait être laissé au choix de l'admin d'activer ou non le trigger (peut-être même un bouton en front).

**Comment by camillemonchicourt** [comment]
C'est déjà le cas, et il y a un paramètre pour l'activer ou non, justement car c'est lourd : https://github.com/PnX-SI/gn_module_import/blob/master/config/conf_gn_module.toml.example#L5-L7

On l'a peut-être désactivé sur l'instance du PNE.
