### ISSUE TITLE
Inversion correspondance des nomenclatures

### ISSUE THREAD

**Issue by bouttier** [PnX-SI/gn_module_import#213]
L’étape de correspondance des nomenclatures liste l’ensemble des champs de la synthèse pour lesquelles un champs source a été sélectionné lors de l’étape de correspondance des champs.

Actuellement, pour chaque champs, il est listé l’ensemble des nomenclatures du SINP, avec pour chacune un select permettant de choisir une valeur source dans celle identifié dans le fichier téléversé.

Je propose d’inverser le processus : lister les valeurs relevées dans le fichier téléversé, et permettre pour chacune de sélectionner la valeur de destination.

Les avantages sont les suivants :
- Un formulaire plus court réduit aux seuls valeurs effectivement présentes dans le fichier source.
- La suppression du warning dynamique indiquant qu’une valeur source n’a pas été associé. On a une visibilité immédiate sur l’avancement du mapping en regardant les select complétés / vierges.
- Il devient possible d’associé plusieurs valeurs source à une même valeur de destination (utile si le fichier source contient par exemple « NSP » mais également « Ne sait pas »)
- Une démarche plus « logique » : il me semble que l’on cherche plutôt à déterminer les valeurs cibles pour les valeurs sources plutôt que l’inverse.

**Comment by DonovanMaillard** [comment]
Bonjour, 

Pour information puisque tu n'étais pas dans le projet à l'époque, ce point a été discuté a plusieurs reprises dès la rédaction du cahier des charges, et les deux possibilités ont été envisagées. A la base, c'était même la solution que tu propose qui était venue en premier. Mais finalement :

- On ne connait pas le fichier source, il est donc impossible de savoir si le formulaire sera plus long ou plus court : quelqu'un qui fonctionne avec du texte et non pas une liste prédéfinie pourrait tout à fait avoir davantage de textes source qu'il n'existe de nomenclatures cibles
- On connait en revanche les nomenclatures cibles : quelqu'un qui fait différents imports de plusieurs fichiers se retrouve toujours face au même formulaire en fonctionnant dans le sens actuel
- Il est déjà possible d'associer plusieurs sources à une cible en principe, le formulaire est multiselect (sauf si ça a changé récemment)
- Niveau logique, on a dans la 1ere étape la liste des champs cibles, on y liste le champs source correspondant. Du coup il a été finalement choisi d'avoir dans la seconde étape toutes les valeurs cibles et d'y lister les sources. 

Quelque soit le sens retenu, il ne nous a pas semblé in fine qu'une solution soit largement meilleure qu'une autre. Tout ca est pour info, je ne suis pas particulièrement attaché à une manière de faire ou à une autre... 

Dans l'idée, c'est une modification plus profonde qu'il faudrait à cette étape longue et rébarbative. Il faudrait pouvoir s'en passer ou au pire, la préremplir au maximum en enregistrant des synonymies au fil des imports. Si je rentre plusieurs fichiers avec M=Mâle, à terme le module doit proposer d'office cette correspondance pour le champs sexe. Et on peut même imaginer la même chose sur les champs, en recherchant le vocabulaire le plus fréquement mis en correspondance "nom latin=nom cité, obs=observateur, etc). Tout en gardant la possibilité de rectifier à la main s'il y a des erreurs.

**Comment by bouttier** [comment]
Merci Donovan pour ces éclairements sur ce choix. Je me permet de continuer sur ce ticket, je ne crois pas que ce trade-off soit discuté ailleurs publiquement.

- Il me semble un bon compromis qu’un fichier simple produise un formulaire simple, un fichier complexe produise un formulaire complexe.
- Le formulaire diffère entre 2 fichiers, mais reste tout de même structuré par les champs de synthèse.
- Le comportement multiselect dont tu parles semble avoir été modifié : lorsqu’une valeur est saisie dans un select, elle est supprimé des autres select. Cela empêche en effet d’associer plusieurs sources à une cible, cependant cela permet également d’avoir une bien meilleur visibilité sur l’avancement de la correspondance dans le fonctionnement actuel. À noter que pour les champs, il est bien possible d’associer 2 champs sources à un même champs de destination.
- Cohérence avec la correspondance des champs : très juste ! Cela me donne envie d’inverser également la correspondance des champs, mais je suis forcé de reconnaître que cela serait alors nettement moins lisible que ce qui est fait maintenant grâce à la catégorisation des champs, ou même la visibilité des champs obligatoires. Je note toute de même une différence entre champs et valeurs : certains champs source peuvent être ignoré, mais lorsqu’ils sont sélectionnés, il faut être capable de traiter toutes les valeurs sources.

Quand à ta dernière proposition, j’ai l’impression que si l’on peut enrichir un mapping existant avec des nouvelles associations de champs (resp. valeurs) sans oublier les associations précédentes, même si non utilisé dans le fichier courant, on obtient à terme un mapping assez universelle se rapprochant de l’enregistrement des synonymes dont tu parles !

**Comment by camillemonchicourt** [comment]
Dans la 2.0.0 les correspondances ont été inversées : 

![image](https://user-images.githubusercontent.com/4418840/200694497-9838e14f-8e6d-4444-8ee5-c98bfd5f279b.png)

Comme discussion chaque solution a ses avantages et inconvénients.
