### ISSUE TITLE
Erreur 500 sur dEEFloutage donnée privée

### ISSUE THREAD

**Issue by JulienCorny** [PnX-SI/gn_module_import#216]
Bonjour,

Je crois qu'il y a un bug (erreur 500) pour remonter une erreur utilisateur (absence de la colonne dEEFloutage dans le fichier d'import : 'Le champ dEEFloutage doit être remplit si le jeu de données est privé') lorsqu'on travaille sur des données privées (champ 'origine de la donnée' dans le jdd). 

Il me semble que ça provient de la fonction 'dee_bluring_check' (nomenclatures.py) qui renvoie 'All' lorsque la donnée est privée et qu'il n'y a pas de 'bluring_col', ce qui ne convient pas ensuite comme type au paramètre 'id_rows' de la fonction 'set_user_error'
![erreur500_dEEFloutage](https://user-images.githubusercontent.com/40057801/116679771-39d9aa00-a9ab-11eb-9f32-5d23217de9b0.png)

**Comment by DonovanMaillard** [comment]
Même soucis constaté pour nous, ce contrôle devrait être optionnel... ou alors prendre une valeur par défaut en absence de l'info dans le fichier source.

**Comment by DonovanMaillard** [comment]
Au niveau de l'ORB Aura, il est nécessaire qu'on puisse désactiver cette contrainte. Si le jeu est privé et que DEE Flou n'est pas renseigné, alors diffusion avec la géométrie renseignée sans appliquer de floutage. 

Il faut qu'on puisse prévoir un paramètre qui permette de définir un code_nomenclature de DEEFLOU par défaut à la place, ou désactiver le contrôle en mettant "en dur" la nomenclature qui correpond à "pas de floutage"

**Comment by camillemonchicourt** [comment]
Il y avait pas déjà la possibilité de désactiver ce contrôle comme discuté ici : https://github.com/PnX-SI/gn_module_import/issues/171 ?

**Comment by bouttier** [comment]
Le paramètre s’appelle ``CHECK_PRIVATE_JDD_BLURING`` (avec la faute).
L’erreur 500 devrait être résolue dans la v2.

**Comment by camillemonchicourt** [comment]
Corrigé dans la 2.0.0
