### ISSUE TITLE
Permettre au module de restreindre les imports par zone géographique ou par taxon

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/gn_module_import#217]
Dans notre contexte il nous est nécessaire de filtrer les données que l'on importe ou non selon 2 critères : 
- La localité (en région uniquement)
- Les taxons (invertébrés seulement)

Je pensais d'abord nettoyer mes fichiers en amont mais c'est redondant pour chaque fichier et semble-t-il, intéressant pour d'autres instances. Dans le cas de Ginco, la bbox incluant métropole + dom-tom ne permet pas d'identifier des données à l'étranger par exemple, limiter les imports à un multipoygon de la France et ses eaux territoriales pourrait être plus adapté.

Nous aimerions donc ajouter une fonctionnalité qui permettra de n'importer que les données d'un certain zonage et d'une certaine emprise taxonomique. 

Concrètement il s'agirait d'ajouter 2 paramètres dans la conf du module, un ALLOWED_AREA_ID et un TAXONOMY_ID_LIST, qui n'importerait que les données dont le cd_nom est bien dans la liste de taxons autorisée, et situées dans l'aire géographique autorisée. Ca fonctionnerait en lien avec le ref_geo, et avec les listes de taxhub (par exemple la liste occtax pour ne pouvoir importer que les taxons saisissables, par cohérence).

**Comment by camillemonchicourt** [comment]
Attention au fait que cela peut alourdir les traitements que de comparer toutes les données à un territoire plus précis et/ou à une liste de taxons.
Prévoir que si ces paramètres ne sont pas renseignés, alors on ne filtre pas.

**Comment by DonovanMaillard** [comment]
Oui, ces paramètres on bien vocation à être optionnels et ne rien filtrer s'ils ne sont pas renseignés :)

Pour les temps de traitement, un peu moins important maintenant que la tâche s'effectue en arrière-plan avec un envoi de mail une fois le traitement terminé.

**Comment by DonovanMaillard** [comment]
Maxime de Natural Solution va se pencher sur la question, on resterait dans l'idée suivante : 

- Un paramètre **facultatif** indiquant une liste des taxons importables : on définit un id_list de taxhub, si le cd_nom importé n'est pas dans cette liste alors la données tombe en erreur  "N'appartient pas aux taxons importables". Si le paramètre n'est pas renseigné, alors c'est tout le taxref qui est utilisé par défaut
- Un paramètre **facultatif** indiquant un id de zonage du ref_geo : idem, si la donnée ne tombe pas dans ce zonage, la donnée tombe en erreur "Cette donnée est en dehors du zonage défini pour les imports" par exemple. Si le paramètre n'est pas renseigné, aucun filtrage géographique.

Pour le premier, aucun soucis relevé pour le moment. Pour le second, se pose la question de récupérer une géométrie du ref_geo par une API : est-ce qu'une API existe et renvoie ce type d'informations ?

**Comment by Adrien-Pajot** [comment]
A tester notamment sur des imports de plusieurs milliers de données. Et sinon simplifier la géométrie de l'emprise du territoire avant la comparaison ? (par exemple pour des zones immenses et bien découpées ça peut être pas mal de réduire le nombre de sommets)

**Comment by DonovanMaillard** [comment]
Le filtre taxonomique va poser peu de soucis, seul le géographique est à affiner en effet. 

Dans notre cas, on sera plus ou moins obligés de prendre le contour précis de la région, si on simplifie on va louper/garder des données qu'il ne faudrait pas au niveau de nos limites. On sait que ça va effectivement augmenter (fortement) le temps de traitement, mais ça me pose assez peu de soucis finalement avec le fonctionnement actuel qui  envoie un mail en fin de traitement : on ne bloque pas l'utilisateur devant son écran.

Après puisque c'est l'utilisateur qui définit son zonage, libre à lui de le simplifier en amont, mais ça ne doit pas être imposé par le module. On pourra toujours commenter le paramètre en précisant qu'une géométrie plus complexe rend le temps de traitement plus long...

**Comment by jpm-cbna** [comment]
Pour la question de l'utilisation de st_intersect avec les grandes géométries, il est possible d'utiliser [ST_Subdivide](https://postgis.net/docs/ST_Subdivide.html). Voir aussi [cet article](https://www.stevencanplan.com/2017/12/the-genius-of-using-st_subdivide-to-speed-up-postgis-intersection-comparisons/).
Je l'ai utilisé dans l'Atlas avec succès pour 12 millions de données et la géométrie de la région AURA.
Cela réduit considérablement le temps de traitement de st_intersect mais cela demande de créer une table pour stocker les géométries subdivisées...

**Comment by DonovanMaillard** [comment]
Merci pour ce retour ! 

On peut imaginer une table dans le schema imports, qui se renseigne/rafraichit uniquement lors de l'update_configuration du module si le paramètre est renseigné.

**Comment by DonovanMaillard** [comment]
Fait dans la version 1.2.0
