### ISSUE TITLE
Import de donnée : Bug volumes de données affichage message erreur

### ISSUE THREAD

**Issue by afourneyron** [PnX-SI/gn_module_import#238]
Bonjour, 

je viens de m'apercevoir lors d'un import de fichier de 58 000 données que le module d'import se met systématiquement en erreur sans dire de raison. Il y avais déjà un ticket sur le problème : [Soucis sur les volumes de données](https://github.com/PnX-SI/gn_module_import/issues/50)

Je voulais savoir s’il y avait la possibilité d'indiquer dans le petit bandeau rouge qui s'affiche (actuellement sans message), que l'erreur vient du nombre de données trop importantes qui génère un time out ? 

Merci beaucoup pour tout ce que vous faites :)

**Comment by DonovanMaillard** [comment]
Salut Axel, 

Es tu sur que cette erreur vient d'un timeout ? 

Ce qui prend du temps porte notamment sur les controles, et sur l'écriture des erreurs, ton fichier semble donc en comporter un paquet. Pour être sur que c'est bien le timeout qui pose soucis, tu peux remonter le timeout de gunicorn dans ton fichier geonature/config/settings.ini . Il y a quelque chose à relancer pour reprendre en compte la  nouvelle conf, il faut que je retrouve quoi...

**Comment by camillemonchicourt** [comment]
Mise en place des traitements asynchrones avec le worker Celery dans la 2.0.0 pour éviter ce genre de soucis.

Les performances restent cependant à tester et renforcer dans le cas de gros volumes de données.
