### ISSUE TITLE
Mauvaise détection d'encodage à l'import

### ISSUE THREAD

**Issue by vprunet** [PnX-SI/gn_module_import#239]
Le fichier joint m'a donné du fil à retordre. Il ne passait pas à l'import (problème d'encodage).
[UTF.csv](https://github.com/PnX-SI/gn_module_import/files/7268154/UTF.csv)
Après analyse hexdump du fichier, il semble que le problème vient du caractère C2A0 (espace insécable) devant zzzz : le fichier utf est valide, mais est reconnu comme ISO-8859-1 par goodtables (la lib qui est utilisée par le module d'import), ce qui entraine le rejet du fichier par le module d'import.
 
L'apparition du problème semble aussi liée à la petite taille du fichier csv (un seul enregistrement). Si on duplique la ligne de données, le fichier est bien reconnu comme UTF8 par goodtables.

J'ai fait le même essai avec frictionless, le successeur de goodtables. -> Pas mieux.

Il faut donc savoir que la vérification d'encodage du fichier source n'est pas fiable à 100% et rejette certains fichiers valides.

**Comment by vprunet** [comment]
Peut-être serait-il possible de vérifier que l'encodage est utf-8, plutôt que de demander à goodtables de deviner quel est cet encodage?

**Comment by camillemonchicourt** [comment]
Merci pour ce retour.
Un travail a été initié pour détecter automatiquement l'encodage du fichier et ne pas se limiter à l'UTF8 : https://github.com/PnX-SI/gn_module_import/issues/188

Il a été l'occasion d'une reprise plus globale du module Import, en cours dans la branche ``refactor`` (https://github.com/PnX-SI/gn_module_import/compare/refactor).

**Comment by camillemonchicourt** [comment]
Détection automatique de l'encodage du fichier source développée dans la 2.0.0
