### ISSUE TITLE
Erreur setuptools à l'installation

### ISSUE THREAD

**Issue by gildeluermoz** [PnX-SI/gn_module_import#244]
Lors de l'installation sur une version récente de Debian 10 (10.11), une erreur survient dans l'installation des dépendances (simpleeval).
En installant setuptools 57.5.0 l'installation se déroule normalement.
GN 2.7.5

` pip install setuptools==57.5.0`

**Comment by camillemonchicourt** [comment]
OK, on a testé une installation de ``develop`` (future 1.1.6 à venir) et on n'a pas eu de soucis avec ``setuptools``.
Il faudrait indiquer le message d'erreur en question mentionné dans ce ticket ?

Fixer une version de ``setuptools`` au niveau du module IMPORT peut causer des soucis si on a GeoNature ou un autre module qui demande une autre version, ça va finir en conflit sans pouvoir s’installer.

On a quand même fixé la version de ``setuptools`` dans la PR #259 en même temps que ``pyproj`` pour ne passer à sa version 3.x car la v3 nécessite PROJ 7.2.0 mais Debian 10 fournit PROJ 5.2.0, donc cela levait une erreur.

**Comment by camillemonchicourt** [comment]
Mis à jour dans la 1.1.6, même si cela peut poser les soucis évoqués ci-dessus.

**Comment by DonovanMaillard** [comment]
La version 1.2.0 reprend les requirements pour assurer une compatibilité Debian10 et Debian11 au dela de setuptools
