### ISSUE TITLE
Ecriture dans synthèse malgré un import non terminé en interface

### ISSUE THREAD

**Issue by gildeluermoz** [PnX-SI/gn_module_import#246]
Lors d'un import d'un fichier de 49612 données, j'ai lancé l'insertion dans la synthèse (dernière étape). Le module me rend la main après un certains temps à mouliner (il réaffiche l'étape avec le bouton pour insérer les données dans la synthèse). je clique une seconde fois sur le bouton. Idem, il me rend la main. L'import reste tagué comme à finir. Je le supprime et je recommence.
Même comportement.
Après controle, les données sont bien inséré dans la synthèse. Ceci m'a conduit à insérer 2 fois le même fichier avec 2 imports différents. Les 2 imports sont notés comme à finir dans l'interface. 
Au final j'ai du faire des bidouilles en base pour terminer cet import, et nettoyer les doublons.

**Comment by camillemonchicourt** [comment]
Ne devrait plus être possible dans la 2.0.0
