### ISSUE TITLE
Pas de détection des dates invalides

### ISSUE THREAD

**Issue by gildeluermoz** [PnX-SI/gn_module_import#247]
Un fichier source comportant des dates au format postgres `2020-08-25 41:37:45.235` par ex
Le module ne sait pas gérer ce format mais ne le signale pas.
Ca fini par une grosse erreur psycopg2 qu'il faut savoir lire pour comprendre que c'est un soucis de format de date.

Si le module détectait un mauvais format dans le rapport des erreurs ce serait plus clair.

**Comment by camillemonchicourt** [comment]
Ce format sera géré dans la version 2.0 et renverra une vraie erreur de format dans le cas où un format ne serait pas bon - https://github.com/PnX-SI/gn_module_import/commit/efd236620660b23bcca5e7b3de66a4e76c77afa2

**Comment by camillemonchicourt** [comment]
Géré dans la version 2.0.0.
Voir aussi https://github.com/PnX-SI/gn_module_import/issues/128
