### ISSUE TITLE
Premiers retours sur la démo partielle

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/gn_module_import#25]
Suite aux premiers tests sur une démo partielle (une démo plus complète allant jusqu'à l'envoi dans la synthèse sera diffusée dans quelques semaines), les premieres remarques : 

- Il faudrait griser le bouton "valider le mapping" tant que tous les champs obligatoires ne sont pas renseignés
- altitude max indiqué deux fois en interface

- Discuter du fonctionnement de la validation / commentaire validation et son interaction avec l'uuid (obligatoire dans geonature d'avoir un uuid pour valider une donnée)

- Permettre dans la table permettant la config de l'interface (à mettre en place) de définir les champs affichés ou non (et obligatoires ou non)

**Comment by DonovanMaillard** [comment]
Avec un fichier exporté de geonature démo (il a un wkt pas un x/y) le controle du mapping tourne et n'abouti pas, au lieu de renvoyer une erreur de type. Identifier le soucis.

**Comment by JulienCorny** [comment]
Bonjour,

Merci Donovan pour les retours. 

Pour le bouton 'valider le mapping', je l'avais mis en required tant que les champs obligatoires ne sont pas remplis mais ça a dû sauter lors des dernières modif, je le remet rapidement. 

Pour l'altitude_max effectivement c'est une coquille mais de toute façon je vais transférer la semaine prochaine toutes les infos relatives à l'affichage des champs du mapping dans 2 tables (bib_themes et bib_fields) à la place de les mettre dans le fichier de configuration, ce sera bien plus lisible et facile à contrôler et modifier. Et du coup cela permettra facilement de configurer les champs à afficher ou non, et/ou obligatoires. 

Pour le fonctionnement de validation / commentaire de validation et le lien avec l'uuid, faudrait qu'on en discute effectivement parce que je n'y ai pas encore réfléchi.

**Comment by JulienCorny** [comment]
Sinon en ce qui concerne l'avancée du développement, nous (@HamoudaAmine  et @JulienCorny ) avons commencé le mapping de contenu, le front est quasiment fini. Et l'envoi des info de la table utilisateur vers la synthèse est également bien avancé. On devrait donc pouvoir mettre à jour assez rapidement le serveur de démo avec une première version incluant un fonctionnement complet sur l'ensemble des étapes.

**Comment by JulienCorny** [comment]
Je n'arrive pas à reproduire le bug wkt, de mon côté ça fonctionne bien : lorsque j'indique une colonne wkt à la place d'un x ou y, l'erreur est détectée (voir copie écran)
![print wkt error](https://user-images.githubusercontent.com/40057801/68467442-798c5f00-0216-11ea-810d-8df5e00a8653.png)

**Comment by DonovanMaillard** [comment]
Corrigé par Julien
