### ISSUE TITLE
rapport erreur d'encodage mais succès de l'import tout de même 

### ISSUE THREAD

**Issue by AmelieTagliaferro** [PnX-SI/gn_module_import#252]
Bonjour, 
lors d'un import, nous obtenons un rapport d'erreur "erreur d'encodage" mais finalement l'import se fait sans encombre avec toutefois le rapport d'erreur lié à l'import. Est ce un bug ? 
Merci d'avance pour vos retours 
<img width="524" alt="encodage erreur CENC" src="https://user-images.githubusercontent.com/93383491/144639230-7937fb3a-a6c2-46e3-a08b-2d9f80209df2.PNG">
<img width="914" alt="erreur import" src="https://user-images.githubusercontent.com/93383491/144639360-d0a762ab-f7f6-47eb-b4f3-a61172be36a4.PNG">

**Comment by camillemonchicourt** [comment]
Corrigé avec la v2 du module, plus stable et robuste.
