### ISSUE TITLE
Debian 11 - Mise à jour des dépendances

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/gn_module_import#260]
Les dépendances actuellement utilisées ne permettent plus une installation à jour et fonctionnelle sur Debian11 et python 3.9 d'après Maxime Vergez. 

Une mise à jour des dépendances sera à creuser prochainement...

**Comment by camillemonchicourt** [comment]
Oui @bouttier a testé une installation en local sur Debian 11.
Il a en effet du mettre à jour les dépendances mais ça a fonctionné.

**Comment by DonovanMaillard** [comment]
Notamment en lien avec #244

**Comment by DonovanMaillard** [comment]
Il a prévu de faire un commit ici avec les dépendances à jour ou  il a géré ça manuellement pour les tests à ce stade ?

**Comment by mvergez** [comment]
Ok j'avais testé avec Python 3.9 et j'avais des problèmes notamment avec pandas je crois (0.24.2 dans les requirements vs 1.3.5). Même en essayant de le mettre à jour ça plantait lors de l'installation ou de l'utilisation.
Cool si ça fonctionne alors !

**Comment by bouttier** [comment]
J’avais fait ça manuellement. Par contre je pense qu’on est obligé de cibler des versions de certaines dépendances (pandas mais pas que) différentes suivant la cible Debian 10 ou 11, donc pas si simple.

**Comment by camillemonchicourt** [comment]
La version 1.1.6 sera juste compatible Debian 10.
Pour Debian 11, on a prévu de creuser ça avec la refactorisation.

**Comment by mvergez** [comment]
A voir suivant les dépendances mais tant qu'il y a un support de Python 3.7 (installé sur Debian 10 je crois et par la 2.6 de GeoNature) cela devrait fonctionner pour Debian 10 et 11 non ?
Pour pandas par exemple, le support en 3.7 est encore assuré : https://pandas.pydata.org/docs/getting_started/install.html#python-version-support

**Comment by bouttier** [comment]
Il n’y a pas que la version de Python installé qui importe. Par exemple, pyproj requière une certaine version de la bibliothèque PROJ. Ainsi, Debian 10 fournit PROJ 5.2.0, il faut donc pyproj<3 car la v3 requière PROJ 7.2.0. Pour le cas de cette lib, pyproj<3 support PROJ 7.2.1 fournis par Debian 11 donc ça marche, mais ça n’était pas gagné d’avance.

**Comment by gildeluermoz** [comment]
@bouttier, si tu en as le souvenir, est-ce que tu donnerais les dépendances à modifier/fixer pour faire passer l'install stp ?

**Comment by bouttier** [comment]
Remplacer pandas 0.24.2 par pandas 1.3.5 permet l’installation des dépendances pip sur Debian 11. Maintenant je ne sais pas si le code du module d’import est compatible avec cette version de pandas …

**Comment by cen-cgeier** [comment]
Le changement de version de pandas (et par la même occasion de geopandas 0.5.1 ==> 0.10.2), permet également une bonne installation de geonature sur Ubuntu 20.04

**Comment by gildeluermoz** [comment]
J'ai donc testé avec `geopandas==0.10.2` et `pandas==1.3.5` et l'installation se fait bien sur debian 11.
merci à tous les 2
Je dois prochainement intégrer des données sur cette instance, je ferai un retour pour dire si tout est ok ou s'il y a des soucis à l'usage du module.

**Comment by mvergez** [comment]
Merci @gildeluermoz pour la version des packages. J'ai aussi dû mettre à jour dask : `dask[dataframe]==2022.1.0` pour Debian 11.
J'arrive jusqu'à la dernière étape (4) et au moment d'importer dans la synthèse j'ai cette erreur : 
```
psycopg2.errors.DatetimeFieldOverflow: date/time field value out of range: "14/03/2019"
HINT:  Perhaps you need a different "datestyle" setting.
```

J'enquête...

**Comment by camillemonchicourt** [comment]
A priori @bouttier a trouvé une version qui fonctionnerait sur Debian 10 et Debian 11 : https://github.com/PnX-SI/gn_module_import/commit/f266406397599136a3e880f2b16d27af696dccf5

**Comment by RNF-SI** [comment]
Salut, j'essaye à mon tour d'installer le module import sur Debian 11.
J'ai modifié `requirements.txt` comme indiqué avec `geopandas==0.10.2` et `pandas==1.3.5`.
J'ai essayé d'ajouter `requirements.in` comme le commit de @bouttier (dans gn_module_import/backend ?)
J'ai une erreur qui apparait dans la partie `FUNCTIONS` et qui stoppe l'installation : 

```
-------------
--FUNCTIONS--
-------------

]
(Background on this error at: http://sqlalche.me/e/13/f405)


Error while installing GN module .The process returned:
        Error during module IMPORT installation


Error while installing GN module .The process returned:
        Error during module IMPORT installation
Remove the module in gn_commons.t_modules ...
```

Je ne trouve pas de log sur l'installation de modules, y en a t'il ?

**Comment by camillemonchicourt** [comment]
Le message semble indiquer que tu as déjà installé le module, qu'il est donc présent dans la table ``gn_commons.t_modules`` et que donc il ne peut pas l'installer.

**Comment by RNF-SI** [comment]
Non je n'ai pas le module import dans la table `gn_commons.t_modules` ...
J'ai plutôt interprété ce message comme "il y a une erreur à l'installation du module, donc on le supprime de la table t_modules sur laquelle on l'avait déjà enregistré".

**Comment by RNF-SI** [comment]
J'ai tenté d'installer le module sur mon autre instance GeoNature, en paramétrant directement `requirements.txt` avec les modifs précédentes. 
L'installation se fait sans problème. 

Mon problème sur la première instance vient donc soit :
- de traces de précédents essais d'installation du module qui empêche de le terminer (comment le vérifier ?)
- de ma configuration d'utilisateurs particulière (FDW de la table utilisateurs d'une autre instance)

**Comment by camillemonchicourt** [comment]
Je pencherai pour un soucis venant d'installations précédentes.
Mais désinstaller/réinstaller le module n'est pas évident, voir https://github.com/PnX-SI/gn_module_import/issues/278

**Comment by RNF-SI** [comment]
il ne semble rien y avoir dans ma base de données qui correspond au module import... 
d'ailleurs, la console semble renvoyer toutes les lignes commentées, et l'erreur apparait après 

```
-------------
--FUNCTIONS--
-------------
```

or les lignes qui suivent sont 

```
-----------------------
-----------------------
--GN_IMPORTS_ARCHIVES--
-----------------------
-----------------------
```

elles devraient apparaitre aussi si l'erreur arrive sur la commande suivante... je ne comprend pas bien

**Comment by camillemonchicourt** [comment]
Franchement je sais pas du tout. 
Si l'installation sur une autre GeoNature a fonctionné alors c'est certainement que cette installation à un truc qui coince, certainement lié à des installations précédentes mais je ne connais pas assez pour dire quoi.
Le module est en plaine phase de refonte (voir le ticket dédié sure sujet) pour packager son installation, le passer sous Alembic, mettre en place des tests automatisés, le rendre plus performant et robuste.

**Comment by RNF-SI** [comment]
J'ai un problème qui semble plus global en fait... j'ai essayé d'installer le module monitorings pour voir et j'ai la même erreur... je pense que je suis bon pour une réinstallation complète

**Comment by RNF-SI** [comment]
En testant l'import, j'ai une erreur à l'étape 3 :

```
[ERROR] {'message': "INTERNAL SERVER ERROR : Erreur pendant le mapping de correspondance - contacter l'administrateur", 'details': 'Expected meta to specify type DataFrame, got type pandas.core.frame.DataFrame', 'raisedError': 'GeonatureImportApiError'}
```

Peut être lié à des dépendances du Debian 11 ?

**Comment by camillemonchicourt** [comment]
Nouveau soucis, il vaut mieux privilégier un autre ticket pour ne pas mélanger des sujets potentiellement différents.
Quitte à faire des liens entre tickets si pertinent.

**Comment by RNF-SI** [comment]
ça semble être directement lié aux erreurs évoquées plus haut, donc pertinent ici non ? je peux refaire une issue si tu préfères.
@mvergez a indiqué avoir installé la version `dask[dataframe]==2022.1.0` (je pense que c'est `dask[dataframe]==2.1.0` ?), package qui semble être à l'origine de mon erreur. J'ai donc également fait l'installation de cette version, mais j'ai toujours la même erreur.

**Comment by mvergez** [comment]
Je confirme que c'est bien dask[dataframe]==2022.1.0 que j'ai dans mon requirements.txt (leur numéro de version n'est pas comme les autres).
Ça fonctionnait chez moi mais avec des cas simples je pense, je n'ai pas tout testé en profondeur...

**Comment by RNF-SI** [comment]
ok, mes excuses, en effet ça marche avec `dask[dataframe]==2022.1.0`. La version me semblait étrange. 
J'ai des erreurs mais liées à mon jeu de données, donc tout va bien pour l'instant.

**Comment by mvergez** [comment]
Aucun souci ! Effectivement, ces numéros de version sont un peu déroutants.
Si tu rencontres un problème de date (format postgres ou quelque chose du genre dans le log du backend) au moment de l'import dans la synthèse (dernière étape), n'hésite pas à faire "Précédent" pour revenir à l'étape des nomenclatures puis directement "Suivant" puis "Importer les données dans la synthèse". Je ne sais pas si c'est clair...

**Comment by camillemonchicourt** [comment]
Si tu as des problèmes de performances, cela peut être lié à https://github.com/PnX-SI/gn_module_import/issues/262#issuecomment-1047680332
On prépare une release corrective.

**Comment by mvergez** [comment]
Je fais suite au problème de date que j'ai eu sur Debian 11 et Postgresql 13.5. L'erreur était la suivante quand je cliquais sur 
![image](https://user-images.githubusercontent.com/85738261/158371293-725e11df-ce62-4062-bfd1-d8904b51838d.png)
 : 
```
psycopg2.errors.DatetimeFieldOverflow: date/time field value out of range: "14/03/2019"
HINT:  Perhaps you need a different "datestyle" setting.
```

J'ai donc suivi le "HINT" et j'ai modifié la query suivante : https://github.com/PnX-SI/gn_module_import/blob/eaed215750d00d5b957fa1eed2707fe0dc47a956/backend/db/queries/load_to_synthese.py#L36-L48
En ajoutant sous le `BEGIN;`
```sql
SET datestyle = DMY;
```

Je ne sais pas si c'est la bonne manière de résoudre le problème et cela implique de ne pouvoir importer que des dates au format Jour Mois Année.

D'après @bouttier, cela pourrait venir d'une nouveauté dans cette version de postgres. J'enquête...

Je pourrai faire une PR avec les bons requirements pour que le module fonctionne sur Debian 11 si vous voulez

**Comment by gildeluermoz** [comment]
Le paramètre `datestyle` peut être déduit de la locale au moment de l'installation de Postgres.
Il peut donc être différent d'un serveur à l'autre, selon la manière dont debian a été installé.
Le forcer peut donc être utile s'il doit tjs être à `DMY`.

**Comment by mvergez** [comment]
Merci pour ton retour !
Tu préconises donc de mettre ce paramètre dans la configuration postgres (si c'est possible) ? Ou la solution que j'ai proposée est convenable ?

**Comment by gildeluermoz** [comment]
Le paramètre `datestyle` est défini pour tout le cluster postgres dans `postgresql.conf,`  par exemple sur un de mes serveurs : `datestyle = 'ISO, DMY'`. A ce niveau, on ne contrôle pas ce qui peut être fait pas les uns ou les autres. Et notamment par ce qui est fait par défaut lors de l'installation de postgres. Visiblement, si tu as un soucis avec ça, c'est que tu ne dois pas avoir DMY pour ton cluster postgres (que dit `SHOW datestyle;` ?)
Mais tu peux le définir pour une base de données en particulier : `ALTER DATABASE mydb SET datestyle TO "ISO, DMY";`
Ou le définir temporairement pour l'exécution d'un script comme tu le proposes.
Il n'y a pas de recette unique. 
La bonne recette pour GeoNature est à discuter avec la team.
JA priori, il me semblerait bienvenu d'avoir la garantie que ce paramètre soit à `DMY`, au moins pour la base GN, voir pour le cluster postgresql si celui-ci n'habrite pas de bdd ou cela pourrait poser un soucis. Donc à régler à l'installation de la base plutôt que de manière isolée dans un des scripts SQL d'un des nombreux modules GN.

**Comment by mvergez** [comment]
Merci beaucoup pour ton retour. Effectivement, sur une autre VM Debian 11 (sûrement mieux configuré que ma machine) j'ai pu installer le module d'import et tester sans avoir besoin de SET datestyle. Je vais tester la commande `SHOW datestyle;`, merci pour l'astuce !
On attendra un retour de l'équipe GeoNature, mais j'ai l'impression qu'en mettant bien les locales ça semble être bon. Sinon effectivement, à mettre dans la configuration du cluster postgresql
Merci encore !

**Comment by camillemonchicourt** [comment]
Compatibilité Debian 10 et 11 mise en place dans la version 1.2.0.
