### ISSUE TITLE
Gestion de la t_sources

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/gn_module_import#27]
Deux possibilités pour la t_sources : 

Actuellement, la t_sources de gn_synthese stocke une source=un module. 

Est-ce qu'on garde ce principe pour l'import? 
L'autre solution, plus pertinente mais qui va largement augmenter la taille de la table t_sources, c'est de créer une source par import; C'est pertinent car chaque import a sa table et son champs entity_source_pk_field qui lui est propre. 

Perso je pencherais donc pour cette 2eme solution, mais qui va faire perdre en visibilité dans la t_source... alors qu'on peut également, dans le module d'imports, stocker les champs des pk_source. 

Un retour sur ce point, notamment @gildeluermoz  qui a le recul sur la gestion des sources ?

**Comment by camillemonchicourt** [comment]
Une source ne correspond pas forcément à un module.

Une source permet d'identifier la table source d'une donnée présente dans la synthèse. Il s'avère que chaque module contient une table source de la synthèse.

Mais pour les imports de données tiers, on a bien une source par table. C'est déconnecté de la notion de module.

**Comment by DonovanMaillard** [comment]
Développé. 

Le module renseigne, dans la t_source, une ligne par import décrivant bien l'identifiant de l'import, la table et le champs entity_source_pk_field correspondant.
