### ISSUE TITLE
Problème de contrôle de type_info_geo ?

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/gn_module_import#271]
Sur la version 1.1.7 (et plusieurs versions précédentes) : 
- J'exporte des données de la Synthèse d'un GeoNature
- J'importe ces données avec le module Import dans un autre GeoNature
- J'utilise le modèle d'import des champs fourni par défaut "Synthèse GeoNature" qui me mappe bien toutes mes colonnes
- J'utilise le modèle d'import des nomenclatures fourni par défaut "Nomenclatures SINP (labels)" qui me mappe bien toutes mes nomenclatures

Mais au moment de l'import j'ai une erreur qui est renvoyée : 
![Capture d’écran de 2022-01-12 13-02-44](https://user-images.githubusercontent.com/4418840/150114066-92f0e48c-8438-4ec2-8825-0957c0665955.png)

Pour que mon import passe, il faut que je ne mappe aucun champs de mon fichier source avec les champs de destination "Type d'information géographique" et/ou "Nature d'objet géographique", je ne suis plus certain duquel pose soucis.

Je pense que c'est le contrôle sur type_info_geo qui a été ajouté dans la 1.1.1 (https://github.com/PnX-SI/gn_module_import/issues/176) qui pose soucis ? 
Ce sujet est pas clair du tout pour moi.

A désactiver par défaut ici : https://github.com/PnX-SI/gn_module_import/blob/master/config/conf_schema_toml.py#L152 ?

**Comment by bouttier** [comment]
Après relecture du standard, il apparaît que la nomenclature « type d’info géographique » sert à distinguer, lorsque qu’une observation est lié à plusieurs données géographique, quelle est la donnée géographique de référence, la plus précise (même s’il s’agit d’une commune) (= géoréférencement), et quelle sont les données géographiques secondaires déduites de la donnée géographique de référence (= rattachement).

Dans le cadre du module d’import, celui-ci prend en entrée une seule donnée géographique. Même lorsque l’on en sélectionne plusieurs lors de l’association des champs, on en retiendra une seule, par exemple le WKT plutôt que la commune lorsque cette information est disponible dans le fichier fourni.
Cette données géographique est donc **forcément** l’information de référence dont on dispose, **même s’il s’agit d’une information flouté**.

La présence de la colonne « type info geo » dans la synthèse de GeoNature n’a pas de sens. En effet, la colonne « the_geom »  contient toujours l’information géographique de référence (= géoréférencement), même lorsque la donnée est présente flouté. Le champs de nomenclature blurring (a.k.a. DEE_FLOUTAGE) permet d’indiquer que l’information dont on dispose est flouté, mais ce n’est pas le rôle de « type info geo ».
La nomenclature « type info geo » peut avoir un intérêt par exemple lorsque l’on récupère une observation avec ses zones associées. En effet, il s’agit d’information déduite de la géom, et il s’agit donc bien d’information géographique de type rattachement au sens de cette nomenclature.

Le contrôle doit donc être supprimé, et tant que la colonne type info geo est présente dans la synthèse, celle-ci doit être peuplé avec la valeur géo-référencement.

**Comment by camillemonchicourt** [comment]
Suppression du TYP_INFO_GEO dans la 2.0.0
