### ISSUE TITLE
Import occurrences habitat

### ISSUE THREAD

**Issue by AmelieTagliaferro** [PnX-SI/gn_module_import#274]
Bonjour, 
est-il possible avec la nouvelle mise à jour de Geonature d'importer des occurrences d'habitat ? 
C'est peut être un sujet qui a été évoqué précédemment, mais je n'en ai trouvé aucune trace dans les issues hormis la #108 qui l'évoque rapidement.
Merci par avance pour vos retours et merci pour votre travail ! 
Bonne journée,

**Comment by camillemonchicourt** [comment]
Bonjour,
Le module IMPORT actuel ne permet que d'importer des occurrences de taxons dans la Synthèse de GeoNature.
Il est prévu d'étendre le module (ou d'en créer un autre) pour les imports d'occurrences d'habitat.
A priori cette année, mais rien de certain et planifié pour le moment.

D'ici là il est bien entendu possible d'importer des occurrences d'habitat directement dans la BDD pour en disposer dans le module Occhab.

**Comment by AmelieTagliaferro** [comment]
D'accord ! Merci pour ces précisions,

**Comment by camillemonchicourt** [comment]
Duplicate - https://github.com/PnX-SI/gn_module_import/issues/303
