### ISSUE TITLE
[1.1.7] Coordonnées géographiques en dehors du périmètre de l'instance - erreur bbox ?

### ISSUE THREAD

**Issue by Splendens** [PnX-SI/gn_module_import#275]
Bonjour, 

Avec GeoNature 2.9.0 et le module d'import 1.1.7, j'ai une erreur sur toutes mes coordonnées géographiques, alors que le même fichier passe sans problème avec le module d'import 1.1.6 et GN 2.8.1.

![image001](https://user-images.githubusercontent.com/19465859/150786992-ec9f5530-0fdc-444e-b4c9-3bb24a5bdcac.jpg)

Les géométries sont des points en WKT, SIRD 2154, les localités sont bien en France métropolitaine, et dans la config du module j'ai  INSTANCE_BOUNDING_BOX = [-5.0, 41.0, 10.0, 51.15] (celui par défaut sur la métropole + Corse). 

Dans les logs, j'ai ces erreurs lors de la tentative d'import : 
```

[2022-01-24 13:02:02 +0000] [16246] [INFO] Find nomenclature with errors :
update t_imports from step 3 to step 4
[2022-01-24 13:02:02 +0000] [16246] [INFO] update t_imports from step 3 to step 4
-> t_imports updated from step 3 to step 4
[2022-01-24 13:02:02 +0000] [16246] [INFO] -> t_imports updated from step 3 to step 4
Get valid data for preview
[2022-01-24 13:02:02 +0000] [16246] [INFO] Get valid data for preview
the JSON object must be str, bytes or bytearray, not NoneType
[2022-01-24 13:02:02 +0000] [16246] [ERROR] the JSON object must be str, bytes or bytearray, not NoneType
Error while calculate bbox
[2022-01-24 13:02:02 +0000] [16246] [ERROR] Error while calculate bbox
-> got valid data for preview
[2022-01-24 13:02:02 +0000] [16246] [INFO] -> got valid data for preview
```

Il s'agit d'un bug sur la nouvelle version du module, ou bien il y a un paramétrage que j'ai raté ?

**Comment by Splendens** [comment]
J'ai pris le même fichier, et à la place du WKT, j'ai calculé le X et Y des géométries et retenté l'import avec un X/Y. Résultat : l'import a fonctionné ! C'est donc mes géom en WKT qui ont foiré... 

Avant de fermer ce ticket : est-ce que quelqu'un arrive bien à importer des géométries en WKT ?

**Comment by camillemonchicourt** [comment]
OK donc ne ferme pas, il y a peut-être un soucis actuellement avec les wkt.
A tester, investiguer.

**Comment by Splendens** [comment]
Finalement, même problème avec des coordonnées X / Y en WGS84.
Il n'y a que les coordonnées en Lambert 93 qui passent (et surtout sans décimale, des coordonnées avec décimale font une erreur PROJECTION_ERROR dans le module)

**Comment by camillemonchicourt** [comment]
Ah bizarre car justement je pense avoir fait les tests du module avant la release avec des fichiers ayant des coordonnées XY en WGS84.

**Comment by jpanijel** [comment]
Suite à notre recette, nous n'avons pas remonté d'erreur à l'import avec l'import de géométrie au format WKT et en WGS84.
