### ISSUE TITLE
[1.1.7] UUID non générés par défaut ? question

### ISSUE THREAD

**Issue by Splendens** [PnX-SI/gn_module_import#279]
Bonjour,

Lorsqu'on fait un import, si on ne matche pas de champ "UUID" et qu'on ne coche pas la case "Générer l'identifiant SINP", les données sont importées en synthèse sans UUID. 

C'est un choix délibéré ? Une question de performance ?

**Comment by camillemonchicourt** [comment]
Oui si on ne coche pas la case l'indiquant explicitement, c'est normal de pas le générer, non ?

**Comment by Splendens** [comment]
La question, c'était plutôt dans le sens de pourquoi laisser le choix ? 

Ca me semblait bien rentré dans les mœurs d'utiliser les UUID. D'autant plus que j'ai l'impression que pas mal d'utilisateurs viennent sur GeoNature en partie pour le côté "respect des standards SINP". 

D'où mon questionnement : si l'utilisateur ne spécifie pas de champ UUID à conserver lors de l'import, pourquoi, par défaut, ne pas générer des UUID ? 
Peut-être à cause des données importées depuis des bases de générant pas d'UUID ?

**Comment by camillemonchicourt** [comment]
Car on s'est dit que dans certains cas, un partenaire nous fournit un jeu de données ne comprenant pas d'UUID, alors que les données fournies ont bien un UUID par ailleurs, car ils ont été intégrés dans une plateforme SINP par ailleurs par exemple où des UUID leur aurait été attribués.

Et donc qu'il serait contre-productif et dommage de leur générer d'autres UUID de notre côté, alors que ce sont des données partenaires que nous ne gérons pas.

**Comment by Splendens** [comment]
C'est bien ce que j'imaginais, et pour moi c'est clair, merci !

Pour ce qui est de l'utilisation du module par des utilisateurs qui ont un peu moins la tête dans les données, c'est peut-être plus un problème d'ergonomie. Le formulaire de matchage des champs est balaise, et les utilisateurs ne font pas trop attention aux petites cases à cocher (UUID, altitudes).

**Comment by bouttier** [comment]
On pensait modifier la case « générer les altitudes » en « générer les altitudes **manquantes** », et la mettre cochée par défaut. Peut-être peut-on faire pareil « générer les UUID manquants » et l’activer par défaut ? (ça me semble rester plus risquer que pour les altitudes …)

**Comment by camillemonchicourt** [comment]
Moi ça me semble de faire comme ça.
Plus simple et intuitif et fais par défaut pour ceux qui ne savent pas trop.
Et aussi pour avoir des mécanismes simples et cohérents entre les différents champs.
Donc je suis pour ta proposition.

**Comment by DonovanMaillard** [comment]
En effet, pour les altitudes, les calculer par défaut ne me pose pas de socis, mais pour l'UUID c'est un coup à générer des doublons surtout pour les utilisateurs qui n'ont pas la tête dans la gestion de données. 

Se pose aussi, d'une manière plus large, la question de confier les imports à des utilisateurs non gestionnaires de données, qui n'ont pas toutes les références sur les champs, les nomenclatures SINP etc mais c'est un autre débat. A l'origine ce module a été pensé pour des administrateur, mais même pour tous les utilisateurs il faut pouvoir laisser le choix de calculer ou non les uuid (et à mon sens ne pas l'activer par défaut)

**Comment by camillemonchicourt** [comment]
Je pense qu'il est important d'avoir de la cohérence et de l'homogénéité pour simplifier la compréhension de l'outil, du processus, et pas à chaque fois se poser la question d'un bouton qui a une logique, et un autre similaire un peu plus bas qui en a une autre.
Et quand même plutôt privilégier que des UUID soient générés si le fichier n'en fournit pas.

**Comment by gildeluermoz** [comment]
De ma courte expérience, comme le dit très bien Donovan, les utilisateurs ne maitrisent pas tous cette notion d'UUID. Je vois que les données circulent beaucoup entre les structures. Avec ou sans UUID. 
Tout dépend qui utilise le module d'import. S'il s'agit d'une structure "SINP Like", qui regroupe beaucoup de sources diverses, l'administrateur de données maitrise généralement bien l'import, l'export et la notion d'UUID. 
Par contre chez les structures productrices des observations, la situation est très hétérogène. Chez ces structures, les imports sont soit 
* des données historiques de la structure elle même 
    * sans UUID localement mais plus ou moins déjà remontées au SINP, donc potentiellement avec un UUID qui n'est pas revenu auprès du producteur
    * avec UUID (a priori ce n'est pas la généralité)
* des données de partenaires
    * avec UUID transmis (cas simple mais pas si fréquent)
    * sans UUID transmis mais ça ne veut surtout pas dire qu'il n'existe pas qq part au SINP régional ou national
Donc "forcer" la génération d'UUID ne me semble pas pertinent car créer des doublons avec 2 UUID différents me semble plus problématique que d'intégrer des données sans UUID.

Au delà de la difficile traduction de cette complexité dans l'interface, le module d'import ainsi que le module d'export, permettent d'administrer des données sans être administrateur de données. C'est un avantage mais ça peut aussi être un problème.
Il n'y a pas de solution toute faite, sinon que d'informer au mieux les utilisateurs de tout cela.
OU que la production d'un UUID par une structure autre que le producteur remonte systématiquement auprès du producteur et que celui-ci soit en capacité de l'associer à ses données.
Bref je pense qu'on en parlera encore longtemps !

**Comment by camillemonchicourt** [comment]
La question est donc de savoir ce que l'on veut pousser par défaut pour ceux que cela dépasse : 
- Que si ils ne savent pas et que ça les dépasse, privilégier de générer des UUID par défaut pour être sur d'en avoir
- Privilégier de ne pas en générer dans le doute où ces données auraient déjà des UUID ailleurs

De mon côté, je suis plutôt sur le premier cas. 
Si c'est divergent ou différent selon les contextes, il faudra envisager un paramètre pour pouvoir définir si la génération des UUID manquants est cochée par défaut ou non.
Et dans tous les cas, faire une petite info bulle d'aide à côté de ce champs, expliquant ce que sont les UUID, à quoi ils servent, et dans quels cas il est conseillé de les générer ou non.

**Comment by gildeluermoz** [comment]
C'est bien résumé. Merci Camille.
Pour ma part je ne le cocherais pas par défaut car il y a beaucoup de données importées qui sont des données de partenaires ou produites par des prestataires experts qui peuvent aussi les détenir et les partager dans tous les sens. Et comme ce genre de données intégrées dans son GeoNature n'a pas vocation à être exporté, l'UUID n'est pas utile.
Choisir de produire un UUID est une démarche qui doit se faire en connaissance et donc si tu le veux, tu sais ce que tu fais et tu le coches.

**Comment by camillemonchicourt** [comment]
Oui il y a des approches et des contextes différents.
Mais vivement que les gens "partagent leurs données dans tous les sens" car même si ça avance doucement, c'est encore beaucoup l'inverse 🤣

**Comment by DonovanMaillard** [comment]
A l'inverse de toi camille, je pense qu'il ne faut pas générer d'uuid par défaut... Si vraiment un administrateur qui connait la question juge qu'il en fallait, il sera toujours en mesure d'en générer avant transferts

**Comment by camillemonchicourt** [comment]
Ça dépend des contextes.
Chez nous je dirai que pour 90% des imports on intègre des données PNE pour la première fois dans le système et on veut absolument leur attribuer des UUID.
Pour des données partenaires c'est différent en effet, mais c'est beaucoup moins notre cas d'usage avec le module Import.
Pour une plateforme de dépôt comme DEPOBIO il faut absolument attribuer un UUID aux données déposées si ils n'ont pas été générés en amont dans l'outil source (cas encore rare), sans que les déposants ne se posent avec ce sujet qu'ils ne maîtrisent pas.

**Comment by Splendens** [comment]
De mon côté, comme Camille,  je vois essentiellement des imports de données auxquelles il faut absolument attribuer un UUID car il s'agit de données saisies dans des tableurs (par les agents de la structure ou des presta), et qu'on importe dans la BD de GeoNature. Cela peut être des données contemporaines (malgré les outils de saisies web!), mais aussi énormément de données antérieures à l'utilisation de GN (et parfois, cela fait des années de tableurs...). 
C'est d'ailleurs pourquoi c'est bien des utilisateurs et non des administrateurs qui font ces imports. Ils sont les mieux placés pour savoir à quoi correspond quels champs / quelles valeurs à matcher ou non.

Autre idée : que les cases "générer les altitudes" et "générer les uuid" soient cochées d'office ou non, peut-être qu'un message d'alerte serait le bienvenu ? Quelque chose du style "Les UUID ne seront PAS générés lors de l'import de données", ou à l'inverse : "vous avez choisi de générer les UUID sur l'import de données".

**Comment by camillemonchicourt** [comment]
OK

**Comment by camillemonchicourt** [comment]
OK

**Comment by bouttier** [comment]
Que pensez vous de la pertinence de lever des messages d’avertissement (comme les erreurs mais de niveau avertissement seulement) pour les lignes sans UUID dans le cas où la génération est désactivée ? Si on rajoute cela, faut-il rajouter une option pour désactiver ces avertissements ?

**Comment by DonovanMaillard** [comment]
A mon avis la checkbox cochée par défaut ou non à l'échelle d'une instance suffit. Si on choisit de ne pas générer d'uuid par défaut c'est que notre contexte le justifie. C'est dans tous les cas impossible pour le module de savoir quel est le bon comportement à adopter pour un import donné. Je me limiterais au paramètre de la checkbox cochée par défaut ou non pour ma part. Mais une info n'est pas gênante non plus si ca répond aux besoins de certains.

**Comment by camillemonchicourt** [comment]
Le paramètre `DEFAULT_GENERATE_MISSING_UUID` permettant de définir si cette option est cochée ou non par défaut, a été ajouté il y a quelques temps.
