### ISSUE TITLE
Champs additionnels

### ISSUE THREAD

**Issue by cen-cgeier** [PnX-SI/gn_module_import#290]
Bonjour à tous,

en passant par le back-office > Champs additionnels, j'ai souhaité ajouter un/des champs à ceux proposés par le module d'import. Le seul module que le back-office me propose où je peux ajouter un champs est Occtax.

Est-il possible/envisager d'ajouter des champs personnalisés au sein du module d'Import ? (ou plus généralement au sein d'autres modules par le biais du back-office)

**Comment by camillemonchicourt** [comment]
Il n'est pas prévu de définir en amont des champs additionnels que l'on pourrait importer.
Mais il est prévu mieux il nous semble, avec la possibilité d'importer n'importe quel champs de la source dans le champs jsonb dédié au stockage des champs additionnels : https://github.com/PnX-SI/gn_module_import/issues/165

C'est développé et à venir dans la version 1.2.0 en cours de publication : https://github.com/PnX-SI/gn_module_import/blob/project-FLA_NS/docs/CHANGELOG.rst

**Comment by xavyeah39** [comment]
Salut,
Il n'est pas possible d'ajouter des champs additionnels au module d'import à proprement parler. 
Les champs a faire correspondre (mapping) dans le module d'import sont ceux de la synthèse.
Je pense que ce que tu souhaites faire c'est plutôt d'agréger plusieurs champs de ton fichier source à importer vers le champs `additionnal_data` de la synthèse non ?
Ce n'est pas encore possible via l'interface dans la version actuelle du module mais prévu et à venir dans la prochaine version. 
Voir #165 et #241

**Comment by xavyeah39** [comment]
> Il n'est pas prévu de définir en amont des champs additionnels que l'on pourrait importer. Mais il est prévu mieux il nous semble, avec la possibilité d'importer n'importe quel champs de la source dans le champs jsonb dédié au stockage des champs additionnels : #165
> 
> C'est développé et à venir dans la version 1.2.0 en cours de publication : https://github.com/PnX-SI/gn_module_import/blob/project-FLA_NS/docs/CHANGELOG.rst

Il est trop rapide ce Camille....

**Comment by cen-cgeier** [comment]
Haha, je ne m'attendais pas à ce que ma question suscite tant d'engouement..  
C'est exactement ce que je souhaite faire @xavyeah39 et je n'avais pas vu que c'était en cours de dev.
Merci à tous les 2 !

**Comment by camillemonchicourt** [comment]
Tu peux tester la future 1.2.0 d'ailleurs si tu veux, en téléchargeant directement la branche dans laquelle elle est actuellement en cours de finalisation, plutôt qu'une version "stable" : https://github.com/PnX-SI/gn_module_import/archive/refs/heads/project-FLA_NS.zip

**Comment by xavyeah39** [comment]
Pour info, voilà comment j'avais contourné ce manque en bricolant avec un peu avec du SQL : 
- préformatage en JSONB  de mon futur champ `additionnal_data` lors de la préparation de mon fichier a importer : 
```sql
json_build_object(
	'relv_nom', COALESCE(a.relv_nom,'non-renseigné'), 
	'methode_collecte', COALESCE(a.obse_pcole_choi,'non-renseigné'),
	'obse_nom', COALESCE(a.obse_nom,'non-renseigné'),
	'obsv_libel', COALESCE(a.obsv_libel,'néant'), 			
	'site_categ_choi', COALESCE(a.site_categ_choi,'non-renseigné'), 
	'nomlieu', COALESCE(a.nomlieu,'non-renseigné')
)::jsonb::text AS additional_data,
```
- je fais mon import via le module et je mappe ce faux champ `additionnal_data` dans un champ de texte de la synthèse que je n'utilise pas (`validation_comment` par exemple)
- une fois l'import réalisé, un petit coup de SQL pour re-ventiler les valeurs `text` en `jsonb` dans le vrai champ `additionnal_data` de `synthese` : 
```sql
UPDATE gn_synthese.synthese 
SET additional_data = validation_comment::jsonb
WHERE additional_data IS NULL 
AND id_source = 6 --> l'id_source de ton import crée par le moule d'import dans gn_synthese.t_sources
; 
UPDATE gn_synthese.synthese 
SET validation_comment = NULL
WHERE id_source = 6 --> l'id_source de ton import crée par le moule d'import dans gn_synthese.t_sources
```

**Comment by xavyeah39** [comment]
> Merci pour ton code @xavyeah39, on en avait discuté la dernière fois mais c'est toujours plus sympa à voir en vrai ! J'envisage d'ouvrir le module d'import aux collègues scientifiques pour qu'ils importent eux-même leur données (les leurs ou les partenaires). J'essaie donc de percevoir comment je peux me passer de cette manip

Oui cette solution alternative peut convenir pour un "one-shot" en attendant mais au quotidien et pour tes collègues ce sera bien mieux via l'interface avec la prochaine version du module.

**Comment by bouttier** [comment]
Suivi de l’implémentation dans l’interface dans le ticket #165
