### ISSUE TITLE
Maquette fonctionnelle du projet

### ISSUE THREAD

**Issue by orovellotti** [PnX-SI/gn_module_import#3]
Voila notre premier travail de maquette
[GeoNature Import - Copie.pptx](https://github.com/PnX-SI/gn_module_import/files/3044209/GeoNature.Import.-.Copie.pptx)
[GeoNature Import - Copie.pdf](https://github.com/PnX-SI/gn_module_import/files/3044210/GeoNature.Import.-.Copie.pdf)

**Comment by orovellotti** [comment]
Petite correction
[GeoNature Import.pdf](https://github.com/PnX-SI/gn_module_import/files/3044305/GeoNature.Import.pdf)
[GeoNature Import.pptx](https://github.com/PnX-SI/gn_module_import/files/3044306/GeoNature.Import.pptx)

**Comment by DonovanMaillard** [comment]
Merci Olivier, j'intègre tout ça au CR prochainement!

**Comment by DonovanMaillard** [comment]
Après avoir le CR (voir définition générale du projet), j'ai retravaillé très à la marge la proposition pour coller au mieux avec ce qui s'est dit, et/ou ce que j'avais en tête. Voici ma contre proposition.

![0](https://user-images.githubusercontent.com/23358384/56034420-8c45c080-5d27-11e9-93dc-f3cbb7adcca0.png)
![1](https://user-images.githubusercontent.com/23358384/56034421-8cde5700-5d27-11e9-97c1-0bcbfb0ccb86.png)
![2](https://user-images.githubusercontent.com/23358384/56034422-8cde5700-5d27-11e9-8ea7-f2ec112a891d.png)
![3](https://user-images.githubusercontent.com/23358384/56034423-8cde5700-5d27-11e9-91ab-5133fa9c0a2d.png)
![4](https://user-images.githubusercontent.com/23358384/56034424-8d76ed80-5d27-11e9-88e4-a6e7e9c6510f.png)
![5](https://user-images.githubusercontent.com/23358384/56034425-8d76ed80-5d27-11e9-9e8f-e978f282a9bf.png)

**Comment by DonovanMaillard** [comment]
L'étape actuellement numérotée 2 permettant de choisir le JDD et le mapping est supprimée. 

Lors de l'ajout d'un nouvel import, une modale s'ouvre et permettra de sélectionner le JDD. Ce choix se fait donc avant l'upload, ce qui permet à l'utilisateur d'être tout de suite rejeté s'il n'a pas de JDD créé en amont, sans chercher son fichier, déclarer ses séparateurs et son SRID. 

Dans le même temps, le choix du mapping se fera donc sur le haut de la fenetre 3. Le formulaire de mapping sera grisé tant que l'utilisateur n'aura pas choisi entre un mapping ou le fait d'en créer un nouveau. 

Se pose la question de pouvoir réouvrir la modale de choix du JDD pour changer de jeu de données en cas d'erreurs.
