### ISSUE TITLE
Import vers Monitoring, Occhab, Occtax...

### ISSUE THREAD

**Issue by Adrien-Pajot** [PnX-SI/gn_module_import#303]
Bonjour, 

Ne me souvenant jamais si cela a déjà été discuté/si c'est dans les cartons, j'ouvre une discussion : 
la possibilité d'utiliser le module d'import vers le module monitoring est-elle envisager ? 
Celle-ci est en tout cas espérée mais implique beaucoup de réflexions....

**Comment by DonovanMaillard** [comment]
Pour le moment ce n'est pas sur le tapis et ce n'est pas si simple techniquement, d'autant plus pour le module monitoring dont les infos attendues dans les champs json sont variables. 

A l'heure actuelle les réflexions et travaux se concentrent sur l'amélioration de l'existant et sa robustesse pour traiter au mieux et de manière plus performante les imports vers la synthese. Un import vers occtax serait également un besoin pour certains et moins complexe car on connaît les formats attendus mais ca reste compliqué. 

En l'état. Le module a des prémices pour supporter différentes cibles (dict fields etc qui ne sont pas en dur). Mais bcp de choses restent quand même à consolider avant d'envisager plusieurs cibles. 

Se pose aussi la question de la pertinence. Les modules de saisie ont leur propre schéma destiné à recueillir les donnees qui y sont saisies. La synthese a vocation à synthétiser les donnees venant de plusieurs sources. Ca mérite réflexion je oense au niveau concept...

**Comment by camillemonchicourt** [comment]
La réflexion sur une V3 du module IMPORT qui permettrait d'alimenter d'autres destinations que le module SYNTHÈSE a bien avancé : 
- Après analyse technique, il a été retenu que le module IMPORT pouvait évoluer pour alimenter d'autres destinations, plutôt que de développer un outil d'import spécifique à chaque module de destination
- @bouttier a fait une analyse et proposition technique qui a un peu évolué depuis : [multidest.pdf](https://github.com/PnX-SI/gn_module_import/files/13686342/multidest.pdf)
- Les premiers développements ont commencé dans cette PR - https://github.com/PnX-SI/gn_module_import/pull/495

Le principe général est de : 
- Rendre plus générique le module pour pouvoir spécifier plusieurs destinations
- Factoriser les fonctions, interfaces et contrôles qui peuvent être communs à toutes les destinations
- Que chaque module de destination vienne renseigner et définir ses champs, ses spécificités, etc... pour que le module Import n'ait pas à gérer ça, ni à connaitre les destinations, qui peuvent être des modules non installés ou spécifiques à certaines instances
- D'intégrer le module Import dans le cœur de GeoNature car il s'agit d'une fonction transversale et maintenant qu'il est robuste et largement utilisé, pour en faire une brique du cœur de GeoNature que chaque module peut utiliser et étendre.

Niveau interface, on gardera les principes et fonctionnalités actuelles, en les étendant à plusieurs destinations : 
- On arrive sur une liste de tous les imports. On peut filtrer les imports par destination
- Quand on veut créer un nouvel import, on pourra sélectionner la destination (selon les permissions de l'utilisateur connecté). Si j'ai des permissions C dans le module de destination et des permissions C dans le module Import, alors je peux créer un import vers le module de destination.
- Les JDD, les formulaires de mapping et les modèles de mappings dépendent des permissions de l'utilisateur et du module de destination
- Depuis un module de destination, je peux avoir un accès direct aux imports dans ce module, avec un bouton IMPORTER si j'ai des permissions sur le module IMPORT et de création sur le module de destination. Cela me renvoie alors directement au module d'import avec le module de destination déjà sélectionné
- Il faudra désormais pouvoir importer vers des modules composés de plusieurs tables dans les modules Occtax, Occhab, Monitoring (contrairement à la Synthèse qui est à plat). Il est proposé de faire des imports dans les différentes tables du module depuis des fichiers à plat, pour simplifier l'utilisation et la préparation des fichiers à importer.
  - Ainsi si je veux importer 2 stations d'habitat qui ont 3 habitats chacunes, alors j'importerai un fichier qui a 6 lignes, où les infos des 2 stations sont dupliquées
  - Si j'importe des habitats sur une station existante, alors je renseigne son UUID dans le fichier à importer et dans ce cas-là la station ne sera pas créé, mais on créera uniquement des habitats associés à cette station. Cela pourra permettre à terme d'avoir un fonctionnement similaire pour importer des observations vers la Synthèse associés à plusieurs JDD, en mentionnant leur UUID dans le fichier à importer (https://github.com/PnX-SI/gn_module_import/issues/493)

Les développements vont commencer par permettre d'importer dans Occhab, puis Monitoring (plus complexe car plus de niveaux et surtout car la structure des sous-modules est différente à chaque sous-module).
On pourra ensuite envisager des évolutions pour importer vers Occtax, Métadonnées, ou d'autres modules plus spécifiques.

**Comment by gildeluermoz** [comment]
Pour importer vers occtax est-ce qu'une première approche consistant à pousser des données de la synthèse vers occtax ne serait pas plus générique et plus simple que de complexifier le module d'import ? Synthèse et Occtax sont très proches. Synthèse étant presque une vue applatie des 3 tables d'Occtax.

Dans le module d'import, l'utilisateur choisi un import terminé et il clique sur un bouton 'vers occtax'. Il faut "juste" désactiver les trigger qui renvoient occtax vers la synthese avant d'écrire dans occtax et gestionner les UUID.

Sinon à voir s'il serait pertinent que ça trouve une place dans le module metadonnées pour s'appliquer potentiellement à d'autres source qu'Import. Dans la gestion des jdd par ex. (ceux qui contiennent déjà des données). En analysant au préalable les effets de bords biensûr.
Bon, faut bien gérer les données qui sont déjà dans occtax ainsi que les uuid mais c'est une piste pour enrichir GN d'une fonctionnalité certainement utile dans le cas de migration d'un autre outil vers GN.

Pour insérer vers Monitoring, c'est une autre affaire me semble t-il. Ca demande une grosse préparation des données à importer, avec la préparation de couches pour les sites, et toutes les spécificités et cas particuliers de chacun des sous-modules...

**Comment by camillemonchicourt** [comment]
On va faire évoluer le module d'IMPORT pour qu'il puisse alimenter Occhab, potentiellement aussi Occtax qui sera assez similaire.
Monitoring sera plus complexe mais est prévu.
Je préfère rester dans les modes de fonctionnement classique des imports, plutôt que de faire quelque chose d'un peu complexe et spécifique qui alimenterait la Synthèse et permettrait d'aller dans l'autre sens vers Occtax.

**Comment by camillemonchicourt** [comment]
En complément, le support de présentation du COTECH du 19 décembre de présentation faite par @bouttier : 
[import-multidest.pdf](https://github.com/PnX-SI/gn_module_import/files/13715784/import-multidest.pdf)

**Comment by camillemonchicourt** [comment]
Module Import enrichi et revu pour être multi-destinations (avec Occhab pour commencer, puis Monitoring à venir) et intégré dans le cœur de GeoNature à partir de sa version 2.15 : https://github.com/PnX-SI/GeoNature/issues/3269
