### ISSUE TITLE
Modification des données après l'import 

### ISSUE THREAD

**Issue by Adrien-Pajot** [PnX-SI/gn_module_import#304]
Déjà discutée précédemment et notamment dans le refact : https://github.com/PnX-SI/gn_module_import/issues/257 la modification est en sql. 

Ne pourrions pas envisager un onglet supplémentaire à la fin de l'import, que l'on retrouve sur la liste des imports pour effectuer cette modification ? 
Un sujet largement débattu je suppose mais je voulais ouvrir un ticket avec le titre adéquat pour retrouver (si pas déjà fait).

**Comment by bouttier** [comment]
Parles-tu vraiment d’une modification des données **après** l’import, ou avant l’insertion des données dans la synthèse ?
Qu’attends-tu de cet onglet supplémentaire ? Qu’il permette de faire quoi ?

Si tu parles vraiment d’une modification après l’import, je ne vois pas de quoi il peut s’agir à part modifier les données de la synthèse directement.

**Comment by Adrien-Pajot** [comment]
> Si tu parles vraiment d’une modification après l’import, je ne vois pas de quoi il peut s’agir à part modifier les données de la synthèse directement.

Je me suis dit pareil. Sauf qu'on veut l'éviter, du coup je me suis demandé si on devait faire une table intermédiaire synthèse like avec le coeur des données importées ou pas (ou comme validation?). L'idée serait de pouvoir supprimer avant insertion dans la synthèse donc mais aussi n'importe quand après un import, d'où la table intermédiaire.

**Comment by camillemonchicourt** [comment]
Le fait de pouvoir modifier en SQL les données pendant le processus d'import (sujet discuté dans #257) et le fait de pouvoir modifier/corriger des données importées sont 2 sujets différents.

Le deuxième (dont tu parles je pense) étant bien plus globale et pas liée directement au module d'Import, discuté ici : https://github.com/PnX-SI/GeoNature/issues/1455

**Comment by camillemonchicourt** [comment]
Sujet GeoNature, non lié directement au module Import.
