### ISSUE TITLE
Import vers OccTax

### ISSUE THREAD

**Issue by Adrien-Pajot** [PnX-SI/gn_module_import#305]
Salut, 
En discussion avec les TAAF, et pour la quatrième fois en une semaine, le besoin d'importer les données directement dans OccTax a été énoncé. Cela va notamment avec #304 mais aussi le fait que la saisie de données se fait parfois sur un outil comme Qfield ou autre alors que ce sont des données opportunistes. 
Je n'ai pas trouvé de ticket ouvert sur le sujet (ou alors j'ai mal cherché) mais je crois bien qu'on en a déjà parlé, qu'en dites-vous ?

**Comment by DonovanMaillard** [comment]
Oui, déjà évoqué indirectement avec tes deux derniers tickets #303 en particulier, et en lien avec #304 

Ca mériterait en effet de s'y pencher mais ca reste un gros chantier et les financements/temps de réflexion qui vont avec à mon sens. Avoir un module comme import, qui vient "interférer" dans un autre module n'est pas forcément si simple. Notamment pour qu'import suive les mises à jour d'occtax, monitoring, et créer des dépendances entre les modules (que faire si on a import mais pas occtax ou pas monitoring, si l'utilisateur à les droits sur l'un des modules et pas l'autre, comment masquer/trier les fonctionnalités etc. Il y a forcement des solutions, mais oui ça reste un assez gros chantier je pense. Avec tout l'intérêt que ça représente, je pense qu'on est beaucoup à avoir importé à la main des données dans occtax...

**Comment by camillemonchicourt** [comment]
Oui c'est lié à #303
Tout reste à faire.

**Comment by Adrien-Pajot** [comment]
Yes pour l'instant c'est du manuel, merci pour vos réponses ! On peut laisser ouvert pour attaquer les réflexions techniques sur le projet quand on les aura avancées

**Comment by camillemonchicourt** [comment]
Duplicate https://github.com/PnX-SI/gn_module_import/issues/303
