### ISSUE TITLE
Retour utilisateur sur import de nombreuses données 

### ISSUE THREAD

**Issue by afourneyron** [PnX-SI/gn_module_import#338]
Bonjour,

Je me permets de poser un ticket pour faire un retour sur l'importation de jeu de donnée volumineux (125 000 données) sur la dernière release 2.9.2 

Le problème du ticket https://github.com/PnX-SI/gn_module_import/issues/50 est toujours présent, on ne peut pas importer plus de 10 000 données à la fois. 
Nous avons changé le timeout à 20min pour permettre l'intégration sinon impossible d'importer les données.

L'importation des données est bien réalisée dans `gn_synthese.synthese` cependant, il y a parfois des problèmes qui surviennent de manières aléatoires. Sur les 13 fichiers de 10 000 données importés je retrouve 3 cas d'importation différents (voir images ci-dessous) : 

1.  Données du fichier importées dans la synthèse, mais sans peuplement de `gn_synthese.cor_area_synthese` , exemple de l'id 147, ligne 1 (3 fichiers dans ce cas), on peut voir qu'il n'y a pas eu id_source attribué
2.  Données du fichier correctement importées sans problème, exemple de l'id 146, ligne 2 (6 fichiers sont dans ce cas) 
3.  Données du fichier importées dans la synthèse, mais nous n'avons pas trouvé d'erreur en particulier, exemple de l'id 145, ligne 3 (4 fichiers sont dans ce cas)

![image](https://user-images.githubusercontent.com/85483402/172389584-b52702bb-d0cb-4c8c-81a6-20f22ef57976.png)

Le fait que le module d'import place certaine importation en erreur m'inquiète. Je pense qu'il n'a pas pu finir le process d'importation prévu, et je me demande quelles sont les tâches qui n'ont pas pu aboutir. Serait-il possible dans le rapport d'erreur de savoir quelles étapes n'ont pas pu être réalisées ?

Si vous avez un schéma/logigramme qui récapitule l'ensemble des tâches, requêtes, triggers qui sont réalisées lors de l'importation, cela pourrait me permettre de vérifier que l'importation se doit correctement déroulée, mais aussi de vous faire un retour sur des tâches ou des paramètres qui pourrait être bloquant. 

Nous sommes actuellement sur une version de Géonature [2.9.2](https://github.com/PnX-SI/GeoNature/releases/tag/2.9.2)

**Comment by DonovanMaillard** [comment]
Salut Axel, 

Une refonte du module est en cours par Elie et Antoine au Muséum, ce travail a très bien avancé ces dernières semaines / ce dernier mois. Ce type d'erreur sont susceptibles de ne plus se reproduire, le process d'import et les fonctions du backend ayant été reprises dans leur quasi intégralité( pas les mêmes dépendances utilisées etc etc). 

Actuellement ces soucis sont variables en fonction des fichiers et des paramètres. Avec un timeout de plusieurs heures et des fichiers avec peu d'erreurs, j'ai pu importer plus de 200.000 lignes sans soucis d'un seul coup par exemple. 

Pour le logigramme, rien de tel à ma connaissance pour le moment, mais ca pourrait être intéressant de le faire sur les versions après refonte pourquoi pas... comme toujours il faut surtout trouver le volontaire/le temps pour le documenter. Globalement, beaucoup de choses de passent, de manière asynchrone ou non selon les volumes de données, et l'import reste donc un process qui imlplique pas mal de choses au niveau du backend.

**Comment by camillemonchicourt** [comment]
La refonte du module (https://github.com/PnX-SI/gn_module_import/issues/257) a notamment pour vocation de ne plus avoir ces erreurs "aléatoires" qui se produisaient dans la V1, mais aussi de gérer des plus gros volumes de données sereinement.
Le code a été repris de fond en comble pour être allégé, optimisé et amélioré.

Le processus de traitement asynchrone a aussi été complètement revu pour utiliser un mécanisme plus solide avec des services, des workers, des queues, des ressources attribuées.
Tous les imports seront faits en asynchrone désormais peu importe le nombre de données, pour garantir un fonctionnement plus homogène et plus robuste.

Un récapitulatif des évolutions et du fonctionnement du module refondu sera réalisé prochainement dans le ticket dédié.
Et une documentation du fonctionnement est aussi prévue.

**Comment by camillemonchicourt** [comment]
Corrigé avec la v2 du module, plus stable et robuste.
