### ISSUE TITLE
Vers une modale d'infos sur les imports ?

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/gn_module_import#34]
En lien avec #27 et #32 

Dans la synthèse, grace à la t_source notamment, un bouton nous renvoie sur le module de saisie, voie d'entrée de la donnée dans la source. 

Dans le cas d'un import, c'est un peu à part. Et actuellement on ne renvoie vers rien. 

De plus dans l'historique du module d'import, on a actuellement une liste des imports et quelques informations essentielles seulement, avec un bouton qui permettra de télécharger les données d'un import non conformes donc non importées. 

Dans une évolution future potentielle, il me semblerait plus pertinent d'avoir une modale d'info, comme sur les autres modules, propre à chaque import, et renvoyant les informations liées à l'import : format du fichier envoyé, date, nombre de lignes, role(s) impliqués dans l'import, jeu de données... mais aussi nombre de lignes conformes importées, et lien vers l'export des données non importées. Depuis la synthèse, on pourrait ainsi retourner sur la modale d'info de l'import en question pour voir un peu mieux d'où / de quel envoi, provient la donnée. Ca permettrait également d'enrichir et clarifier un peu les infos dans le module d'import, une fois un import terminé.

**Comment by camillemonchicourt** [comment]
Désormais depuis la liste des imports, on a un lien vers le JDD de rattachement, qui lui même comprend maintenant une fiche détail avec récapitulatif des données, leur répartition, les données sensibles, la liste des imports concernés...
On a aussi accès au rapport d'erreur complet de l'import depuis la liste des imports.

**Comment by DonovanMaillard** [comment]
Peut-être à mettre en lien avec #158 pour disposer d'un rapport plus complet qui ne se limite pas aux erreurs (une espèce de "prévisualisation" en plus des erreurs).

**Comment by DonovanMaillard** [comment]
Doublon avec #158 , à voir dans ce cadre si on passe par une modale ou une fenetre dédiée, comme pour les métadonnées (plus cohérent à priori)
