### ISSUE TITLE
IMPORT NIVEAU 2 : échec de l'import du fichier CSV

### ISSUE THREAD

**Issue by mgageo** [PnX-SI/gn_module_import#36]
Bonjour à tous,
J'ai mis en place une instance GeoNature 2.2.1 sur une machine virtuelle en Debian 9.
L'installation s'est déroulée sans problème.
J'essaye maintenant de faire un import de niveau 2 en suivant le guide https://geonature.readthedocs.io/fr/latest/import-level-2.html
Sur le la commande psql, j'ai une erreur
postgres@geonature:/home/marc$ psql -d geonature2db -f sql
psql:sql:1: NOTICE:  la table « testimport » n'existe pas, poursuite du traitement
psql:sql:1: ERREUR:  erreur de syntaxe sur ou près de « ; »
LIGNE 1 : create table gn_imports.testimport ( text);
                                                    ^
REQUÊTE : create table gn_imports.testimport ( text);
CONTEXTE : fonction PL/pgsql gn_imports.load_csv_file(text,text), ligne 26 à EXECUTE
psql:sql:2: ERREUR:  la relation « gn_imports.testimport » n'existe pas
postgres@geonature:/home/marc$

La commande fait aussi référence à un utilisateur geonatuser qui n'existe pas :
postgres@geonature:/home/marc$ psql -c '\du+'
                                                     Liste des rôles
 Nom du rôle |                                    Attributs                                    | Membre de | Description
-------------+---------------------------------------------------------------------------------+-----------+-------------
 geonatadmin |                                                                                 | {}        |
 postgres    | Superutilisateur, Créer un rôle, Créer une base, Réplication, Contournement RLS | {}        |

postgres@geonature:/home/marc$

J'ai oublié d'installer quelque chose ?

Marc

**Comment by DonovanMaillard** [comment]
Bonjour, 

Sauf erreur je vois le -f, vous avez lancé un script directement depuis un fichier.sql ? Il est possible qu'un mauvais copié collé ait laissé un "ALTER TABLE gn_import.testimport OWNER TO geonatuser" ou quelque chose du style. Sachant que cet utilisateur n'existe pas sur votre bdd puisque votre utilisateur créé à l'installation est geonatadmin. 

De plus le ";" qui pose problème pourrait venir soit du script, soit des données qui contiendraient par exemple un ";" dans un commentaire, ce qui fait que postgres a mal compris le fichier et a créé des colonnes sans que ca soit voulu. 

Ps : à basculer sur le dépôt GeoNature

**Comment by mgageo** [comment]
Merci pour rapide réponse.

En mode ligne de commande, voici ce que j'obtiens
postgres@geonature:/home/marc$ psql -d geonature2db
psql (9.6.15)
Saisissez « help » pour l'aide.

geonature2db=# SELECT gn_imports.load_csv_file('/home/marc/imports/observations.csv', 'gn_imports.testimport');
NOTICE:  la table « testimport » n'existe pas, poursuite du traitement
ERREUR:  erreur de syntaxe sur ou près de « ; »
LIGNE 1 : create table gn_imports.testimport ( text);
                                                    ^
REQUÊTE : create table gn_imports.testimport ( text);
CONTEXTE : fonction PL/pgsql gn_imports.load_csv_file(text,text), ligne 26 à EXECUTE
geonature2db=#

Le code source de la fonction
geonature2db=> SELECT prosrc FROM pg_proc WHERE proname = 'load_csv_file';
                                                                       prosrc
----------------------------------------------------------------------------------------------------------------------------------------------------
                                                                                                                                                   +
 --This function create a table and her structure according to the CSV structure and the passed name.                                              +
 --CSV content is loaded in.                                                                                                                       +
 --Then, the function tries to define the type of columns according to the content.                                                                +
 --You must check and adapt result.                                                                                                                +
 --                                                                                                                                                +
 --USAGE (due to 'copy' function usage, use it with a superuser only).                                                                             +
 --SELECT gn_imports.load_csv_file('/path/to/file.csv', 'targetschema.targettable');                                                               +
 DECLARE                                                                                                                                           +
     col text; -- variable to keep the column name at each iteration                                                                               +
     sname text; --destination schema name                                                                                                         +
     tname text; --destination table name                                                                                                          +
 BEGIN                                                                                                                                             +
     create temp table import (line text) on commit drop;                                                                                          +
     --import all csv content                                                                                                                      +
     EXECUTE format('copy import from %L', csv_file);                                                                                              +
     -- if not blank, change the csv_temp_table name to the name given as parameter                                                                +
     IF length(target_table) > 0 THEN                                                                                                              +
         --split schema.table to 2 strings                                                                                                         +
         SELECT split_part(target_table, '.', 1) into sname;                                                                                       +
         SELECT split_part(target_table, '.', 2) into tname;                                                                                       +
         --if a schema name is given                                                                                                               +
         IF(tname IS NOT NULL) THEN                                                                                                                +
             --drop if exists and create table with first line as columns name in given schema (before point in target_table string)               +
             EXECUTE format('DROP TABLE IF EXISTS %I.%I', sname, tname);                                                                           +
             EXECUTE format('create table %I.%I (%s);',                                                                                            +
                 sname, tname, concat(replace(line, ';', ' text, '), ' text'))                                                                     +
             from import limit 1;                                                                                                                  +
             -- load data in target table                                                                                                          +
             EXECUTE format('copy %I.%I from %L WITH DELIMITER '';'' quote ''"'' csv header', sname, tname, csv_file);                             +
         --if no schema is given working with public schema                                                                                        +
         ELSE                                                                                                                                      +
             --drop if exists and create table with first line as columns name in public schema                                                    +
             EXECUTE format('DROP TABLE IF EXISTS %I', target_table);                                                                              +
             EXECUTE format('create table %I (%s);',                                                                                               +
                 target_table, concat(replace(line, ';', ' text, '), ' text'))                                                                     +
             from import limit 1;                                                                                                                  +
             -- load data in target table                                                                                                          +
             EXECUTE format('copy %I from %L WITH DELIMITER '';'' quote ''"'' csv ', target_table, csv_file);                                      +
         END IF;                                                                                                                                   +
         --try to change convert numeric and date columns type. If error throw, do nothing, continue and keep 'text' type.                         +
         FOR col IN EXECUTE format('SELECT column_name FROM information_schema.columns WHERE table_schema  = %L AND table_name = %L', sname, tname)+
         LOOP                                                                                                                                      +
             BEGIN                                                                                                                                 +
                 EXECUTE format('ALTER TABLE %I.%I ALTER COLUMN %s TYPE integer USING %s::integer', sname, tname, col, col);                       +
                 EXCEPTION WHEN OTHERS THEN                                                                                                        +
                     BEGIN                                                                                                                         +
                         EXECUTE format('ALTER TABLE %I.%I ALTER COLUMN %s TYPE real USING %s::real', sname, tname, col, col);                     +
                         EXCEPTION WHEN OTHERS THEN                                                                                                +
                             BEGIN                                                                                                                 +
                                 EXECUTE format('ALTER TABLE %I.%I ALTER COLUMN %s TYPE date USING %s::date', sname, tname, col, col);             +
                                 EXCEPTION WHEN OTHERS THEN -- keep looping                                                                        +
                             END;                                                                                                                  +
                     END;                                                                                                                          +
             END;                                                                                                                                  +
         END LOOP;                                                                                                                                 +
     END IF;                                                                                                                                       +
     RETURN format('CREATE TABLE %I.%I FROM %L', sname, tname, csv_file);                                                                          +
 END
(1 ligne)

geonature2db=>

**Comment by mgageo** [comment]
C'est moi qui est fait une erreur : je n'ai pas téléchargé le fichier csv mais la page html github de ce fichier.
En téléchargeant https://raw.githubusercontent.com/PnX-SI/Ressources-techniques/master/GeoNature/V2/import-avance/observations.csv l'import se passe bien.

J'ai ensuite remplacé geonatuser par geonatadmin.

Il me reste à poursuivre ...

Merci pour votre aide
Marc
