### ISSUE TITLE
Soucis à l'installation sur la version 2.2.1

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/gn_module_import#37]
J'ai testé l'installation (en inversant les deux lignes que @JulienCorny avait indiqué) . Un petit problème qui sera à régler : 

'npm WARN gn_module_import@1.0.0 No repository field.
up to date in 0.195s
No module named 'toolz'
Dask dataframe requirements are not installed.
Please either conda or pip install as follows:
  conda install dask                     # either conda install
  pip install dask[dataframe] --upgrade  # or pip install

Error while installing GN module 'IMPORT'.The process returned:
	Module IMPORT
                    File /home/geonatureadmin/gn_module_import-navigation/backend/blueprint.py must have a variable call :
                        blueprint instance of Blueprint'

En installant le pré-requis nécessaire manuellement, l'installation se lance et avance... jusqu'à retrouver le message : Module IMPORT
                    File /home/geonatureadmin/gn_module_import-navigation/backend/blueprint.py must have a variable call :
                        blueprint instance of Blueprint'. 

J'ai également essayé en refaisant manuellement la PR de JoelClems(766) . Même résultat.

**Comment by DonovanMaillard** [comment]
Seule l'installation des pré-requis est problématique et toi, pour l'instant, se faire manuellement. 

Le soucis semble provenir non pas du module imports, mais de la fonction create_gn_module, qui a deja des corrections en cours mais qui ne semblent pas régler totalment le soucis. 

Installation OK une fois les pré-requis installés donc.

**Comment by camillemonchicourt** [comment]
Tu as fait quelles commandes pour installer le module sur GN 2.2 du coup ?

**Comment by DonovanMaillard** [comment]
Noté dans la doc du module :)
[Ici](https://github.com/PnX-SI/gn_module_import/blob/develop/README.rst)

Sur ce point, j'attends la prochaine release de GN , une correction a été faite sur la commande create_gn_module ca n'avait pas suffit lors de mes tests. 
Dans tous les cas, le soucis semble provenir de la commande d'install du module qui ne gère pas les pré-requis, et pas du module d'imports en lui-même (pour ça que j'ai cloturé le ticket ;) ).
