### ISSUE TITLE
Retours sur la version actuelle

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/gn_module_import#38]
Les tests de la version actuelle sont en cours ("pré-release" = branche navigation). 

Serveur de test : https://geonature.demos.natural-solutions.eu/geonature/#/

### **Installation et configuration**
à tester sur la 2.0.1 (version sur laquelle ont été faits les développement du module)

Sur la 2.2.1 : installation OK dès qu'on installe les pré-requis manuellement (#37). En revanche le module, bien qu'installé, visible en interface et en place coté BDD, ne fonctionne pas ! 
Il semble qu'au début de la manipulation, le module ne crée par d'id_import, bloquant tout le reste (erreur object / object). Une autre erreur dans les logs, qui explique possiblement la première, est la suivante : FileNotFoundError: [Errno 2] No such file or directory: '/home/geonatureadmin/geonature/external_modules//imports/upload/synthese_observations_2019-11-18T14_44_02.787Z.csv'". Il y a un / en trop dans le chemin du fichier recherché. 

### **Import des données**
**Testé et fonctionnel**
- Bonne détection des erreurs de dates invalides (34 du mois. Date fin avant la date début)
- Bonne détection du mauvais SRID (renseigné wgs84 au lieu de lambert, détecté)
- UUID invalides ou déjà dans la synthèse bien détectés
- Génération des uuid ok quand manquants, sans écraser les uuid présents dans la source
- Cumul des dates invalides + uuid invalide
- Altitudes min et max controlés (min supérieur à max détecté)
- Export des données invalides ok
- Import des données valides ok

**Corrections et améliorations**
- Erreur (connue) sur la sélection des mappings : il faudra qu'un même mapping comporte à la fois la phase de mapping des champs + la phase de mapping de nomenclatures
- Suite à la prévisualisation, mettre en place une pop-up résumant les actions effectuées (données importées, export des données invalides, lien vers la synthèse -> #32 ). A défaut, remettre le bouton d'erreurs, le bouton de téléchargement des données invalides et préciser le nombre de données à importer directement sur l'étape de prévisualisation.
- Sur la page d'historique, mettre la date d'import lorsque l'import est terminé. Et laisser le bouton 'terminer l'import' quand celui ci est resté en cours. A coté de cette date, mettre une icone plus petite pour récupérer les données invalides.
- Amélioration : réexporter le csv invalide avec le même séparateur que le fichier importé (habitudes de l'utilisateur)
- Erreur sur la fonction "générer les altitudes" : si je fais un mapping en cochant la fonction, que j'avance dans l'import, et que je reviens en arrière en décochant cette fonction, la prévisualisation comporte toujours les altitudes calculées. Si les altitudes sont inscrites en base dans la table d'import, il semble probable que le calcul des altitudes effectué la première fois écrase les vides dans la table d'import et que l'opération devienne irréversible, de même que pour la génération d'uuid qui a la même mécanique. Dans ce cas, il faudrait déclencher ces fonctions au moment de la prévisualisation, et les écrire en base directement lors de l'import.
- Si je reviens en arrière, modifie un mapping et repars à la prévisualisation, le décompte de lignes au total s'incrémente systématiquement du nombre de lignes du fichier (mais les données n'apparaissent qu'une fois). Pour un fichier de n données, si je recule et reviens 4 fois à la prévisualisation, le compteur affiche donc 4n données. 
- Moins prioritaire : dans la BDD et l'appli, remplacer le préfixe bib par dict

**Fonctionnalités restant à développer**
- Import de géométries à partir d'un champ WKT
- Import de fichiers au format geojson
- Poursuivre un import en cours, laissant la possibilité de modifier les données coté BDD si nécessaire pour l'administrateur de la base

**Comment by JulienCorny** [comment]
Merci Donovan pour tous ces retours. Comme convenu, je vais créer une issue pour chaque point à corriger/améliorer

**Comment by DonovanMaillard** [comment]
Points traités un a un par Julien dans des issues spécifiques.
