### ISSUE TITLE
Test module / message d’erreur

### ISSUE THREAD

**Issue by MathieuLagarde** [PnX-SI/gn_module_import#39]
Bonjour,
Voici un retour suite au test du module d’import sur un tableur de données « brutes » (déjà homogénéisé, mais non conforme au standard de données de la synthèse).

- Première étape : « sélection du jeu de données »

Il faut donc choisir un JDD parmi la liste des JDD déjà créés (je présume) sur GéoNature.
Question : Peut-on envisager que le fichier d’import comporte déjà un champ contenant l’identifiant (UUID) des JDD correspondants générés via l’application des métadonnées de l’INPN ?

- Identifiant SINP (UUID)

Les caractères alphabétiques de mes UUID étaient en majuscule, ce qui est considéré comme une erreur.

- A la fin du mapping des contenus, j’obtiens ce message d’erreur en cliquant sur « suivant » :

INTERNAL SERVER ERROR during content mapping (user values to id_types

Du coup, pas moyen d’aller plus loin dans cette phase de test.

**Comment by DonovanMaillard** [comment]
Salut, 

Sur l'import d'un jeu de données, certaines choses sont prêtes en python, j'avais fait un code (pas très propre), que théo a du utiliser et nettoyer un peu récemment. Des choses sont déjà bien avancées sur ce point, mais il faudra voir si on l'intègre ou non en interface. Se posera aussi la question de le mettre dans le module métadonnées, ou dans le module d'import. Ca reste donc une évolution à prévoir pour plus tard!

En revanche, on est resté sur le principe 1 import = 1 jdd. On ne pourra donc pas importer un fichier et renseigner dans le mapping le jdd à rattacher. Il faudra diviser les données d'origine avec 1 fichier par jdd. 

Sinon merci pour l'internal server error. Je ferai des tests à nouveau mais il est possible que ça soit lié au problème de choix du mapping, un problème que julien a identifié en installant le module dernièrement. Peux-tu nous détailler ce que tu as fait (mapping choisi, nommé ou non, nouveau ou non, même nom sélectionné sur les 2 etapes de mapping?) afin qu'on reproduise? 

merci!

**Comment by camillemonchicourt** [comment]
Le script Python en question qui permet de récupérer les infos sur des JDD à partir de leur UUID en interrogeant l'API de l'INPN : https://github.com/PnX-SI/GeoNature/tree/master/data/scripts/import_mtd

**Comment by MathieuLagarde** [comment]
> 
> 
> Peux-tu nous détailler ce que tu as fait (mapping choisi, nommé ou non, nouveau ou non, même nom sélectionné sur les 2 etapes de mapping?) afin qu'on reproduise?

Salut,
Tant pour le Mapping des champs que pour le Mapping des contenus, j'ai créé un Nouveau mapping, chacun avec un nom différent.
