### ISSUE TITLE
[IMPORT] refonte graphique du rapport d'import

### ISSUE THREAD

**Issue by jupierrot** [PnX-SI/gn_module_import#403]
Bonjour à tous,

Suite à l'ajout dans la version 2.0 d'un rapport d'import, nous (Patrinat) souhaitons en revoir le graphisme car ce dernier ressemble trop aux pages de métadonnées.
Nous proposons donc la maquette suivante qui reprend l'ensemble des informations présentes dans le rapport mais avec un visuel plus proche de la page récapitulatif avant import.

Les modifications sont :

- Ajouter un bloc titre au rapport d'import comportant la mention "Rapport d'import", l'id de l'import et son statut (en cours, terminé, en erreur)
- Regrouper les champs dans des blocs se suivant sur le modèle du récapitulatif avant import. Les blocs à créer sont :
    Description de l'import
    Correspondances
    Données invalides
    Données importées
- Le bloc données importées ne sera visible QUE pour les imports terminés.
- les icônes pour les blocs seront identiques à ceux de la page récapitulatif avant import

![rapport_import_termine](https://user-images.githubusercontent.com/99485453/203527882-90a81f7d-0394-4952-8375-42e81119b6e1.png)
![rapport_import_enerreur](https://user-images.githubusercontent.com/99485453/203527895-2d4f59ad-ccca-489a-956e-0dcdd98bde11.png)
![rapport_import_encours](https://user-images.githubusercontent.com/99485453/203527907-d8bda0d1-f95f-451e-ba54-76ea7c6680c8.png)

**Comment by DonovanMaillard** [comment]
Bonjour, 

Un seul petit détail ; le nombre d'observations importées est indiqué dans le 1er bloc, et le nombre de taxons en pied de rapport. 

J'aurais tendance à mettre les deux informations au même niveau, plutôt en haut du rapport (avec ou sans les icônes). 

On a privilégié l'homogénéité au sein de l'outil lors de la mise en place de ces rapports, mais si ça pose un soucis, ok pour une maquette différente, 

Donovan

**Comment by TheoLechemia** [comment]
Ok pour la refonte. Petit point de vigilance : utiliser les composant "material" pour garder l'homogenéité de l'UX

**Comment by jupierrot** [comment]
Si on descend dans le bloc "Données importées" le champs "observations importées", alors l'information ne sera pas visible pour tout import non terminé.
La valeur serait de toute façon à 0 et le statut de l'import indiquerai "en cours".
Ce serait OK pour toi @DonovanMaillard ?

**Comment by DonovanMaillard** [comment]
Si ca convient à tout le monde oui, ça me semblerait plus logique. En revanche, peut être faire apparaître plus clairement (badge ou autre ) le statut en cours de limport dans ce cas.

**Comment by camillemonchicourt** [comment]
Petit détail sur le sujet, en chipotant un peu.
Mais en effet, selon moi, c'était plus pertinent d'afficher le "nombre de données importées/nombre de données total du fichier source" dans la description au début du rapport.
Car c'est une info centrale et essentielle.
Et car c'était bien intéressant aussi de l'avoir aussi pour les imports non terminés, pour savoir le nombre de données totales (0/458).

Donc je préférai le remettre dans le bloc DESCRIPTION.
Et si il faut mettre le nombre de taxons importés avec (ce qui me semble pertinent), le mettre aussi dans le bloc Description, sous le nombre de données totales.

**Comment by DonovanMaillard** [comment]
en haut, en bas, comme ça vous semble le mieux (moi je préférais en haut mais bien visible, pas perdu dans les autres infos de la description car c'est une info centrale). L'essentiel est que ces deux infos soient au même endroit.

**Comment by jupierrot** [comment]
OK pour les déplacer les champs dans le bloc description

**Comment by antoinececchimnhn** [comment]
Fait !

**Comment by camillemonchicourt** [comment]
Intégré dans la version 2.0.3
