### ISSUE TITLE
Erreur installation due à table supprimée

### ISSUE THREAD

**Issue by MoulinZ** [PnX-SI/gn_module_import#409]
Salut,
J'ai une erreur dans mon upgrade du module import due à une table supprimée à la main dans la bdd (table gn_imports.i_export_opportunistes_24) :
```
    raise NoReferenceError(f"No import linked with archive table: {archive_table}")
sqlalchemy.exc.NoReferenceError: No import linked with archive table: export_opportunistes_24

```

C'est la ligne suivante du upgrade qui plante :
```
INFO  [alembic.runtime.migration] Running upgrade 6f60b0b934b1 -> 0ff8fc0b4233, remove_archive_schema
```

J'imagine que c'est un problème d'état de la bdd connu par alembic ? le genre de chose que je reglerai avec un `flask db stamp head` sur mes app locales mais je ne sais pas si ça marche exactement pareil ici, je veux pas faire de bêtise.

 Merci pour le retour !

**Comment by bouttier** [comment]
Comme tu n’as plus d’import 24, le script ne sait pas où sauvegarder les données de la table ``gn_import_archives.export_opportunistes_24``  et préfère s’arrêter plutôt que de supprimer la table. Tu peux la supprimer manuellement si tu ne veux plus ses données.

**Comment by MoulinZ** [comment]
ah merci, je cherchais la table dans le schema gn_imports...
