### ISSUE TITLE
Envoyer une notification à la fin d’un import

### ISSUE THREAD

**Issue by bouttier** [PnX-SI/gn_module_import#414]
Cette fonctionnalité existait déjà en v1.
Elle est très simple à remettre en v2 grâce au nouveau mécanisme de notification apparu en 2.11.

**Comment by camillemonchicourt** [comment]
Avec le développement de cette fonctionnalité, si les notifications sont activées au niveau de GeoNature, les utilisateurs peuvent activer les notifications sur leurs imports terminés : 

![image](https://user-images.githubusercontent.com/4418840/213304384-bafcf487-12e2-4037-8e70-b754f6edd5ac.png)

Ceux-ci peuvent être notifiés directement dans l'application : 

![image](https://user-images.githubusercontent.com/4418840/213301304-ca6cf117-607f-4122-9594-9bfb81b199fb.png)

Quand on clique sur une notification d'import terminé, on accède directement à son rapport d'import.

Ils peuvent aussi être notifié par email :

![image](https://user-images.githubusercontent.com/4418840/213303749-9af9cfb3-972a-465d-b81b-6cb55cc2488f.png)

Les templates des messages de notification sont modifiables directement dans le module ADMIN : 

![image](https://user-images.githubusercontent.com/4418840/213305305-6ea2de00-0a60-4a30-a03a-5debcd22c127.png)

La version 2.12 de GeoNature permettra de définir des notifications par défaut, pour ne pas que chacun est à s'abonner explicitement à chaque type de notifications, mais qu'ils puissent plutôt s'en désabonner si ils le souhaitent (https://github.com/PnX-SI/gn_module_import/issues/420).

-----------------------------

Un point auquel on n'a pas pensé est que pas tous les utilisateurs d'une instance de GeoNature qui dispose du module IMPORT ont accès à celui-ci.
Pour ceux qui n'ont pas accès au module, c'est un peu bizarre de leur proposer de s'abonner aux notifications "Import en synthèse terminé"...

Idéalement il faudrait faire évoluer le système de notifications de GeoNature, pour ne pouvoir s'abonner aux notifications liées à un module, que si on a accès à celui-ci.

**Comment by camillemonchicourt** [comment]
Le système de notification lors d'un import terminé a été intégré dans le version 2.1.0 du module.
Et une notification par défaut a été intégrée pour cette règle de notification.
Ainsi par défaut quand on installe ou dispose du module IMPORT, tous les utilisateurs reçoivent une notification par email et dans l'application quand leur import est terminé.
Ils peuvent se désabonner de cette notification ou ne garder que les notifications par email ou dans l’application si ils le souhaitent.

Pour le fait d'avoir accès aux notifications seulement si on des droits d'accès au module IMPORT, c'est une évolution plus globale à voir au niveau de GeoNature - https://github.com/PnX-SI/GeoNature/issues/2428
