### ISSUE TITLE
Erreur sur la sélection des mappings

### ISSUE THREAD

**Issue by JulienCorny** [PnX-SI/gn_module_import#42]
Commentaire suite aux tests : 
Erreur (connue) sur la sélection des mappings : il faudra qu'un même mapping comporte à la fois la phase de mapping des champs + la phase de mapping de nomenclatures

@DonovanMaillard , pourrais-tu détailler plus ce commentaire, je ne suis pas sûr de comprendre. Tu veux dire que lors d'un import tu aimerais qu'on puisse regrouper le mapping de champs et le mapping de nomenclature sous un même nom de mapping ?

**Comment by DonovanMaillard** [comment]
Discuté avec Julien. Plus compliqué à traiter, pour un bénéfice discutable. 

Les mappings de champs et de contenus sont donc traités indépendemment l'un de l'autre. On crée donc à la fois un mapping de champs, à la fois un mapping de contenu, qui ne constituent pas un seul ensemble de correspondances (au lieu d'avoir un mapping unique qui incluait toutes les correspondances de champs et de vocabulaire comme imaginé).

**Comment by camillemonchicourt** [comment]
Tu parles au niveau interface ou au niveau stockage du mapping dans la BDD ?

**Comment by DonovanMaillard** [comment]
En interface On crée un mapping sur les correspondances de champs. Et indépendamment du premier, on crée un mapping pour les vocabulaires. 

Ca peut présenter autant davantages que d'inconvénients à priori. Dans la mesure ou un vocabulaire SINP décodé, ou les CD nomenclatures par exemples, peuvent etre sélectionnés quelque soit le format des champs transmis. Mais ca obligé à créer, ou sélectionner, un mapping à chaque étape. 

Coté BDD je vais aller voir ce qui se passe, j'ai encore assez peu navigué dans la BDD que j'ai réussi à installer correctement il n'y a que quelques heures ;)

**Comment by DonovanMaillard** [comment]
Voir si on souhaite conserver ce fonctionnement ou non, qui a ses + et ses -, mais ne colle pas à ce que nous avions en tête et pourrait ne pas convenir aux attentes du mnhn à terme. 

En théorie, nous avions planifié un seul mapping, qui comprenait les 2 étapes (on ne créait et sélectionnait qu'un mapping, qui "packageait" le tout pour un format de données correspondant à tel ou tel partenaire). A rediscuter

**Comment by bouttier** [comment]
Cela me semble apporter une rigidité, et pas forcément simple à implémenter, pour un bénéfice relativement léger. Il reste possible de créer un mapping de champs et un mapping de nomenclature qui portent le même nom (e.g. « Modèle <structure> »).

**Comment by DonovanMaillard** [comment]
Oui, ce ticket aurait du être fermé. Ca date du développements originaux du module et le fonctionnement peut rester l'actuel sur 2 mappings distincts, éventuellement nommés pareil. Je ferme ;)
