### ISSUE TITLE
Notification par défaut en fin d’import

### ISSUE THREAD

**Issue by bouttier** [PnX-SI/gn_module_import#420]

**Comment by bouttier** [comment]
#419 rajoute la possibilité de souscrire à une notification lors qu’un import se termine.
https://github.com/PnX-SI/GeoNature/pull/2267 rajoute la possibilité à GeoNature de définir des notifications par défaut (sera releasé dans GeoNature 2.12)
Il faudrait que le module d’import configure un abonnement par défaut aux notifications de fin d’import.
Note : attendre que la 2.12 sorte afin de faire cela !

**Comment by camillemonchicourt** [comment]
Fait dans la PR https://github.com/PnX-SI/gn_module_import/pull/440 et intégré dans la version 2.1.0 du module.
