### ISSUE TITLE
Limiter la détection de l’encodage à maximum 1000 lignes / 2 secondes

### ISSUE THREAD

**Issue by bouttier** [PnX-SI/gn_module_import#422]
La détection de l’encodage du fichier source peut être lent, en particulier quand le fichier source est très long.
Une limitation à par exemple 1000 lignes permettrait d’éviter cette lenteur excessive.
Une autre solution pourrait être de contraindre la détection de l’encodage temporellement (par exemple, 2 secondes maximum).
cf ``detect_encoding`` dans ``utils.py``

**Comment by bouttier** [comment]
Lenteur de l’étape de détection de l’encodage à confirmer avant de se lancer dans ce dev.

**Comment by bouttier** [comment]
Problème de perf confirmé par #427

**Comment by bouttier** [comment]
Fait dans b4a0466b0ee020cb37858fa4fd43a85155285ee6

**Comment by camillemonchicourt** [comment]
Intégré dans la 2.0.5
