### ISSUE TITLE
Rapport d'erreur(s), type COUNT_MIN_SUP_COUNT_MAX

### ISSUE THREAD

**Issue by cen-cgeier** [PnX-SI/gn_module_import#434]
GN version : 2.11.2
IMPORT version : 2.0.5

Bonjour à tous, 
En important diverses données, j'obtiens un rapport d'erreur que j'ai du mal à saisir. J'ai tenté d'entrer dans le code pour tenter un débug et une PR par la suite mais je ne parviens pas à trouver la source du problème. Un petit coup de pouce serait le bienvenu.

**Description :** 
- Type d'erreur concerné : COUNT_MIN_SUP_COUNT_MAX
- Description de l'erreur : Incohérence entre les champs dénombrement. La valeur de `denombrement_min` est supérieure à celle de `denombrement_max` ou la valeur de `denombrement_max` est inférieur à `denombrement_min`.

![image](https://user-images.githubusercontent.com/96542451/221539552-a261113c-4d3f-4e16-afd9-9db2f375d0ef.png)

Pourtant, lorsque je consulte mon document source, mes données exportées et mon mapping des champs, les effectif sont bien mappés comme ils le doivent et les `effectif` sont bien inférieurs aux `effectif_max`.
Mon CSV source est créé par un script python où les colones d'effectifs sont formatés en `string` avant écriture. J'effectue cette manip afin que les effectifs s'écrivent en entier et non en flottant (car j'ai des données sans effectifs définis) qui est un type reconnu comme invalide lors du process de validation.
J'ai également tenté de mettre un effectif par défaut et de formater les colones d'effectifs en `integer` avant écriture.
J'obtiens le même résultat.

**Capture du mapping :** 
![image](https://user-images.githubusercontent.com/96542451/221540041-2f19c008-3c38-4206-8bd7-3d02d287666f.png)
**Capture des données invalides :** 
![image](https://user-images.githubusercontent.com/96542451/221540884-1abaa22b-43f4-4ed3-bb88-399602396e1a.png)

Avez-vous une idée d'où peux se situer mon problème ? 
Je ne parviens pas à en comprendre l'origine.. 
D'avance merci

**Comment by gildeluermoz** [comment]
Bonjour
Une piste a évaluer sur l'ensemble des données :
si on considère une comparaison textuelle, les valeurs du champ effectif sont effectivement supérieure à celle du champ effectif_max
En type text 101 est supérieur à 1000.

**Comment by gildeluermoz** [comment]
Pour tester les données sources, une autre piste
Ouvrir le csv dans libre office
Ajouter une colonne
Dans cette colonne, comparer les 2 valeurs avec QQ chose du genre colmax >= colmin
Ça devrait renvoyer vrai ou faux.
S'il y a 152 faux correspondant aux lignes Invalides, c'est probablement que la comparaison se fait sur du string et pas sur de l'integer. 
Et donc qu'il y a un soucis de typage sur les colonnes du fichier source

**Comment by bouttier** [comment]
Bonjour,
Merci Gil pour la piste qui était bien la source de l’erreur.
Les colonnes étaient bien converties en entier, mais des erreurs dans le code de contrôle min / max amenées à utiliser les colonnes originales textuelles.
Correction : https://github.com/PnX-SI/gn_module_import/pull/436 (intégrant une comparaison de 20 et 5 dans les tests)

**Comment by cen-cgeier** [comment]
Merci pour le débug ! 
Désolé, de ne pas avoir pu répondre à vos messages.
J'ai reporté les corrections #436 d' @bouttier dans mon module et je lai ré-installé mais j'obtiens toujours la même erreur.
Les données sources d'effectifs que j'ai utilisé sont des entiers dans mon test.
Il doit y avoir une subtilité que je n'ai pas, j'attendrais la sortie de la release 2.0.6 
A bientôt

**Comment by cen-cgeier** [comment]
Bonjour et merci pour cette assistance.
Désolé de ne pas avoir pu répondre à vos précédents messages. J'ai installé la release 2.0.6 mais j'obtiens encore la même erreur en sortie de validation.
Les effectifs du fichier source que j'ai utilisé pour ce test sont des entiers. 

Dans la table `gn_imports.t_imports_synthese`, les données reconnues comme posant problème sont intégrées dans les colonnes `src_count_min` `src_count_max` (type varchar) et ne figure pas dans les colonnes `count_min` `count_max` (type Integer).
Il semble que peu import la typologie d'entrée, les effectifs subissent une comparaison textuelle lors du check.

**Comment by bouttier** [comment]
Bonjour,
J’ai pu reproduire le bug en 2.0.5, et j’ai pu confirmer qu’il est résolu en 2.0.6.
Pouvez-vous relancer le worker Celery en charge des contrôles ?
```
sudo systemctl restart geonature-worker
```
Je suspecte que celui-ci tourne encore avec le code du module d’import 2.0.5 sans la correction.

**Comment by cen-cgeier** [comment]
Bonjour,
Je crois que j'ai depuis un peu cassé la machine d'IMPORT en tentant de trouver la source de mon problème...
Actuellement, j'ai un import en cours de validation qui est coincé et semble tourner dans le vide..
Je ne parviens pas à de forcer l'arrêt du contrôle des données.
![image](https://user-images.githubusercontent.com/96542451/221860895-dff14966-8499-43e2-b6ac-1d935a2f9a85.png)

J'ai tenté une ré-installation du module, suivi des commandes `sudo systemctl restart geonature` `sudo systemctl restart geonature-worker` mais rien n'y fait.

**Comment by cen-cgeier** [comment]
Je viens d'y parvenir en réalisant les manip suivantes : 
- `sudo systemctl stop geonature-worker`
- suppression de l'import en cours dans le module
- `sudo systemctl start geonature-worker`

Ne faudrait-il pas ajouter un stop du geonature-worker aux commandes d'annulation et suppression de l'import ?

**Comment by bouttier** [comment]
Le redémarrage du worker lors de l’annulation ou la suppression d’un import n’est pas nécessaire.

Il est probable que vos manipulations de réinstallation ait amené le worker à oublier de traiter votre import en cours ; la situation peut se résoudre en reprenant l’import à l’étape précédente (correspondance des nomenclatures – il peut falloir modifier les correspondances puis remettre les correspondances d’origines dans l’unique but de forcer la revalidation) puis relancer les contrôles du fichier.

**Comment by cen-cgeier** [comment]
J'ai essayé cette manip, elle ne semble pas fonctionner dans mon cas. Cela fini par me renvoyer un `HttpErrorResponse`
![image](https://user-images.githubusercontent.com/96542451/221865345-ba1fe023-ce1f-4eed-a473-79e08869db26.png)

**Comment by cen-cgeier** [comment]
J'ai tenté un autre import test avec des écarts entre les effectifs min et max, tout c'est bien passé !

En revanche j'ai toujours ce problème de supprimer un import dont la validation a été initié.. Souhaitez-vous que j'ouvre un autre ticket ?
Actuellement, l'import en question n'a plus de statut `Validation en cours`. Je peux retourner sur les différentes étapes de l'import mais dès lors que je clique sur `Suivant`, j'obtiens l'erreur `502 Proxy Error`.

**Comment by bouttier** [comment]
Quel est l’ordre de grandeur du nombre d’observations de cet import ?
Une erreur 502 correspond à un temps de traitement de la requête excessif. Un problème connu est, lors d’une reprise d’un import existant, un « nettoyage » des données de manière peu efficace, partiellement résolu dans la version develop du module par https://github.com/PnX-SI/gn_module_import/commit/df1fc211acba5795fb2571fabc4639f58f85684d

**Comment by cen-cgeier** [comment]
l'import posant problème contient 50000 observations ^^'

**Comment by cen-cgeier** [comment]
Un grand MERCI pour l'assistance Élie
