### ISSUE TITLE
Rajouter un contrôle ST_IsValid

### ISSUE THREAD

**Issue by bouttier** [PnX-SI/gn_module_import#438]
Une géométrie incorrecte peut amener à faire planter le trigger de peuplement de la table ``cor_area_synthese`` lors de l’import dans la Synthèse :
```
INSERT INTO gn_synthese.cor_area_synthese […] JOIN ref_geo.l_areas a ON public.ST_INTERSECTS(updated_rows.the_geom_local, a.geom)
```
```
(psycopg2.errors.InternalError_) GEOSIntersects: TopologyException: side location conflict at […]
```
Cette erreur peut être à priori empêchée en vérifiant préalablement la validité des géométries ce qui peut être fait au moyen de la fonction ``ST_IsValid``.

**Comment by DonovanMaillard** [comment]
A voir si on peut pas ajouter st_makevalid qui permet dans certains cas de corriger les géométries invalides ?

**Comment by gildeluermoz** [comment]
Pour avoir éventuellement des infos sur l'invalidité, il existe aussi
https://postgis.net/docs/ST_IsValidReason.html

**Comment by camillemonchicourt** [comment]
Contrôle ré-implémenté dans la version 2.2.0.
