### ISSUE TITLE
Erreur sur la fonction "générer les altitudes" et "générer les uuid"

### ISSUE THREAD

**Issue by JulienCorny** [PnX-SI/gn_module_import#44]
commentaire de @DonovanMaillard  lors du test sur le serveur de démo :
"si je fais un mapping en cochant la fonction, que j'avance dans l'import, et que je reviens en arrière en décochant cette fonction, la prévisualisation comporte toujours les altitudes calculées. Si les altitudes sont inscrites en base dans la table d'import, il semble probable que le calcul des altitudes effectué la première fois écrase les vides dans la table d'import et que l'opération devienne irréversible, de même que pour la génération d'uuid qui a la même mécanique. Dans ce cas, il faudrait déclencher ces fonctions au moment de la prévisualisation, et les écrire en base directement lors de l'import."

**Comment by JulienCorny** [comment]
C'est corrigé : les altitudes et les uuid sont générés dans tous les cas dans une nouvelle colonne (avant ils complétaient les données manquantes directement à l'intérieur de la colonne des altitudes ou uuid indiquée par l'utilisateur). Ce qui permet lors du processus de revenir en arrière et de décocher 'générer les altitudes' ou 'générer les uuid' sans garder les valeurs générées précédemment.

**Comment by DonovanMaillard** [comment]
Corrigé
