### ISSUE TITLE
[Génération UUID] UUID non générés lorsque champ masqué bien que DEFAULT_GENERATE_MISSING_UUID

### ISSUE THREAD

**Issue by VincentCauchois** [PnX-SI/gn_module_import#447]
Pr: https://github.com/PnX-SI/gn_module_import/pull/463

## **Versions**

Sont concernées au moins ces version du module IMPORTS : 
- 2.0.6 : https://github.com/PnX-SI/gn_module_import/tree/2.0.6
- 2.1.0 : https://github.com/PnX-SI/gn_module_import/tree/2.1.0

## **Description du bug**

Lorsqu'on a la génération des UUID SINP manquants par défaut activé ; via le paramètre DEFAULT_GENERATE_MISSING_UUID défini à `True` comme c'est le cas par défaut (https://github.com/PnX-SI/gn_module_import/blob/2.1.0/backend/gn_module_import/conf_schema_toml.py#L134), mais qu'on désactive l'affichage du champ "Générer les identifiants SINP manquants" avec coche ; à l'étape "Correspondance des champs" d'un import ; alors les lignes importées à partir d'un fichier source pour lequel on ne mappe pas de colonne avec le champ "Identifiant SINP (uuid)" ; typiquement quand il n'y pas de colonne dédiée dans le fichier source ; se retrouvent sans UUID une fois insérées dans la synthèse.  

## **Comportement attendu**

On devrait avoir une génération effective des UUID SINP dans tous les cas, lorsqu'est activé la génération des UUID SINP manquants, et donc également dans un cas où la colonne n'est pas mappée.

Lorsque la colonne n'est pas mappé, mais que le champ "Générer les identifiants sinp manquants" est affiché et coché, alors les UUID sont bien générés.

## **Comment reproduire**

1. Désactiver l'affichage du champ "Générer les identifiants SINP manquants" : en passant, dans la table `gn_imports.bib_fields`, la valeur du champ `display` à `False` pour la ligne avec `name_field=unique_id_sinp_generate`.
2. S'assurer que le paramètre `DEFAULT_GENERATE_MISSING_UUID` est bien défini à `True`
3. Importer un fichier source, avec ou sans colonne pour les UUID et avec ou sans valeur(s) vide(s), sans rien faire correspondre pour le champ "Identifiant SINP (uuid)"

## **Compléments**

Voir #279 pour plus de contexte autour de la génération par défaut des UUID

**Comment by VincentCauchois** [comment]
TODO : 
- [ ] Avoir différents fichiers d'imports : avec colonne UUID et toutes les lignes remplies, avec colonne UUID et certaines valeurs manquantes, avec colonne UUID vide, et sans colonne UUID
- [ ] Faire la configuration pour reproduire l'anomalie : génération des UUID manquants activé + coche masqué
- [ ] Réaliser les différents et constater quels cas posent problème
- [ ] Inspecter le fonctionnement de la génération des UUID dans le code

**Comment by camillemonchicourt** [comment]
Corrigé dans la 2.2.0
