### ISSUE TITLE
Rapport d'erreurs incohérent avec les données invalides téléchargées

### ISSUE THREAD

**Issue by cen-cgeier** [PnX-SI/gn_module_import#464]
GN : 2.12.3
Import : 2.1.0

Bonjour à tous,

J'ai récemment eu une collègue qui a eu une difficulté avec sont import. Le rapport indiquait 13 erreurs de cd_nom mais le fichier téléchargé des donnes invalides contenait uniquement des cd_nom valides.

En consultant le csv d'origine j'ai constaté que lorsqu'un saut de ligne est fais dans une cellule, la ligne en question se stocke sur 2 lignes. Dans ce cas, la ligne du fichier se stocke sur 2 lignes en base de données.
Le problème est que le téléchargement des données invalides itère sur le nombre de ligne stockée dans `t_imports.source_file` sans autre considération. 
Ci-dessous une illustration de mes propos : 

-  Exemple succinct de tableau de données saisie par un utilisateur : 
![image](https://github.com/PnX-SI/gn_module_import/assets/96542451/dec6dae9-c859-4fc3-9e08-869517908b0a)
- Equivalent stocké dans la table `t_imports.source_file`: 
![image](https://github.com/PnX-SI/gn_module_import/assets/96542451/c2fb1b09-5876-4aa0-93b3-28c04152cc81)

Le nombre de lignes stockées devient supérieur au nombre de ligne présent dans le tableau. Je soupçonne cet événement d'être la cause de la disparité entre les lignes identifiées dans le rapport d'erreurs (qui sont justes) et les données invalides téléchargées.
Je n'ai pas de solutions à proposer pour le moment.

**Comment by cen-cgeier** [comment]
Bonjour à tous,

j'ai pu me re-pencher sur le sujet et voici où en est ma réflexion : 

**Problématique :** 
1 ligne de données CSV peut correspondre à 1 ou X lignes de données binaires. C'est parfois le cas lorsqu'un saut de ligne est présent dans une cellule de texte.
La fonction permettant la récupérations des données erronées itère sur le nombre de lignes binaires.

**Quel marqueur pourrait identifier une ligne complète ?**
- Le nombre de quotechar `"` présent dans la ligne binaire.
Ce marqueur peut permettre d'identifier si une cellule est répartie sur une seule ligne ou plusieurs.
Si le nombre de quotechar est pair (ici, 0 est considéré comme pair), les cellules ne sont pas réparties sur plusieurs lignes, la ligne de données est complète. 
Sinon, la ligne de données est morcelée sur plusieurs lignes binaires. Les lignes suivantes sont considérées comme faisant partie d'une seule et même ligne, tant que le nombre de quotechar n'est pas pair.

**Fonction actuelle, récupérant les données erronées :** 
`gn_module_import/backend/gn_module_import/routes/imports.py l.531`
``` py

    @stream_with_context
    def generate_invalid_rows_csv():
        inputfile = BytesIO(imprt.source_file)
        yield inputfile.readline()  # header
        line_no = 0
        for row in inputfile:
            line_no += 1
            if line_no in imprt.erroneous_rows:
                yield row
```
**Proposition d'évolution de la fonction :**
``` py
    @stream_with_context
    def generate_invalid_rows_csv():
        inputfile = BytesIO(imprt.source_file)
        yield inputfile.readline()  # header
        line_no = 0
        n_qchar = 0             # Initiation de la variable dénobrant le nombre de quotechar
        for row in inputfile:
            n_qchar += row.count(b'"')     # nb quotechar dans la ligne binaire
            if n_qchar % 2 == 0:           # si nb quotechar est pair
                line_no += 1
                n_qchar = 0                # Ré-initialisation de n_qchar
            if line_no in imprt.erroneous_rows:
                yield row
```

Qu'en pensez-vous ? 
Je peux proposer une PR si la solution vous convient.

**Comment by bouttier** [comment]
Plutôt que de gérer les cellules sur plusieurs lignes manuellement, il vaut mieux utiliser les outils de Python pour lire et écrire du CSV. C’était mon erreur de ne pas avoir procédé de la sorte initialement. J’ai implémenté ceci dans #470. J’y ai également rajouté un test pour couvrir les fichiers de ce type.

**Comment by camillemonchicourt** [comment]
Merci, corrigé dans la 2.2.1
