### ISSUE TITLE
INVALID_URL_PROOF avec des adresses https:// contenant un espace

### ISSUE THREAD

**Issue by AudreyEnGuyane** [PnX-SI/gn_module_import#469]
Bonjour à tous,

je suis en train d'essayer d'importer un fichier contenant des preuves numériques. Lors de la vérification des données, j'ai le signalement d'une erreur INVALID_URL_PROOF: "... Il doit commencer par “http://”, “https://”, ou “ftp://”."
J'ai vérifié les adresses de mes preuves numériques: elles commencent toutes par "https://geonature.parc-"... 
Je butte depuis 2j car j'avais déjà fait d'autres imports avec des preuves numériques.

Bilan: l'import butte sur les adresses qui contiennent des espaces comme l'exemple suivant:
_https://geonature.parc-amazonien-guyane.fr/geonature/api/static/medias/5/DSCN5775_Theobroma grandiflorum_SebastienSant.jpg_
Je le sais car j'ai cherché/remplacé tous les espaces de ces adresses dans le fichier source... Ce qui a gommé l'erreur (mais du coup, l'import est faux!)

De fait, impossible d'importer les jeux de données concernés dans le SINP...

Solution: un petit patch pour que l'import prenne le champ dans son intégralité ? (et non jusqu'à la fin de la 1e chaîne de caractère!)

**Comment by camillemonchicourt** [comment]
Je ne comprends pas bien.
Une URL ne peut pas contenir un espace.

**Comment by AudreyEnGuyane** [comment]
Pourtant, il y en a bien un dans l'adresse mentionnée ci-dessus. 
Si tu colles l'ensemble de l'adresse dans un moteur de recherche, ça le fait!

**Comment by AudreyEnGuyane** [comment]
J'ai testé en remplaçant les espaces par %20, ça bloque aussi sur mes 35 enregistrements.

**Comment by camillemonchicourt** [comment]
Une URL ne doit pas avoir d'espace.
C'est pour ça que quand on uploade un média qui a un espace dans son nom, il est renommé automatiquement sans accent et sans espace.

Exemple, je viens de charger l'image "Roselin écrins Saulay.jpg" sur une observation Occtax et lors de l'intégration sur le serveur le fichier est renommé pour être disponible sur https://demo.geonature.fr/geonature/api//media/attachments/5/132_Roselin_ecrins_Saulay.jpg

C'est toi qui a mis manuellement des fichiers avec des espaces dans le dossier de ton serveur GeoNature (https://geonature.parc-amazonien-guyane.fr/geonature/api/static/medias/5/) ?
Dans ce cas, pour moi le soucis vient de là. Pas d'espace dans les noms de fichiers, si on veut qu'ils soient accessibles en HTTP.

**Comment by AudreyEnGuyane** [comment]
> C'est toi qui a mis manuellement des fichiers avec des espaces dans le dossier de ton serveur GeoNature?

Oui, lorsque j'ai intégré une base photo d'un de nos agents.
J'en conclue qu'il faut que je renomme tous les fichiers dans le dossier [api/static/medias/5/] et que je fasse la modification dans la table t_medias... Soit 15500 photos...
Ouch. J'ai bobo là...

**Comment by camillemonchicourt** [comment]
Des fichiers avec des espaces.
Tu cherches les bobos aussi. 🤣
C'est sur qu'il faut pas faire ça à la main...

**Comment by AudreyEnGuyane** [comment]
On va dire qu'on apprend de ses erreurs... Celle là, je ne la referai plus...
Et puis, je suis dure au mal. Et un peu maso...
Merci pour les infos. Y'a plus ka...

**Comment by camillemonchicourt** [comment]
Il doit y avoir différents outils permettant de faire ça en lot, ou directement en ligne de commande - https://www.linuxadictos.com/fr/como-eliminar-espacios-nombres-archivos.html

Ou une solution pour garder les fichiers avec des espaces dans leur nom, mais ça pour y accéder en HTTP ça me semble pas idéal.
