### ISSUE TITLE
Coquille dans le code à l'installation

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/gn_module_import#47]
La commande d'installation de GeoNature permet de nommer un module : 
geonature install_gn_module /home/geonatureadmin/gn_module_import-develop Imports (au pluriel avec une majuscule par exemple). 

Or cette variable est utilisée dans certains endroits du code et pas d'autres. Par exemple, le "module path" comprend bien la majuscule et le pluriel, mais ce paramètre n'est pas pris en compte pour créer le répertoire du module. Je m'explique :

On se retrouve avec le log suivant : 
FileNotFoundError: [Errno 2] No such file or directory: '/home/geonatureadmin/geonature/external_modules//Imports/upload/synthese_observations_2019-12-16T23_27_12.662Z.csv'. (avec le nom de module choisi par l'utilisateur) 
Alors que le chemin qui existe réellement est home/geonatureadmin/geonature/external_modules//import/upload/synthese_observations_2019-12-16T23_27_12.662Z.csv'.

A corriger pour que le paramètre de l'installation soit effectivement pris en compte et fonctionnel

**Comment by JulienCorny** [comment]
Salut,

J'ai corrigé une erreur à un endroit du code où le nom du module était effectivement en dur. 
Par contre, si on veut changer le nom du module lors de la commande gn_install_module (c'est à dire mettre autre chose que 'import'), il faut aussi modifier la valeur de la variable module_code dans le fichier manifest.toml. Je sais pas si c'est possible de le faire dynamiquement ou si c'est quelque chose à revoir sur l'ensemble des modules ? ou alors j'ai loupé un truc, ce qui se pourrait bien !

**Comment by camillemonchicourt** [comment]
Oui bien vu. Le code du module n'est pas spécialement fait pour être customisé.
Par contre il y a un champs label du module qui permet de customiser son nom affiché.
