### ISSUE TITLE
Affichage des champs non associés ne marche pas

### ISSUE THREAD

**Issue by joelclems** [PnX-SI/gn_module_import#496]
A l'étape trois *Correspondance des champs* on ne peut pas voir les champs non associé

Lorsque que l'on clique sur le liens `x Champs` on est renvoyé vers l'adresse `https://<domaine>/geonature/#unmappedSourceFields`
Il y a un pb avec le collapse (surement du à une montée de version de bootstrap

![image](https://github.com/PnX-SI/gn_module_import/assets/40370682/4b9e481e-4785-4d09-8d61-1176026e5d7a)

on peut utiliser ngbCollapse pour résoudre ce pb

**Comment by camillemonchicourt** [comment]
Corrigé dans la version du module intégrée au cœur de GeoNature à partir de sa version 2.15
