### ISSUE TITLE
Soucis sur les volumes de données

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/gn_module_import#50]
Actuellement un fichier csv de seulement 50.000 lignes ne peut être uploadé sur un serveur à 4Go. 
De même avec un GeoJson d'environ 10.000 lignes. 

devra pouvoir gérer des volumes de l'ordre de 300.000 lignes a minima comme évoqué avec Julien. (pas nécessaire d'avoir des performances importantes sur des fichiers de plus d'un million de lignes pour autant).

**Comment by JulienCorny** [comment]
En fait c'est lié au timeout de gunicorn qui est à 30 secondes par défaut. 
Là pour un fichier de 50000 lignes qui posait problème, le temps de traitement était de 35 secondes pour le mapping de champs/data cleaning, ça ne passait pas. 
J'ai modifié le timeout en le mettant à 300 secondes dans gunicorn_start.sh et ça marche : 
exec gunicorn  wsgi:app --error-log $APP_DIR/var/log/gn_errors.log --pid="${app_name}.pid" -w "${gun_num_workers}" -b "${gun_host}:${gun_port}" -t "300" -n "${app_name}"

A noter que sur un même serveur, le temps de traitement peut varier fortement selon les fichiers, même s'ils ont le même nombre de lignes selon : 
- la taille du fichier (10 ou 200 colonnes par exemple)
- le nombre d'erreurs détectées (s'il y a des erreurs à toutes les lignes ça rallonge le traitement)
- le nombre de traitement choisis (seulement mapping des champs obligatoires ou la totalité des champs)  
- les traitements choisis (par exemple générer des altitudes ou pas). 
Parfois un fichier de 10000 lignes peut prendre plus de temps qu'un fichier de 20000 lignes.

**Comment by DonovanMaillard** [comment]
Salut, 

Merci pour ton retour. 

Il faudrait le passer en paramètre dans la configuration dans ce cas. Est-ce possible?

**Comment by JulienCorny** [comment]
Salut,

Je ne sais pas si on peut le passer en paramètre de la config du module puisque ce timeout concerne toute l'instance de GeoNature sur le serveur, donc tous les modules ?

**Comment by DonovanMaillard** [comment]
D'accord, merci! 

Je vois avec @camillemonchicourt et @TheoLechemia  comment il vaut mieux gérer ce cas là, et le passer au niveau de geonature directement si besoin!

**Comment by TheoLechemia** [comment]
Oui on a déjà eu un problème de timeout comme ça.
On va le mettre en paramètre général

**Comment by DonovanMaillard** [comment]
Du coup, on renseigne temporairement cette commande dans la doc d'install du module et ca passe ensuite en paramètre. Jusqu'à ce qu'on arrive, peut-être un jour, à doper le module pour qu'il passe sous la limite de 30 secondes dans ses phases de mapping et data-cleaning

**Comment by TheoLechemia** [comment]
Oui tu peux le mettre dans la doc en attendant si tu veux.
Et pour la suite, l'idéal serait de sortir du contexte "requete/réponse" pour ce genre de gros traitement. Cf: ce qui a été fait pour le module d'export (lancement d'un thread parallèle)

**Comment by DonovanMaillard** [comment]
Réglé pour le moment avec le paramètre gun_timeout dans la conf de geonature.

**Comment by AmelieTagliaferro** [comment]
Bonjour, j'observe le même soucis d'import d'un jdd de plus de 1000 données en même temps malgré qu'on ait augmenté le timeout à 300... j'ai vérifié l'import des données en fractionné pour voir si il ne comportait pas trop d'erreurs mais non les données sont ok pour l'application ; c'est bien le nombre qui pose problème. Jusqu'où peut on augmenter le timeout sans que ça ne créée des modifications importantes dans geonature ?
Merci de vos retours :)
