### ISSUE TITLE
GN 2.14 / Mise à jour pandas

### ISSUE THREAD

**Issue by vprunet** [PnX-SI/gn_module_import#503]
Bonjour,
Le fichier requirements.in impose une version ancienne de pandas ( <1.4) dont le binaire n'est pas directement téléchargeable par pip install.
Du coup, l'installation du module import dans geonature 2.14.1 (debian 12) est très lente. Cela semble être dû à l'étape de compilation du package pandas en version 1.3.5.

La version courante de pandas (pip install pandas) est la 2.2.2

Question : est-ce que la contrainte  pandas<1.4 est toujours d'actualité?

**Comment by camillemonchicourt** [comment]
On installait une version inférieure à 1.4 de pandas car il fallait SQLA 1.4 minimum pour passer sur pandas 1.4 ou plus.
GeoNature 2.14 passant à SQLA 1.4, on doit maintenant pouvoir monter la version de pandas, mais faut tester et analyser ça.

**Comment by dba-sig-sfepm** [comment]
Bonjour, j'ai testé pandas<2.1 car jusqu'à la version 2.0.3 SQLAlchemy mini est 1.4.16. L'installation s'est passée sans erreur mais j'ai à présent une page 403 en voulant accéder à geonature :(

**Comment by dba-sig-sfepm** [comment]
en fait il y avait une petite erreur quand même en fin d'install : ` File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/bin/env', 'bash', '-i', '-c', 'nvm exec npm run build']' returned non-zero exit status 137.`
Je ne connais pas encore l'appli suffisamment pour comprendre d'où vient cette erreur 403, je suis preneur d'une idée ! Y-a-t il quelque chose à faire au niveau de la base de donnée lors de l'install du module ?

**Comment by blaisegeo** [comment]
Bonjour ;

Nouvelle installation de GeoNature 2.14.2 dans une machine virtuelle VirtualBox. Pas de problème, GeoNature s'ouvre correctement. Par contre l'installation du module import 2.3.0 bloque avec le même type d'erreur que ce qui est indiqué plus haut :

`(venv) geonatureadmin@debvbgn:~$ geonature install-gn-module ~/gn_module_import IMPORT
Installation du backend…
Obtaining file:///home/geonatureadmin/gn_module_import
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
INFO: pip is looking at multiple versions of gn-module-import to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement pandas<1.4 (from gn-module-import) (from versions: none)
ERROR: No matching distribution found for pandas<1.4
Traceback (most recent call last):
  File "/home/geonatureadmin/geonature/backend/venv/bin/geonature", line 8, in <module>
    sys.exit(main())
             ^^^^^^
...
...
...
    subprocess.run(f"pip install -e '{module_path}'", shell=True, check=True)
 `` File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'pip install -e '/home/geonatureadmin/gn_module_import'' returned non-zero exit status 1.
(venv) geonatureadmin@debvbgn:~$
`

Après modification du fichier ~/gn_module_import/requierements.in pour changer la version de Panda comme suggéré plus haut :
`###pandas<1.4  # panda 1.4 requires sqlalchemy>=1.4
pandas<2.1  #
`

et relance de l'installation du module import, j'obtiens exactement la même erreur, à la version de Panda près :
`ERROR: Could not find a version that satisfies the requirement pandas<2.1 (from gn-module-import) (from versions: none)
ERROR: No matching distribution found for paodification du fichier ~/gn_module_import/requierements.in pour changer la version de Panda :
`###pandas<1.4  # panda 1.4 requires sqlalchemy>=1.4
pandas<2.1  #
`

et relance de l'installation du module import, j'ai exactement la même erreur, à la version de Panda près :
`ERROR: Could not find a version that satisfies the requirement pandas<2.1 (from gn-module-import) (from versions: none)
ERROR: No matching distribution found for pandas<2.1
`

Une idée pour résoudre cela s'il vous plait ?

**Comment by blaisegeo** [comment]
Bonjour ;

Nouvelle installation de GeoNature 2.14.2 dans une machine virtuelle VirtualBox. Pas de problème, GeoNature s'ouvre correctement. Par contre l'installation du module import 2.3.0 bloque avec le même type d'erreur que ce qui est indiqué plus haut :

`(venv) geonatureadmin@debvbgn:~$ geonature install-gn-module ~/gn_module_import IMPORT
Installation du backend…
Obtaining file:///home/geonatureadmin/gn_module_import
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
INFO: pip is looking at multiple versions of gn-module-import to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement pandas<1.4 (from gn-module-import) (from versions: none)
ERROR: No matching distribution found for pandas<1.4
Traceback (most recent call last):
  File "/home/geonatureadmin/geonature/backend/venv/bin/geonature", line 8, in <module>
    sys.exit(main())
             ^^^^^^
...
...
...
    subprocess.run(f"pip install -e '{module_path}'", shell=True, check=True)
 `` File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'pip install -e '/home/geonatureadmin/gn_module_import'' returned non-zero exit status 1.
(venv) geonatureadmin@debvbgn:~$
`

Après modification du fichier ~/gn_module_import/requierements.in pour changer la version de Panda comme suggéré plus haut :
`###pandas<1.4  # panda 1.4 requires sqlalchemy>=1.4
pandas<2.1  #
`

et relance de l'installation du module import, j'obtiens exactement la même erreur, à la version de Panda près :
`ERROR: Could not find a version that satisfies the requirement pandas<2.1 (from gn-module-import) (from versions: none)
ERROR: No matching distribution found for paodification du fichier ~/gn_module_import/requierements.in pour changer la version de Panda :
`###pandas<1.4  # panda 1.4 requires sqlalchemy>=1.4
pandas<2.1  #
`

et relance de l'installation du module import, j'ai exactement la même erreur, à la version de Panda près :
`ERROR: Could not find a version that satisfies the requirement pandas<2.1 (from gn-module-import) (from versions: none)
ERROR: No matching distribution found for pandas<2.1
`

Une idée pour résoudre cela s'il vous plait ?

**Comment by jacquesfize** [comment]
Bonjour,

Maintenant que nous avons mis à jour SQLAlchemy en version 1.4, ne pas spécifier de version devrait fonctionner.

**Comment by blaisegeo** [comment]
Bonjour,

Effectivement, en gardant dans le fichier requierements.in
'pandas'
sans spécifier de contrainte de numéro de version, l'installation se passe corrrectement et le module est bien installé.

Merci toujours pour vos réponses rapides.

**Comment by camillemonchicourt** [comment]
Intégré dans la version 2.3.1
