### ISSUE TITLE
Erreur altitude négative à la vérification de fichier d'importation

### ISSUE THREAD

**Issue by blaisegeo** [PnX-SI/gn_module_import#504]
Bonjour;

GeoNature 2.14.0
gn_module_import 2.3.0

L'import d'un fichier csv avec des données en Petite Camargue, sans information d'altitude donc avec calcul d'altitude de GN sur le MNT provoque quelques erreurs lors de la phase de vérification juste avant d'importer réellement ces données :

Type d'erreur : INVALID_INTEGER
Champs : altitude_min et altitude_max
Descritption erreur : Format numérique entier incorrect ou négatif dans une des colonnes de type Entier.

En exportant ces données en erreur puis en les ouvrant dans Qgis ainsi que la couche ref_geo / dem de la base postgis geonature2db, on se rend compte que ces données ponctuelles sont effectivement dans des pixels de la couche postgis ref_geo / dem avec une altitude négative, par exemple en 43,5885699 N / 4,3653179 E : altitude = -0,51 mètre.

En mettant en valeur les altitudes négatives de cette couche geo_ref / dem dans Qgis, on constate qu'un certain nombre d'étangs et d'embouchures de fleuves le long du littoral ont des altitudes négatives, avec le record pour l'étang de Lavalduc avec quelques -9,56 mètres ( https://fr.wikipedia.org/wiki/%C3%89tang_de_Lavalduc ), altitudes négatives qu'on retrouve également sur geoportail avec l'outil "afficher les coordonnées".

En supprimant le fichier :

~/gn_module_import/backend/gn_module_import/checks/sql/__pycache__/__init__.cpython-311.pyc

pour forcer sa recompilation et en remplaçant dans ce fichier :

~/gn_module_import/backend/gn_module_import/checks/sql/__init__.py

sur les lignes 460 et 471 :

whereclause=(alti_min_synthese_field < 0),

et

whereclause=(alti_max_synthese_field < 0),

la condition "< 0" par "< -20", puis en relançant la procédure d'import depuis le début, la vérification ne renvoie plus d'erreur, l'importation se passe bien, et ensuite, dans la synthèse, en sélectionnat ces élements, ils ont bien une altitude négative dans leur fiche d'information.

Est-ce la bonne méthode pour importer des observations situées dans ces zones d'altitude négative le long du littoral méditerranéen ? Cette modification pourrait-elle créer des effets de bords non désirés et pas encore constatés ? Ou y aurait-il une méthode plus recommandable ?

**Comment by camillemonchicourt** [comment]
Fait dans la version intégrée dans GeoNature 2.15.
