### ISSUE TITLE
le module ne voit pas les jeux de données présents

### ISSUE THREAD

**Issue by dba-sig-sfepm** [PnX-SI/gn_module_import#505]
Bonjour, 
Sur une installation récente, le module est bien accessible mais lors de l'affichage de la fenêtre nouvel import, la liste déroulante jeux de données est vide. Il y pourtant de très nombreux jdd bien visibles sur l'interface métadonnées. Petite précision, les métadonnées ont été importés d'une autre instance de geonature (v 2.11.2) par un restore du schéma gn_meta. L'utilisateur fait parti du groupe grp_admin qui a bien sur la totalité des droits. Il n'y a aucune erreur ni sur la console ni sur les logs pour me mettre sur la voie. Merci d'avance

Geonature 2.14.2
gn_module_import 2.3.0
Debian 12

**Comment by camillemonchicourt** [comment]
Pour voir un JDD dans la liste des JDD dans lesquels on peut importer, il faut : 
- que le JDD soit actif
- que le JDD soit associé au module Import
- que l'utilisateur connecté ait des permissions C (create) et un scope suffisants sur le module Import, au regard des acteurs de ce JDD

**Comment by dba-sig-sfepm** [comment]
Bonjour, 
Merci beaucoup, en effet j'avais zappé l'association des JDD au module.
Du coup, j'ai une question complémentaire : l'association des jdd aux modules intégrés (, geonature, synthèse, validation) a-t-elle une influence ? Car dans l'instance dont j'ai hérité aucun jdd n'étaient associés à ces modules mais ils y étaient pourtant accessibles. Merci

**Comment by camillemonchicourt** [comment]
C'est utile que pour les modules de saisie ou intégration de données, justement pour pouvoir flécher quels JDD sont dispos à la saisie dans Occtax, Monitoring et Import.

Cela permet d'avoir des JDD qui sont proposés dans Occtax, mais pas Monitoring, ou seulement Import, etc...

Pas nécessaire, ni utile d'associer les JDD à GeoNature, Synthèse (pour le moment), Validation...
