### ISSUE TITLE
personnalisation du SRID

### ISSUE THREAD

**Issue by dba-sig-sfepm** [PnX-SI/gn_module_import#508]
Bonjour,
petite idée en passant, pour la refonte (si pas déjà dans les tuyaux) : pour l'instant lors de la configuration du fichier il n'y a que les 2 SRID les plus courants proposés mais parfois d'autres peuvent être utilisés (par ex : 32620 en Martinique ou 3163 en Nouvelle-Calédonie). Il pourrait être intéressant d'avoir un choix "autre" avec un champ permettant de saisir un SRID personnalisé. Ca éviterait d'avoir à faire des conversions préalables :)

**Comment by camillemonchicourt** [comment]
En fait c'est un paramètre du module.
L'utilisateur ne peut pas le renseigner mais l'administrateur peut en proposer d'autres en les ajoutant dans la config du module.

**Comment by dba-sig-sfepm** [comment]
Ah mince, j'avais zappé ça. Décidemment on (enfin je) ne lit jamais assez la doc !! Merci :)
