### ISSUE TITLE
Aucun JDD affiché à l'étape 1 de l'import

### ISSUE THREAD

**Issue by rgoffinet** [PnX-SI/gn_module_import#512]
Bonjour,

Nous souhaitons tester les nouvelles versions de géonature à Rennes Métropole. 
Sur un serveur debian 12 dédié, j'ai installé geonature 2.14.2 (via la procédure install_all non dockerisé). J'ai ensuite installé le module d'import 2.3.1 puis accordé toutes les permissions sur ce module au grp_admin (qui possède également tous les droits sur META).

Cependant lors du clique sur "nouvel import" la liste des JDD est vide : 
![image](https://github.com/user-attachments/assets/a78061e2-f194-4dd6-9418-61d06d805e3d)

Or, ma route /geonature/api/meta/datasets?orderby=dataset_name me renvoie bien mes 18 JDD.

Avez-vous une idée de ce qui pourrait expliquer ce problème ? Ai-je raté quelque chose lors du paramétrage du module ?

Merci d'avance pour votre aide.

**Comment by camillemonchicourt** [comment]
Les JDD souhaités ont-ils été associés au module Import ?
