### ISSUE TITLE
Empêcher le masquage d'un champs obligatoire

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/gn_module_import#53]
Actuellement, la table dict_fields permet de masquer les champs, ou définir ceux que l'on souhaite rendre obligatoire (par défaut, les not null de la synthèse). 

Il faut ne faut pas qu'un champs obligatoire puisse être masqué, via une contrainte sur la dict_fields par exemple. Sinon l'utilisateur est refoulé ("le champs cd_nom est obligatoire") sans pouvoir accéder au champs en question.

**Comment by JulienCorny** [comment]
C'est corrigé
