### ISSUE TITLE
Mappings et complication inutile du MCD

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/gn_module_import#54]
Actuellement, et comme prévu en #4 , on a une table pour les mappings de champs, et une table pour les mappings de valeurs.

A voir si à termes, il ne serait pas mieux de simplifier les choses en passant tout sur une seule table (avec un champs 'type' qui indique s'il s'agit d'une correspondance de champs ou de valeur). 

A lier à la discussion #42 pour le regroupement des deux mappings au sein d'un même ensemble. 

En l'occurrence, un choix à rediscuter qui n'était peut-être pas le plus optimisé dans ce qui était planifié.

**Comment by camillemonchicourt** [comment]
La structure de BDD des mappings a été entièrement revue dans la version 2.0.0 : 

![image](https://user-images.githubusercontent.com/4418840/200680813-ebf68248-f2eb-4350-acd9-5b7e2e1f3972.png)

Et ceux-ci sont administrables dans le module ADMIN de GeoNature : 

![image](https://user-images.githubusercontent.com/4418840/200681034-f82642fe-aa60-4af3-9ae3-4212309c04a0.png)
