### ISSUE TITLE
Pouvoir choisir une nomenclature constante à la place de la valeur par défaut en l'absence de champs source

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/gn_module_import#55]
Pour les nomenclatures, soit on a un champs source qui est mis en correspondance, et on fait un mapping des valeurs. Soit on ne renseigne pas de champs, et dans ce cas c'est la valeur par défaut de GeoNature qui est prise en compte. 

Il est fréquent de connaitre une constante pour un jeu de données importé (présent/absent en statut source, types d'objets géographiques, validation etc) sans pour autant disposer d'un champs dans le fichier source '(puisque c'est une constante appliquée à tout le jeu). 

Il sera nécessaire de pouvoir "écraser" la valeur par défaut de GeoNature en définissant une valeur constante, pour les nomenclatures qui n'ont pas de champs dédié dans le champs source.

**Comment by bouttier** [comment]
Doublon avec #68

**Comment by DonovanMaillard** [comment]
Merci Elie, ce petit ajout va faire du bien :) 

Simple question. Quel comportement quand on ne mappe aucune nomenclature ? On continue à sauter l'étape de mappings et pousser les valeurs par défaut de l'instance, ou on propose à l'utilisateur de choisir "ses propres" valeurs par défaut avec cette nouvelle possibilité ?
