### ISSUE TITLE
Etape de prévisulisation - Ajouter une carte

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/gn_module_import#58]
A termes, intérêt à rajouter une carte sur l'étape de prévisualisation. On a vite fait d'importer ses données au Nigeria si on ne maitrise pas totalement son jeu de données à importer.

**Comment by DonovanMaillard** [comment]
La prévisualisation, pour le moment très succincte, a vocation à évoluer vers quelque chose de plus complet et plus visuel. 

Une proposition d'interface ci-dessous, en intégrant notamment la possibilité d'ajouter un commentaire (qui serait stocké dans t_import, voir #93 ). 

![image](https://user-images.githubusercontent.com/23358384/75623924-b4dce000-5baf-11ea-9da0-5119294e8c94.png)

**Comment by DonovanMaillard** [comment]
dans les infos sous le commentaire, on peut même ajouter "Observations du ... au ...", la table t_imports stockant déjà la date min et date max des observations rentrées.

**Comment by camillemonchicourt** [comment]
Carte de prévisualisation faite par https://github.com/PnX-SI/gn_module_import/pull/132

**Comment by camillemonchicourt** [comment]
La carte a été ajoutée. Elle affiche la BBOX des observations et non pas les observations elles-même.
