### ISSUE TITLE
Import de GeoJson - Ordonnancement des champs

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/gn_module_import#59]
Lors de l'import d'un GeoJson, ses champs sont ordonnés de manière a priori aléatoire dans les tables créées (lors de la transformation d'un geojson vers un csv?). 

Il serait préférable de les stocker dans le même ordre que le fichier original , pour conserver la cohérence du fichier source (actuellement tout se mélange sans aucune logique, le mapping de champs est plus long).

**Comment by DonovanMaillard** [comment]
Erreur de diagnostic ! C'est les exports geojsons de geonature qui ne sont pas ordonnés, tandis que les csv le sont.

**Comment by JulienCorny** [comment]
Comme vu avec Donovan, le module import ne change pas l'ordre des champs, ce sont les geojson testés qui étaient désordonnés dès le départ

**Comment by TheoLechemia** [comment]
Oui, par définition les dictionnaire python ne sont pas ordonnés. On génère le geojson à partir de dictionnaire.
Voir du côté de "orderedDict": https://github.com/PnX-SI/GeoNature/blob/775f57bbe95b387423387ff65b21af0d4d5b990e/backend/geonature/core/gn_synthese/models.py#L382
