### ISSUE TITLE
Information "nombre de taxons" mal calculée

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/gn_module_import#60]
L'information "nombre de taxons" retournés pour un import terminée n'est pas valide. 

Elle calcule le nombre de cd_nom. Pour être exact, elle devrait se baser sur le nombre de cd_ref, avec une jointure sur la table taxonomie.taxref pour récupérer l'info.

**Comment by JulienCorny** [comment]
Corrigé
