### ISSUE TITLE
Accepter les uuid quand ils sont en majuscule

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/gn_module_import#61]
Selon les sources de données, les uuid peuvent être soit en minuscules, soit en majuscules. 

Actuellement si on sélectionne un champs source avec des uuid en majuscule, c'est considéré comme une erreur. A rectifier pour les accepter en les transformant en minuscule.

**Comment by JulienCorny** [comment]
Salut,

C'est corrigé. Etant donné que PostgreSQL accepte les uuid en majuscule, j'ai seulement supprimé la détection de l'erreur des UUID en majuscule, mais on ne les transforme pas en minuscule, ça fait gagner du temps de traitement
