### ISSUE TITLE
Etape 1 : Changement de séparateur n'enleve pas l'erreur correspondante

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/gn_module_import#65]
A l'upload, si j'ai une erreur comme une sélection du mauvais séparateur, il faut arreter et recommencer. 

Le changement de séparateur devrait permettre de revalider l'étape sans devoir tout recommencer.

**Comment by camillemonchicourt** [comment]
Le séparateur du fichier CSV est désormais détecté automatiquement : https://github.com/PnX-SI/gn_module_import/issues/119
