### ISSUE TITLE
Afficher et si besoin remplacer la valeur par défaut pour les nomenclatures non mappées

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/gn_module_import#68]
Si un type de nomenclature n'est pas "mappé", celle-ci n'apparait pas lors de l'étape 3. 

Si on a une info non renseignée, on ne découvre donc la valeur par défaut que dans l'étape 4 de prévisualisation. On ne peux pas non plus modifier cette valeur par défaut pour le jeu de données qu'on importe (par exemple si on sait qu'on ne rentre que des cadavre trouvés sur les routes, on ne peut pas renseigner un statut "trouvé mort" par défaut).

**Comment by DonovanMaillard** [comment]
D'autant plus pertinent pour pouvoir valider des controles plus avancés tels que ceux évoqués dans le #176 

@camillemonchicourt souligne aussi l'intérêt pour des nomenclatures qui sont dans le mapping mais dont certaines lignes sont vides : on ne peut pas actuellement définir la valeur par défaut

**Comment by lpojgc** [comment]
Je plussoie ce ticket ;-)

Il faudrait que l'on puisse choisir une valeur pour l'import si l'info n'existe pas dans le fichier.

Merci !

**Comment by DonovanMaillard** [comment]
Rien de planifié sur ce sujet pour le moment, mais me semble toujours autant pertinent :) 

A voir suite à la refonte en cours, il est possible que la manière dont les imports sont traités à l'avenir soit plus facilement compatible avec cette fonctionnalité

**Comment by DonovanMaillard** [comment]
Merci Elie qui a ajouté cette possibilité, ce petit ajout va faire du bien :)

Simple question. Quel comportement quand on ne mappe aucune nomenclature ? On continue à sauter l'étape de mappings et pousser les valeurs par défaut de l'instance, ou on propose à l'utilisateur de choisir "ses propres" valeurs par défaut avec cette nouvelle possibilité ?

**Comment by camillemonchicourt** [comment]
Dans la version 2.0.0, on peut associer une nomenclature pour les colonnes vides dans le fichier source, mais seulement pour les nomenclatures que l'on a mappé.

Donc si je comprend bien cela répond à la 2° partie de ce ticket, mais pas à la première.

Et si on ne mappe aucune nomenclature, on arrive quand même à l'étape de mapping des valeurs, mais sans aucun champs, donc discutable en effet : 

![image](https://user-images.githubusercontent.com/4418840/200682790-a9a9c902-ad9d-4b6a-9251-4dd35005113f.png)

Donc pas certain que la release 2.0.0 permet vraiment de fermer ce ticket.

**Comment by camillemonchicourt** [comment]
Pour le fait que si on ne mappe aucune nomenclature, on zappe l'étape 4, voir la PR dédié à cela : https://github.com/PnX-SI/gn_module_import/pull/384

**Comment by bouttier** [comment]
Statut en 2.0.4 :
- Pour les colonnes non mappé à l’étape de correspondance des champs, le champs n’apparaît pas lors de l’étape de correspondance des valeurs et on importe la nomenclature par défaut (ou NULL s’il n’y a pas de nomenclature par défaut). Une solution de contournement consiste à rajouter une colonne manuellement dans son fichier CSV, quitte à laisser cette colonne vide, que l’on mappera de manière à pouvoir choisir une nomenclature pour les valeurs vides.
- Pour les colonnes mappées, on utilise les nomenclatures du mappings. Si une cellule est vide, l’étape de correspondances des valeurs force à sélectionner une nomenclature pour ces cellules (« _Pas de valeur_ »).
- Dans le cas très particulier où on a désactivé l’étape de correspondance des valeurs (``ALLOW_VALUE_MAPPING = false``, déconseillé), il est nécessaire de spécifier l’ID d’un mapping de valeur générique pré-existant via le paramètre ``DEFAULT_VALUE_MAPPING_ID``. Si une colonnes mappés contient des cellules vides, mais le mapping de valeur ne précise pas de nomenclature à utiliser, alors :
  - si ``FILL_MISSING_NOMENCLATURE_WITH_DEFAULT_VALUE`` est vrai (valeur par défaut), on utilisera la nomenclature par défaut
  - si ce paramètre est faux, une erreur de nomenclature sera levé pour la ligne en question
  
  En version 2.0.0 à 2.0.3, aucune erreur n’était levée et des nomenclatures ``NULL`` pouvaient être insérées en synthèse. Ces données peuvent être corrigé avec le script SQL suivant : https://gist.github.com/bouttier/03ab62b6abc8dcbe5cd527a2cb3a82a4. Je rappelle néanmoins que vous n’avez normalement pas à l’exécuter, celle-ci concerne uniquement les installations dont l’étape de correspondance des valeurs est désactivée et dont le mapping par défaut ne précise pas de nomenclature pour les cellules vides.
