### ISSUE TITLE
Analyser la pertinence d'utiliser les fonctions SQL d'import

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/gn_module_import#7]
Analyse à faire sur l'usage potentiel des fonctionnalités SQL existantes dans le schéma ``gn_import``

Doc import avec fonctions SQL avancées : https://geonature.readthedocs.io/fr/latest/import-level-2.html

Sinon l'import de base : https://geonature.readthedocs.io/fr/latest/import-level-1.html

**Comment by DonovanMaillard** [comment]
Après discussion avec Julien, sans statuer sur le fait d'utiliser ou non les fonctions de Gil. Les transformations de données et donc une partie importante du module devraient se faire en SQL plutôt qu'en python, pour permettre unemeilleure autonomie pour l'entretien et les mises à jour du module à termes.

**Comment by TheoLechemia** [comment]
Tu peux préciser les avantages pour les MAJ et la maintenabilité d'écrire en SQL ?
J'y vois plutôt la nécessité d'écrire des script de MAJ à chaque modification ...

**Comment by camillemonchicourt** [comment]
Oui, point à discuter du coup.

**Comment by DonovanMaillard** [comment]
L'idée de Julien était que globalement autour de GN on est plus à l'aise avec le Sql. Plus simple pour faire les modif de manière autonome dans le cas où la synthèse aurait un nouveau champs ou ce ge're de choses

**Comment by sig-pnrnm** [comment]
> globalement autour de GN on est plus à l'aise avec le Sql.

Je confirme que dans mon cas, je sais écrire le SQL, mais pas (encore) le Python.
J'aurai donc beaucoup plus de facilités à adapter une requête SQL qu'un script Python.

**Comment by TheoLechemia** [comment]
Oui bien-sur, davantage de gestionnaire de BDD maîtrise le SQL.
Mais il ne faut pas oublié que python offre beaucoup plus de souplesse et de fonctionnalité pour écrire des vrais fonctionnalités métiers (écriture de test, lisibilité du code, monté de version sans script de MAJ ...). Il faut voir ce qui est prévu d'être écrit en SQL, mais ça me parait bancal que le coeur des fonctionnalité du module le soit en SQL.

**Comment by JulienCorny** [comment]
Bonjour,

De mon point de vue, le principal (unique?) avantage de le faire en SQL est que les gestionnaires de la bdd geonature pourront intervenir directement sur les fonctions SQL s'ils veulent modifier quelque chose par la suite. C'est dans cette optique que je partais plus sur du SQL pour ce module.

Mais sinon Python est un super outil pour faire tout ça et bien plus pratique, avec beaucoup de librairies, dont Pandas, qui sont vraiment faites pour ce genre de manipulations (data extraction, transformation, verif, ...). A mon avis, c'est plus rapide et pratique à coder, tester et maintenir.

Après il y a peut-être possibilité de mixer un peu les 2. Par exemple la partie de la fonction load_csv de Gil qui copie les données du fichier utilisateur dans des tables (contenant les données brutes) en BDD est pratique et ne nécessite pas je pense de passer par Python. Par contre ce serait plus puissant je pense de faire les opérations qui suivent (transformations, vérif, corrections,...) en Python, notamment en vue de l'amélioration éventuelle du module dans le futur qui peut potentiellement déboucher sur une multitude de petites fonctionnalités à coder (renforcement des vérifications de formats de fichier, corrections automatiques, vérifications et corrections du format et valeurs des données géo, chrono, réconciliation taxref, ...)

**Comment by camillemonchicourt** [comment]
Oui. Par la suite le module va être enrichi avec bien plus de vérification des données.

**Comment by DonovanMaillard** [comment]
Ca marche, donc plutôt le cœur du module en python pour vous ? Et garder uniquement en sql les choses comme l'exemple de load csv, qui sont stables et fonctionnelles en Sql sans complications pour les faire évoluer ?

**Comment by gildeluermoz** [comment]
Effectivement, tout ce qu'un admin modifierait dans du code SQL serait potentiellement à refaire en cas d'évolution du module. Donc oui, plutôt faire en python et penser à rendre paramétrable tout ce qui pourrait être différent d'une instance de GeoNature à l'autre (sauf bien sur pour des valeurs de paramètres enregistrées en base)

**Comment by DonovanMaillard** [comment]
L'essentiel est in fine développé en python, pour les mappings et les transformations de données vers le format et les nomenclatures standards. 
Le sql est utilisé pour l'INSERT à la fin, et pour les fonctions de géométrie.
