### ISSUE TITLE
Installation - libs manquantes

### ISSUE THREAD

**Issue by TheoLechemia** [PnX-SI/gn_module_import#70]
Juste pour signaler qu'en installant la branche develop, j'ai dû installer manuellement les lib python suivantes:
- toolz
- cloudpickle

**Comment by DonovanMaillard** [comment]
Ca marche merci. 

Tu as pu installer les autres (requirements.txt) directement en installant le module avec geonature install_gn_module , ou tu l'as fait à la main ? Perso ca coince toujours au moment d'installer ce qui est indiqué dans le requirement.txt. 

J'ajoute les 2 quand même au fichier pour le tenir à jour.

**Comment by TheoLechemia** [comment]
Oui avec la commande, tout roule

**Comment by camillemonchicourt** [comment]
Il faudrait voir quelles versions ont été installées pour les fixer.

**Comment by DonovanMaillard** [comment]
J'ai vu les versions installées, et les ai fixées dans la branche fix_bdd.

**Comment by DonovanMaillard** [comment]
Fait pour la 1.0.0
