### ISSUE TITLE
Valeurs dupliquées dans les multiselects

### ISSUE THREAD

**Issue by TheoLechemia** [PnX-SI/gn_module_import#71]
Lors du mapping, si on supprime une valeur déjà renseignée, elle apparaît alors en double dans la liste déroulante. Puis en triple, en quadruple si on recommence.

**Comment by DonovanMaillard** [comment]
constaté également pour info

**Comment by DonovanMaillard** [comment]
Corrigé par @TheoLechemia pour la  version 1.0.0
