### ISSUE TITLE
Liste des imports - Pouvoir rechercher/filtrer/trier

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/gn_module_import#75]
- Recherche libre
- Filtre par JDD (liste), année, état
- Tri des colonnes

**Comment by DonovanMaillard** [comment]
Pour l'étape 1? Oui, ca permettrait aussi de "regrouper" les imports par JDD comme théo l'évoque dans le #74

**Comment by camillemonchicourt** [comment]
Voir https://github.com/PnX-SI/gn_module_import/pull/97/files

**Comment by camillemonchicourt** [comment]
Fait : Recherche libre (sur toutes les colonnes) et tri des colonnes. 
Pas de filtre par colonne pour le moment.
