### ISSUE TITLE
Annule et remplace

### ISSUE THREAD

**Issue by TheoLechemia** [PnX-SI/gn_module_import#77]
Pouvoir supprimer un import et réimporter un nouveau fichier.

**Comment by camillemonchicourt** [comment]
Utiliser t_sources pour retrouver les observations d'un import dans la synthèse ?

**Comment by camillemonchicourt** [comment]
Attention aux UUID SINP.
Si on a généré les UUID lors du premier import et que les données ont été partagées avec ces UUID mais qu'on les supprime et les reimport et qu'on leur génère de nouveaux UUID...

**Comment by DonovanMaillard** [comment]
Avec pour autre conséquence la perte des infos stockées dans les tables transversales telles que la validation. 

Un upsert serait plus logique mais plus complexe si les id d'origine je sont pas fiables

**Comment by DonovanMaillard** [comment]
à articuler avec la réflexion #33 pour éviter un annule et remplace, et avoir un mécanisme un peu plus subtile .

**Comment by camillemonchicourt** [comment]
Dans la 1.1.0, on peut supprimer un import et toutes ses données associées.
A voir si il faut en plus gérer la possibilité d"Annuler et remplacer" ?

**Comment by bouttier** [comment]
Avec la v2, il est possible de modifier un import après que celui-ci soit terminé. On peut notamment téléverser un nouveau fichier puis faire suivant, suivant, suivant … pour garder les paramètres / correspondances existantes. Lors de la nouvelle finalisation de l’import, les anciennes données sont supprimées et les nouvelles sont importées.

**Comment by camillemonchicourt** [comment]
Fait dans la version 2.0.0, avec la possibilité de reprendre un import à n’importe quelle étape, y compris lorsque celui-ci est terminé (permettant de mettre à jour des données déjà importées dans la synthèse).

On peut ainsi ré-uploader un fichier source corrigé ou complété sur un import en cours ou terminé.
