### ISSUE TITLE
Afficher le rapport d'erreur dans la liste des imports

### ISSUE THREAD

**Issue by TheoLechemia** [PnX-SI/gn_module_import#78]
Pouvoir afficher le rapport d'erreur depuis la liste des imports.

**Comment by DonovanMaillard** [comment]
A mettre dans une modale d'info, déjà évoquée dans le ticket #34  ?

**Comment by camillemonchicourt** [comment]
Fait dans le cadre du ticket https://github.com/PnX-SI/gn_module_import/issues/114
