### ISSUE TITLE
Actualités et suivi des développements

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/gn_module_import#8]
**Première réunion cet après-midi avec Julien.** 

Les premières briques sont posées, avec des fonctionnalités socle permettant d'installer le module, créer un nouvel import et importer un fichier source, qui est uploadé sur le serveur dans un répertoire "upload" propre au module. Le travail sur la base de données n'a pas encore commencé. 

La prochaine étape est donc de construire la base de données correspondant au module, sur la base de l'ébauche effectuée #4 . Le schéma gn_imports déjà existant sera utilisé pour stocker les infos liées au module d'import (mappings, historiques etc). Les tables et fonctions déjà présentes seront modifiées, supprimées ou déplacées à termes selon les besoins, une fois le module développé. Pour le moment les tables du module et les tables "historiques" cohabiteront sans être liées. Le module d'import génèrera également un second schéma destiné à recevoir les tables d'archive : c'est à dire les données brutes uploadées sans aucune modification (plus économique et simple que de conserver les fichiers source). 

Ont également été revus les mécanismes de choix des jeux de données (passé dans une modale avant l'upload du fichier source pour toute création d'un nouvel import, afin de tout de suite rejeter l'utilisateur s'il n'a pas créé son jdd en amont). 
Ce qui se répercute sur le mécanisme de choix du mapping (qui constituait une étape à part entière avec le choix du jeu de donnée jusqu'à maintenant), qui devrait passer directement sur l'interface de mapping des champs (avec un grisage des mises en correspondances tant qu'on a pas sélectionné ou créé un mapping). 

Tout cela modifie à la marge la maquette, en supprimant l'étape actuellement numérotée 2 #3 

Par ailleurs, on a fait un point sur la BDD et l'ébauche de BDD du module. Sauf complications particulières, le module devrait effectuer les transformations des données (créations des geoms, création des uuid, correspondances des nomenclatures etc) en SQL et non pas en python pour faciliter l'entretien et les ajustements sur le module par la suite.

**Comment by DonovanMaillard** [comment]
Bonjour à tous, 

Ci-dessous un retour du point hebdomadaire avec Julien sur les développements
- Le développement de la BDD a débuté avec ce qui touche à l'itération 1. Les premières tables sont donc en place, avec tout ce qui concerne les id d'import, les id_dataset, dates de création de l'import etc. La correspondance avec les rôle est également en cours de développement (tel role a contribué à tel import). 
- La fonction d'upload est également bien amorcée pour les fichiers ne présentant pas de soucis (pas encore de controles). Les infos liées à l'upload (format du fichier, SRID etc) enrichissent également la base. 

- Sur le fait de développer le controle et la manipulation des données plutôt en python ou en SQL, ça reste à rediscuter au besoin, mais il semble plus pertinent, (performance, robustesse, simplicité) defaire cette partie plutôt en python comme @TheoLechemia  avait l'air de le suggérer. En revanche, celà pose des question (discuté #9) : il faut que le module puisse être ajusté le plus simplement possible en cas d'évolutions, au sein d'une communauté d'utilisateurs plutôt orientée SQL... Malgré tout, pour le moment le choix penche plutôt sur Python pour l'instant, il faudra le décider très rapidement maintenant. 

- Autre question qui se pose, et qui a une petite incidence sur les développements. Quand on reprend un import en cours, est-ce qu'on revient toujours à la première étape, et les champs sont pré-remplis jusqu'à ce que l'on revienne à notre avancement (sachant qu'il n'y a que 3 étapes!) ou est-ce qu'on revient directement sur la dernière étape à laquelle on a arrêté le travail...

**Comment by DonovanMaillard** [comment]
Un petit retour après le point hebdomadaire :

- Concernant les questions qui se posaient précédemment, **le fait de développer le coeur du module** (controle et transformation des données) **en python est acté**, pour plus de robustesse, de facilité et rapidité de développements. De même, on stocke en base l'étape à laquelle on a stoppé un notre travail, et **on revient automatiquement à cette étape lorsqu'on le reprend un import en cours**.

- **Le module pourra évoluer dynamiquement pour toute modification de la table synthèse portant sur des nomenclatures** (ajout, suppression, modification). Pour cela, il lit les infos dans la table de gn_common qui recenses les colonnes de la table synthèse, et les id_type nomenclatures attendus. **En revanche, si la synthèse évolue sur un autre champs que des nomenclatures, il faudra mettre à jour le module d'import au cas par cas**. 
Derrière ce choix, le fait que ce qui est le plus susceptible d'évoluer dans la synthèse est les référentiels et donc les nomenclatures. Et le fait que si un autre champs de la synthèse évolue, il entrainera des modifications dans tout GeoNature de toutes manières. La table synthèse étant transversale et vouée à être stable, il ne semble pas pertinent d'allonger et compliquer les développements pour rendre le module pleinement dynamique.

- **Niveau avancement, la partie upload + les bases de l'historisation des imports devraient être aboutis la semaine prochaine**. Les controles du fichier source (séparateur, choix du srid etc) seront déployés dans la semaine prochaine. 

- Pour gagner en efficacité, les itérations vont être un peu remaniées : l'historique et le fait de stopper/reprendre un import sont des taches transervales que Julien va mettre en place au fil des autres développements. Il pose donc les bases dès maintenant. Et une "mini-itération" lui permettra de paufiner ces fonctionnalités (paramétrage de l'affichage de l'historique de l'import, ce genre de choses)

- Dans le même registre, la gestion des différents encodages sera développée en fin de prestation. Le but étant de développer en priorité le coeur du module : upload, mappings de champs, mappings de contenus

Sur l'interface des bases sont posées et montrent que le besoin et la mécanique souhaitée pour les imports sont compris. Seules quelques paufinages sont à faire sur ces bases (composants, intitulés des boutons etc). 

Même s'il est précoce de se faire un avis à ce stade, une démo sera occasionnellement mise à jour sur [cet URL](https://geonature.demos.natural-solutions.eu/geonature/#/) au cours du développement.

**Comment by DonovanMaillard** [comment]
Bonjour, 

Un point sur les discussions de cette semaine : 

Il ne sera pas possible de réutiliser la fonction "load_csv" développée par Gil, car elle s'appuie sur la fonction pgsql COPY... nécessitant d'être superuser. Un problème d'après Julien, qui propose d'utiliser à la place le COPY FROM de sql alchemy. Ce fonctionnement a cependant un impact par rapport à ce qui était envisagé : on doit obligatoirement créer une clé primaire dans la table d'import et la table d'archive que l'on va créer, il ne sera pas possible d'utiliser celle des données sources si ces données sources avaient une clé primaire. 
La clé primaire du fournisseur de données sera donc simplement stocké comme tous les champs sources ... Seul inconvénient, on aura donc 2 identifiants dans la table d'import (le source + celui de gn)+ un uuid éventuellement créé en synthèse. Un peu de rigueur sur la gestion des identifiants sera donc requise. En revanche, celà simplifie un peu les choses pour renseigner la table t_source. 

Par ailleurs, le séparateur csv sera paramétrable dans la conf du module par l'administrateur de l'instance. 

Les tables créées dans la base porteront le nom du fichier source (en remplacant les espaces etc par des _) suivis du numéro de l'import... pour éviter les conflits si plusieurs fichiers importés ont le même nom (data.csv ou protocole_machin.csv par exemple). 

Niveau avancée, Julien poursuit donc son travail sur l'upload du fichier source, après avoir rencontré ces soucis de droits superuser et de clés primaires à créer obligatoirement. Ce travail d'upload, controle du fichier source, création des tables et suppression du fichier ensuite devrait aboutir dans une à 2 semaines si tout va bien.

**Comment by camillemonchicourt** [comment]
Je comprends pas pourquoi le fait d'utiliser le COPY FROM impose de créer une nouvelle clé primaire...

Dommage de pas pouvoir choisir le séparateur à choix import. C'est pas vraiment souhaitable ça. 
On devrait pouvoir le choisir à chaque import, idem pour le séparateur de texte. Et il peut aussi y avoir le séparateur de décimale.

**Comment by DonovanMaillard** [comment]
Julien ou Théo pourraient te répondre plus en détail, mais **à priori** quand on utilise la commande COPY FROM, elle demande obligatoirement une clé primaire pour créer une table dans la base. Sauf qu'au moment de la création des tables, et donc de l'upload, on a pas encore "lu" les champs présents dans le fichier, donc on ne peut pas indiquer quelle est la clé primaire du fichier....  A revérifier avec eux pour plus de détail. 

Pour le séparateur, c'est un choix discuté pendant la réunion de cadrage, et de mémoire le fait de choisir ça en interface augmentait le risque d'erreurs (quid d'un ; dans un commentaire, etc) et on n'évitera, de toutes facons, pas un nettoyage/formatage du fichier un minimum avant de pouvoir l'importer. On était donc restés là dessus, à rediscuter peut être mais pour le moment je suis resté sur ce qui avait été dit en réunion.

**Comment by JulienCorny** [comment]
Bonjour,
C'est parce que la fonction copy_from de psycopg2 (outil Python pour travailler avec postgreSQL), qui est l'équivalent de COPY de postgreSQL, impose l'utilisation d'une clé primaire pour envoyer les données vers postgreSQL.

**Comment by amandine-sahl** [comment]
Bonjour, 

Ca ne marche pas avec copy_expert?

```
CREATE TABLE test_copy(
    col1 varchar,
    col2 varchar,
    col3 varchar
);

from sqlalchemy import create_engine

with open('/tmp/tmp_process.csv', 'r') as f:
    conn = create_engine('postgresql://user:pass@localhost:5432/tmp_process').raw_connection()
    cursor = conn.cursor()
    cmd = 'COPY test_copy(col1, col2, col3) FROM STDIN WITH (FORMAT CSV, HEADER FALSE)'
    cursor.copy_expert(cmd, f)
    conn.commit()

```

**Comment by JulienCorny** [comment]
Bonjour,

C'est la même erreur que pour copy_from:
Mapper Mapper|UserTableClass|filename could not assemble any primary key columns for mapped table 'filename'

**Comment by DonovanMaillard** [comment]
Bonjour, nouveau point sur les développements .

Julien a quasiment terminé le développement de la phase d'upload, de controle du fichier source et de copie des données dans la BDD. Un certain nombre de controles se font sur le csv uploadé (présence de tous les noms de colonnes, pas de noms en double dans les noms de colonnes, pas de cellule "hors cadre", tableau non vide etc, avec des messages d'erreurs clairs pour l'utilisateur. 

Du fait de la contrainte technique évoquée ci-dessus, une clé primaire propre à géoneature est générée dans chaque fichier uploadé (elle s'appelle gn_pk). En revanche il est prévu lors de l'étape de mapping de déclarer une seconde clé, si le fournisseur de données en avait une, pour vérifier notamment l'absence de doublons. Dans tous les cas dans la t_source et dans la synthèse c'est la gn_pk qui est considérée et non pas la clé du fournisseur. 

A l'heure actuelle, le module permet donc d'uploader un fichier, qui est uploadé, lu, controlé et entré dans une table d'archive + une table d'import. Les premières infos (dataset, id_role, date de création de l'import etc) sont stockées dans le schéma du module. Cette phase devrait se terminer dans la semaine. Prochaine réunion vendredi dans une dizaine de jours, avec le début des développements sur la première phase de mapping.

**Comment by DonovanMaillard** [comment]
Bonjour, 

Un point (rapide) sur les avancées du module d'imports. 
- La phase d'uploads est désormais fonctionnelle, ainsi que l'ensemble des controles effectués sur le fichier source. 
- Après upload, les tables sont créées dans la base, et l'historique est renseigné lors de ces premières étapes. 
- Les différents éléments qui permettent de stopper et reprendre un import sont également implémentées au fur et à mesure. 
- L'interface historique est en train de se mettre en place, avec des champs paramétrables comme cela est fait sur la synthèse et occtax. 

Un point assez important a été fait aujourd'hui avec @JulienCorny , pour planifier la phase de mapping des champs (voir #11 ). Une nouvelle phase particulièrement conséquente, qui va débuter la semaine prochaine mais qui avancera essentiellement en juillet après 2 semaines de break fin juin.

**Comment by DonovanMaillard** [comment]
Bonjour, 

Après une longue période d'arrêt et de ralentissements (congés et autres imprévus), un nouveau point sur les développements du module d'imports. 

Les développements ont repris il y a peu, et on retrouve le rythme du début avec un projet qui reprend le cap. 

@JulienCorny a donc bien avancé sur deux points au cours des dernières semaines : 
- 1) Les performances pour l'import et le traitement des données, pour pouvoir supporter des volumes de données satisfaisants. L'upload du taxref par exemple prenait quelques minutes. Des tests avec des données naturalistes à envoyer dans la synthèse seront faits dans les prochaines semaines sur des jeux de plusieurs centaines de milliers de ligne (jusqu'à 1,6 millions pour le plus gros test).

2 - Le "datacleaning". Un (très) gros travail a été fait sur le controle et le nettoyage des données. Plusieurs résultats en découlent : 

- Une table d'erreurs sera mise en place dans la base de données, pour retourner les erreurs identifiées sur les lignes non-valides (pas de date, date au mauvais format, date max<date min, ou pas de cd nom, cd_nom hors taxref ou autre). Plusieurs dizaines d'erreurs du type existeront, julien propose donc de les stocker dans une table, et de retourner dans la table d'import le ou les id_erreurs renvoyés par l'appli, afin de cibler les corrections à faire sur les données pour le gestionnaire de la BDD.  Pour internationaliser un peu les choses, ca peut aussi largement faciliter la traduction des messages d'erreurs par la suite et pourquoi pas prévoir un paramètre pour choisir la langue du module à termes. 
@TheoLechemia, @camillemonchicourt , @gildeluermoz   : est-ce qu'une table d'erreur de ce type doit être dans le schéma imports, ou dans le schéma gn_commons ? Est-ce qu'une telle table peut servir à votre avis pour d'autres modules comme occtax ou autre (date_max inférieure à date min etc par exemple) avec cette même idée de traduction à terme par exemple?

- plusieurs choix ont été faits du coup quant à la manière de traiter différentes erreurs : 
sur les altitudes, soit on les calcule, soit on stock tel quel les données transmises dans le fichier importé. S'il n'y a qu'une alt min et qu'on renseigne rien dans le max, alors la synthèse n'aura qu'un mini. Si on renseigne dans le mapping des champs que notre altitude source correspond au min et max de la synthèse, on a les deux memes valeurs. Si on a des champs renseignés et des vides, on retrouvera des vides dans la synthèse. Et donc si on a un min supérieur à un max, on aura une erreur qui sera levée et la donnée ne sera pas importable en l'état (soit on ne l'importe pas, soit on la corrige en bdd donc). 
- Sur les dates, si seule une date min est renseignée (obligatoire), la date max vaut la date min. Si deux dates sont renseignées (min et max), on controle la contrainte date max>date min, sinon erreur, idem pour les count etc. 
Sur les uuid, on peut ou non caluler des uuid s'il n'en existe pas. 
@JulienCorny  je ne me rappelle plus ce qu'on a dit dans le cas ou on renseigne un champs uuid mais qu'il y a des cellules vides : je pense que dans ce cas, le mieux est de lever une erreur (certains uuid sont manquants dans le champs source), et qu'on peut choisir ou non de cocher la case 'créer un uuid" pour compléter les manquants. Si on ne coche pas, il reste l'erreur, et les données ne sont pas importées comme pour les autres erreurs. Si on coche la case pour créer un uuid sans indiquer un champs qui en comporterait déjà, alors ça crée un champs dans la table d'imports comme prévu. 

Niveau calendrier : 
- Le prochain sprint de 2 semaines servira au mapping des champs + fin du datacleaning (géométries notamment) et l'envoi dans la synthèse
- Le sprint suivant, sur fin septembre, servira au mapping de contenu et à la sauvegarde des mappings effectués, et finaliser la possibilité de rafraichir les données après avoir effectué des modifications coté BDD (corrections, calculs de cd_nom ou autre). 
- Début octobre en principe, prévisualisation et envoie des données dans la synthèse, et tests avec des gros volumes. 

Fin octobre début novembre, début des tests avec une pre-release, pendant que Julien fera l'interfacage et les derniers développements : prise en charge des fichiers json, mise en paramètre de certaines fonctionnalités, 

Pas mal de points à voir et revoir en ce moment donc, sur tout ce qui concerne la manipulation des données et les corrections et erreurs à faire remonter lors des imports, mais le projet avance de nouveau. 

Donovan

**Comment by camillemonchicourt** [comment]
OK merci pour ce retour. 
Concernant la table avec les types d'erreur, on préfère la mettre dans le schéma ``gn_imports``, pour ne pas trop mélanger et rester lisible. 
Concernant les champs min et max, je ne comprends pas pourquoi vous n'appliquez pas la même logique sur les altitudes et les dates.

**Comment by DonovanMaillard** [comment]
Ça marche.

Pour les dates les champs sont obligatoires. Contrairement aux altitudes etc. Donc si linfo n'est pas où seulement partiellement fournie il faut soit lever une erreur soit compléter linfo.

**Comment by JulienCorny** [comment]
Pour l'uuid c'est bien ce que tu as décrit @DonovanMaillard  : si il est manquant mais que l'utilisateur n'a pas coché la case pour demander de le générer on envoie un warning, c'est à dire qu'on prévient l'utilisateur pour lui dire attention c'est manquant, mais ce n'est pas une erreur bloquante ('gn_is_valid' reste à True). Si l'utilisateur a coché la case on le génère. Et pour les valeurs fournies par l'utilisateur, on vérifie bien que la valeur est correcte c'est à dire de type uuid, sinon on envoie une erreur ('gn_is_valid'=False)

**Comment by DonovanMaillard** [comment]
C'est ça!

**Comment by DonovanMaillard** [comment]
Bonjour à tous, 

Un point sur les développements du module, qui avancent bien avec un module qui prend forme. 

- Julien a terminé le plus gros aspect du module : le mapping des champs. Cette partie permet de controler la validité des données fournies, de transformer les données sources dans le bon format quand c'est nécessaire, de filtrer les données à importer ou non in fine, détecter les erreurs, de lister les erreurs rencontrées etc.
- La partie consistant à enregistrer un mapping est en place et fonctionnelle, on pourra mettre par défaut certains mappings avant la sortie du module en v1.0. 
- Il attaque désormais le mapping de contenu, qui sera bien plus simple et devrait être opérationnel dans les prochains jours
- Il va développer, rapidement également, le mécanisme permettant d'organiser l'interface, gérer les noms des champs etc, tel que le mécanisme est fait pour les attributs de taxhub (#12 ). On a donc 2 tables (équivalentes de bib_attributs et bib_themes) en base qui permettent de cibler un champs de la synthèse, de lui donner un nom, et préciser dans quel thème rentre le champs : on a donc une interface totalement organisable par l'administrateur. Les perspectives avec ce fonctionnement sont multiples : traduction du module, définition des champs obligatoires, champs masquables etc. 
- Enfin il va achever la partie qui envoie les données dans la synthèse mais qui est déjà pas mal avancée.

**Avec une deadline au 4 novembre, Julien devrait sortir une pré-release** donc, qui permettra d'importer des données de bout en bout, depuis un fichier csv. Cette pré-release fera l'essentiel mais ne couvrira pas encore toutes les fonctions, que julien développera pendant que nous pourrons faire les premiers tests. 

Parmi les choses à développer après la pré-release : 
- Importer un geojson
- Gérer les géométries de type wkt
- Permettre la reprise d'un import en cours
- Gérer les données sources liées à la validation
- + Corrections diverses

**Comment by DonovanMaillard** [comment]
Une version est en test (branche navigation) et des premiers retours listent les aspects fonctionnels et les aspects à perfectionner (#38 ). 

Les points suivants restent à développer dans les 4 semaines à venir. 

    Importer un geojson
    Gérer les géométries de type wkt
    Permettre la reprise d'un import en cours
    Gérer les données sources liées à la validation
        Corrections diverses

**Comment by DonovanMaillard** [comment]
Julien a terminé ce lundi son travail de développement. Le module avec l'ensemble de ses fonctionnalités est désormais en phase de test (branche develop). 

Plusieurs erreurs et soucis ont d'ores et déjà été relevés et devront être répertoriées et corrigées dans le mois à venir. La documentation d'installation sera faite très rapidement.

**Comment by DonovanMaillard** [comment]
Après la sortie d'une pré-release le 19 décembre, @JulienCorny commence les corrections de l'ensemble des erreurs déjà repérées. Il s'agit de l''ensemble des issues taguées "bug". 

Les autres issues sont des améliorations qui seront à traiter dans un second temps et ne seront pas l'objet de cette prestation aboutissant à une version 1.0.0 espérée rapidement. 

Après les premiers fix, de nouveaux tests auront lieu durant quelques jours pour voir si ces bugs n'en cachaient pas d'autres.

**Comment by DonovanMaillard** [comment]
Diverses corrections effectuées par Julien ces derniers jours en vue d'aboutir au plus vite à une version 1.0.0. 

Il reste à corriger un ou deux soucis assez rapides à gérer à priori. 

Je vérifie le bon fonctionnement de tout ce qui a été fait rapidement, je mets à jour le changelog et sors une 0.2.0 pour refaire certains tests. Afin de sortir, dès que possible, une 1.0.0.

**Comment by DonovanMaillard** [comment]
La prestation Natural Solutions visant à sortir une version 1.0.0 du module est désormais terminée, merci à @JulienCorny  et @HamoudaAmine pour leur travail. La version 1.0.0 est disponible est fonctionnelle sur GeoNature 2.3.2 et+ .

Les développements vont naturellement se poursuivre pour compléter, corriger, améliorer le module, mais ca ne sera désormais plus dans le cadre de cette prestation. Je clos ce sujet !
