### ISSUE TITLE
Erreur à l'installation du module Import: variable manquante dans blueprint.py

### ISSUE THREAD

**Issue by sogalgeeko** [PnX-SI/gn_module_import#80]
À l'installation de la version **develop** du module *gn_module_import* dans une instance Geonature en **2.3.0** sur Debian 9, j'ai le message d'erreur suivant:

```
No module named 'toolz'
Dask dataframe requierments are not installed.
[.. instructions d'installation...]
Error while installing GN module. The processus returned:
Module IMPORT
File /home/geonatureadmin/gn_module_import-develop/backend/blueprint.py must have a variable call:
    blueprint instance of Blueprint
```

Je précise que les commandes:
```
source geonature/backend/venv/bin/activate
pip install -r /home/geonatureadmin/gn_module_import-develop/backend/requirements.txt
```
ont été lancées au préalable sans erreur et que le fichier `settings.ini` du module a été correctement renseigné.

Ai-je manqué quelque chose (nouvelles dépendances, etc) ?

**Comment by TheoLechemia** [comment]
Une release est en préparation pour rendre compatible le module d'import avec le dernière version de GeoNature 2.3.1.
L'erreur remontée est lié à des librairies python necessaire au fonctionnement du module qui ne sont pas installées (la doc est incomplète).
`pip install toolz cloudpickle` solutionne le problème.

**Comment by sogalgeeko** [comment]
Merci pour ce retour. Il me semblait pourtant bien avoir vu les modules 'toolz' et 'cloudpickle' tirés en tant que dépendances des autres. Je vais vérifier à nouveau sur ma maquette.

**Comment by camillemonchicourt** [comment]
Oui voir https://github.com/PnX-SI/gn_module_import/issues/70
Sera corrigé dans la prochaine release du module compatible avec GeoNature 2.3.1

**Comment by DonovanMaillard** [comment]
Corrigé pour la version 1.0.0 du module
