### ISSUE TITLE
ID en serial

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/gn_module_import#82]
Les identifiants des imports sont auto-incrémentés en Serial.
Mais la plupart des autres IS des tables du modules sont des integer renseignés à la main.

Il vaudrait mieux tout mettre en Serial pour éviter de devoir remplir les ID à la main et d'avoir des conflits selon les instances GeoNature.

A voir si des ID ne sont pas insérés manuellement depuis le code applicatif. Quand on créé un mapping par exemple...

**Comment by DonovanMaillard** [comment]
Je suis en train de faire la modif coté bdd. Je testerai pour voir si l'appli fonctionne bien avec des serials et ferai un retour ici.

**Comment by DonovanMaillard** [comment]
Fait pour la 1.0.0
