### ISSUE TITLE
Message d'erreur du frontend incohérent

### ISSUE THREAD

**Issue by TheoLechemia** [PnX-SI/gn_module_import#83]
Lorsqu'une erreur survient, le front affiche systematiquement cette erreur dans un toaster:
` ERROR: IMPOSSIBLE TO CONNECT TO SERVER (check your connexion) `
L'erreur est en réalité différente:
`AttributeError: module 'psycopg2' has no attribute 'errors'`
Il peut être dangereux d'afficher trop de message "serveur" côté front. Donc preferer un message générique, du type "une erreur s'est produite". La vraie erreur est elle logguée dans les log serveurs.

**Comment by TheoLechemia** [comment]
non corrigé pour l'instant

**Comment by DonovanMaillard** [comment]
OK je regarderai si j'arrive a le faire ou non
