### ISSUE TITLE
erreur psycopg2

### ISSUE THREAD

**Issue by TheoLechemia** [PnX-SI/gn_module_import#84]
Lors de la 1ere étape de l'import (choix du SRID etc...) j'ai cette erreur :

```
    except psycopg2.errors.BadCopyFileFormat as e:
AttributeError: module 'psycopg2' has no attribute 'errors'
```
En python 3.6 et psycopg2 2.7.5.

**Comment by DonovanMaillard** [comment]
Est-ce que tu peux t'assurer que le front ne renvoie pas un id_error? 

J'ai viré ce matin les id "en dur" du script d'installation pour les passer en serial, j'espère que ca ne renvoie pas une erreur incohérente car les id ont changé.

**Comment by TheoLechemia** [comment]
En front ça affiche l'erreur générique "ERROR: IMPOSSIBLE TO CONNECT TO SERVER (check your connexion)" cf #83

**Comment by DonovanMaillard** [comment]
Non reproduit, @TheoLechemia tu confirmes que c'est corrigé, ainsi que #83

**Comment by TheoLechemia** [comment]
Oui, non reproduit depuis un moment

**Comment by DonovanMaillard** [comment]
OK merci. Je ferme alors
