### ISSUE TITLE
Faciliter l'évolution du module en cohérence avec l'évolution du coeur du GeoNature

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/gn_module_import#9]
Se pose la question de gérer la transformation et le contrôle ds données plutôt en SQL, ou plutôt en Python...

D'un coté, en SQL, davantage d'utilisateurs sont à l'aise avec le langage. De l'autre, python est plus adapté, plus puissant et sans doute plus fiable sur ce genre de taches, mais moins d'utilisateurs le maitrisent... Il est aussi plus simple à développer à priori (ce qui pour nous a un intérêt en termes de délais).

Plus précisément, se pose la question de... s'il est en SQL pour être plus adaptable, qu'est ce qu'on va venir y modifier? Ou autrement dit, s'il est en Python, de quoi cela priverait ceux qui n'ont pas les compétences comme moi ... (GN comporte énormément de choses en python par ailleurs). 

Le module, dans son fonctionnement et son éventuelle évolution, dépend surtout de la table synthèse. Avoir un module surtout SQL permettrait de faciliter son entretien dans le cas où la table synthèse évolue (ajout de champs, suppression, modifications de types etc).... La question est donc : dans quelle mesure la synthèse est-elle amenée à évoluer.. Et comment faire pour que le module import puisse s'adapter à un ajout ou une modification de champs sur la synthèse. Et est-ce qu'il est pertinent de rendre ces adaptations accessibles à un maximum de personnes ?

Si la synthèse a vocation a évoluer très peu, très fréquemment et à ne pas être personnalisable à souhait, il est acceptable que le module d'import soit en python et moins adaptable par les gestionnaires de base.
Si on part du principe qu'un administrateur d'instance doit pouvoir ajouter / supprimer / modifier des champs à la synthèse à sa guise, le SQL semblerait plus accessible. Je n'ai pas de réponse sur ce sujet : dans mon esprit, la synthèse est plutôt vouée à être stable et standard, donc on serait plutôt dans le 1er cas, mais je ne voudrais pas fermer de porte, j'attends donc l'avis des experts.

A noter que pour les champs qui reposent sur une nomenclature, il est prévu qu'une table soit ajoutée dans gn_commons (#4 ) pour stocker le nom du champs, et le type de nomenclature qui correspond. Ajouter un champs de nomenclature est donc plus facile à faire qu'un champs type "auteur de la preuve numérique" pour laquelle il faut aller récupérer des rôles. Toutes les modifications n'auraient donc pas la même difficulté :) (sinon c'est pas drole)

**Comment by camillemonchicourt** [comment]
1. La synthèse a une structure fixe et n'a pas vocation à être modifiée localement. Si les gens le font c'est à leur risque et péril et il est fort possible que pas mal de choses ne fonctionnent plus sur GeoNature. 

2. De mon point de vue et de ce que j'ai retenu, il est intéressant de pouvoir gérer les nomenclatures et champs au niveau de la BDD. Ainsi si on ajoute une nouvelle nomenclature / un nouveau champ dans la Synthèse, alors on n'a pas besoin de modifier le code du module. C'est ce qui est prévu dans une table dédiée que tu cites. Au-delà de ça, pour moi le reste doit être fait en Python. Idéalement de manière assez générique et bien commentée pour faciliter les futures évolutions de la Synthèse.

**Comment by DonovanMaillard** [comment]
La table dans GN common ne touche que les nomenclatures. Pas les autres. Tout ce qui appelle un id rôle est en dur dans le module donc si on ajoute un champ "auteur de la preuve numérique" par exemple la table common ne pourra rien faire. A voir pour avoir une conf plus globale dans ce cas... Mais c'est pas forcément évident à mettre en place

**Comment by camillemonchicourt** [comment]
Oui pour moi les nomenclatures suffisent.

**Comment by DonovanMaillard** [comment]
A mon sens aussi. C'est ce qui est le plus susceptoble d'évoluer ou d'évoluer le plus vite
