### ISSUE TITLE
Import de métadonnées du SINP

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/gn_module_import#96]
Théo et moi avons mis en place un script qui permet, en python, de récupérer les fichiers XML du webservice INPN, de les découper et d'intégrer les données correspondantes dans la BDD (https://github.com/PnX-SI/GeoNature/tree/master/data/scripts/import_mtd). 

Il serait intéressant qu'à l'étape du choix du JDD, dans le module d'import, on puisse également "importer un jeu de données du SINP". Il suffirait alors de renseigner son UUID, et que le module lance le script (voir geonature/data/scripts) pour récupérer les mtd en question... puis poursuivre l'import dans le jdd importé. 

A voir si ca doit se trouver dans le module d'imports, dans le module métadata ou dans les deux. Il y a un coté pratique à l'avoir dans le module d'import, mais c'est pas forcement cohérent au niveau des droits (j'ai les droits sur mtd mais par import, je peux pas importer des mtd. Ou inversement, j'ai les droits sur import et pas mtd, et pourtant je peux importer des mtd...). Dans tous les cas, à voir où la placer, mais cette possibilité serait un plus! (avec peut être un nettoyage ou une amélioration nécessaire du script au passage).

**Comment by DonovanMaillard** [comment]
Rien de fait de ce coté pour le moment, mais pourrait être utile pour limiter les jeux créés dans plusieurs instances : est-ce que vous pensez qu'un import de jeux de données depuis l'instance nationale a plutôt sa place dans le module d'import ou dans le module métadonnées ?

**Comment by camillemonchicourt** [comment]
Actuellement le module d'import est vraiment orienté pour importer depuis un fichier.
Là il s'agirait d'importer depuis un flux.
Donc c'est assez différent comme approche, mais peut-être que c'est aussi une vocation du module à moyen terme.

**Comment by DonovanMaillard** [comment]
En soit, je me dis que le fonctionnement actuel est de gérer les métadonnées dans le module méta, avant de faire son import. Et qu'importer un JDD peut intéresser des acteurs qui font de la saisie sous occtax. Je verrais bien cette fonctionnalité dans le module métadonnée, qui laisserait alors le choix entre créer un JDD ou importer les infos d'un JDD. Avec un paramètre pour activer ou non cette fonction selon qu'on travaille, ou non, avec les métadonnées du catalogue national.

**Comment by bouttier** [comment]
Je suis également pour garder la gestion des méta-données dans le module méta-données, et ne pas tout mélanger.

**Comment by DonovanMaillard** [comment]
oui et pour avoir retravaillé sur "mon" script d'import de données depuis les xml nationaux, il y a plusieurs soucis qui font que ces imports ne sont pas du tout mûrs pour intégrer GN : 

- Le script python fonctionne OK, mais n'est (vraiment) pas propre du tout
- Ca intègre des acteurs, des organismes ou personnes au niveau du schema utilisateurs, ca doit sans doute etre discuté
- Accessoirement les fichiers XML fournis au niveau national ne sont pas "propres" non plus, dans le sens ou ils ne sont pas à jour avec les standards à un instant t. A l'heure actuelle par exemple ils utilisent en production des évolutions de standards qui ne sont pas encore validées et n'apparaissent nulle part...
