### ISSUE TITLE
Ne pas imposer l'association des mappings aux rôles

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/gn_module_import#98]
Actuellement chaque mapping est associé à un ou plusieurs rôles (dans la table ``gn_imports.cor_role_mapping``). Quand un utilisateur créé un mapping, alors cette table est renseignée automatiquement et lui uniquement peut utiliser ce mapping.

C'est bien pour les mappings spécifiques que se constitue chaque utilisateur, mais moins pour les mappings génériques qui ont vocation à être partagés. 

On pourrait imaginer que si un mapping n'est associé à aucun rôle, alors tous les utilisateurs y accèdent ?
Cela éviterait aussi de remplir la table lors de l'installation du module, avec des rôles de démo en dur dans le SQL, qui ne sont pas présents sur toutes les instances (https://github.com/PnX-SI/gn_module_import/blob/master/data/default_mappings_data.sql#L22-L31)

**Comment by camillemonchicourt** [comment]
Lors de l'installation et de l'association des mappings fournis par défaut, les rôles par défaut ne sont plus renseigné en dur. On les associe à tous les rôles ayant accès à GeoNature : https://github.com/PnX-SI/gn_module_import/commit/94128dff17262458a0a00de8d591b74ec049c966

**Comment by camillemonchicourt** [comment]
Finalement on ne renseigne plus tous les rôles ayant accès à GeoNature dans la table liant les rôles et les mappings, car c'était peu satisfaisant.

Désormais il y a un CRUVED sur les objets MAPPINGS. Mais à clarifier entre son fonctionnement actuellement partiel, et le fonctionnement et l'usage de la table ``gn_imports.cor_role_mapping``.

**Comment by camillemonchicourt** [comment]
``gn_imports.cor_role_mapping`` est fait pour stocker les auteurs d'un mapping. Elle sert donc à donner ou non accès à un mapping.
Mais pour donner accès à un groupe d'agents à un mapping commun, il vaut mieux leur donner un R 2 ou 3 sur les mappings, et idéalement à terme ajouter la possibilité de créer des mappings publics.

**Comment by DonovanMaillard** [comment]
Oui, et l'idéal serait que pour les mappings publics, seul l'auteur ait le droit d'enregistrer durablement des modifications.

**Comment by camillemonchicourt** [comment]
Oui ça c'est lié au CRUVED des utilisateurs sur les Mappings.

**Comment by TheoLechemia** [comment]
Je viens d'ajouter la notion de public sur les mappings. 
Tout le monde voit ces mappings, et seuls ceux qui ont des droits U=3 peuvent les modifier.
Les mappings fournis par défaut sont noté comme "public" (pas d'update en raison de la diversité des noms de mappings)
Il n'y a pas de possibilité de créer un mapping public en interface pour l'instant

**Comment by camillemonchicourt** [comment]
Mais si par ailleurs je suis auteur d'un mapping public (dans cor_role_mapping) et que j'ai CRUVEd U de 1 ou 2, je devrais quand même pouvoir modifier ce mapping public, non ?

**Comment by TheoLechemia** [comment]
Oui. Corrigé
